### ISSUE TITLE
Создать дизайн для мобильного приложения

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#1]
Описание задачи еще не сформировано до конца!
Разработать дизайн мобильного приложения для экрана с расширением 720*1280
Полученный результат прикрепить к этому таску в виде архива с изображениями.
В комментариях указать инструмент в котором разрабатывались изображения, а на гугл диск сохранить проект. 
В задаче указать не публичную ссылку на гугл диск на папку с материалами

Требования к дизайну:
На данном этапе требуется создать светлую тему приложения. Пользователю должно быть доступно меню со всех экранов кроме тех, где происходит редактирование информации. Из меню должен быть переход на вкладки личного профиля (кроме как с экрана личного профиля), списка организаций, закладки, о нас, справка, закладки.  
Конкретные экраны сточки зрения гражданина:
Конкретные экраны с точки зрения организации:

**Comment by YuriSilenok** [comment]
Здравствуйте @KharlamovaAlexandra,

пожалуйста, добавьте в описание задачи требования к дизайну.

Спасибо,
Юрий

**Comment by YuriSilenok** [comment]
Эта задача в скором времени будет упразднена, так как макет для всех страниц не является приоритетной задачей. Пожалуйста, не теряйте имеющиеся наработки.

Пожалуйста, внесите сведения в лист [Внешние ресурсы](https://docs.google.com/spreadsheets/d/1_VXvt3NKFBgEVKcyeg0LyD6IChBUCVRLu2lNqyrgelQ/edit#gid=902675410), о том, как попасть в редактор макета.

**Comment by KharlamovaAlexandra** [comment]
Закрыта за потерей актуальности
