### ISSUE TITLE
Подключится к базе данных

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#10]
Основная задача #7 
В личном кабинете MySQL создать таблицу user (id, login, password) в БД id10080061_rayofhope и заполнить ее данными (2-3 записи).
На любом язые программирования выполнить следующее:
1. Найти библиотеку для работы с MySQL
2. Сформировать строку подключения к БД
3. Получить данные из таблицы user

Задача считается выполненой, когда в таблице "Команда", на листе "Внешние ресурсы" в стрку MySQL в столбец Данные для подключения? записать строку подключения к БД.

**Comment by YuriSilenok** [comment]
@KharlamovaAlexandra добавил больше деталей в описание задачи.

**Comment by KharlamovaAlexandra** [comment]
Я думаю ее можно закрыть?

**Comment by YuriSilenok** [comment]
Закрыто, так как решено использовать в место библиотеки для MySQL написанные скрипты на PHP
