### ISSUE TITLE
Реализовать добавление постов организацией в Web

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#100]
Epic #97
Макеты #99

**Comment by KharlamovaAlexandra** [comment]
@stasshtaub  Каково состояние задачи?

**Comment by stasshtaub** [comment]
Верстку закончил. Ее никак не проверить, у нас кончился хостинг и сайт не работает

**Comment by KharlamovaAlexandra** [comment]
Хостинг работает
@MoL4okkk  проверить есть ли задача на тестирование данного функционала, если нет, поднять и закрыть эту

**Comment by MoL4okkk** [comment]
Задачи на тестирование подняты
