### ISSUE TITLE
Описание организации хранения данных на сервере

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#102]
Прикрепить в комментариях диаграмму описывающую предполагаемое состояние сервера.
В комментариях сделать небольшое описание технологий, которые будут использоваться, чтобы все могли ознакомиться и понять при желании
Доставить метки

**Comment by KharlamovaAlexandra** [comment]
@Svyat935  Состояние задачи?

**Comment by Svyat935** [comment]
На мой взгляд сделано 70%. Тупняк с понимание YII2. Решается. . .

**Comment by Svyat935** [comment]
[Диаграмма](https://drive.google.com/drive/u/0/folders/1uZcLnlfH22Ao3dcCLSQZrZ_Z4gee8_l5)

**Comment by Svyat935** [comment]
Используется Framework YII2. Он реализует шаблон MVC, высокий функционал для безопасности, имеет высокую скорость.

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  поднять задачу на тестирование диаграммы и закрыть эту задачу

**Comment by MoL4okkk** [comment]
Задача на тестирование поднята, в процессе

**Comment by MoL4okkk** [comment]
@KharlamovaAlexandra, задачу поднял, ссылки проставил, могу закрыть?

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  закрывай
