### ISSUE TITLE
Сделать макет публикации постов для Android

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#103]
Story: #99
Epic: #97

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/folderview?id=1BcokszTVImmRaY0G2VPgB4eINa6hj5Va)
[Видео-демка](https://drive.google.com/file/d/1BlxzqmXhA9iGa6jSlKksGcG6v-esXIYG/view?usp=drivesdk)

Новая нужда
![новая нужда](https://user-images.githubusercontent.com/47520675/66715165-afc9f080-edc8-11e9-875d-867aa3a109b7.jpg)

Новое мероприятие
![новое мероприятие](https://user-images.githubusercontent.com/47520675/66715166-b0628700-edc8-11e9-8462-2da56c84f86c.jpg)

Время мероприятия
![время мероприятия](https://user-images.githubusercontent.com/47520675/66715170-b48ea480-edc8-11e9-9251-d164c5843ec4.jpg)

Место мероприятия
![место мероприятия](https://user-images.githubusercontent.com/47520675/66715169-b35d7780-edc8-11e9-81f4-87879b3c5ba4.jpg)

Новое событие
![новое событие](https://user-images.githubusercontent.com/47520675/66715167-b193b400-edc8-11e9-862f-145915774f18.jpg)

С текстом и картинками
![текст+картинки](https://user-images.githubusercontent.com/47520675/66715174-b6586800-edc8-11e9-90b1-6ea73cc19a74.jpg)

Выбор типа записи
![тип записи](https://user-images.githubusercontent.com/47520675/66715168-b22c4a80-edc8-11e9-93ef-e1e8a893a463.jpg)

**Comment by KharlamovaAlexandra** [comment]
Мне нравится, можно передавать в тестирование

**Comment by KharlamovaAlexandra** [comment]
Тоже не заметила что даты должно быть две

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/drive/u/1/folders/1BcokszTVImmRaY0G2VPgB4eINa6hj5Va)
[Видео-демка](https://drive.google.com/open?id=1BlxzqmXhA9iGa6jSlKksGcG6v-esXIYG)

![время начала мероприятия](https://user-images.githubusercontent.com/47520675/67212360-f224aa80-f424-11e9-854a-8e50dd136166.jpg)
![время завершения мероприятия](https://user-images.githubusercontent.com/47520675/67212359-f18c1400-f424-11e9-8a77-c6df0c1b6ffa.jpg)

**Comment by KharlamovaAlexandra** [comment]
Теперь вроде все

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  Создать задачу на тестирование, повесить ее на Илью и закрыть эту

**Comment by MoL4okkk** [comment]
Тестируется
