### ISSUE TITLE
Исследование по возможности нахождения нескольких организаций по одному адресу

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#105]
Нужно провести исследование и ответить на вопрос: может ли несколько организаций находится по одному и тому же адресу?

**Comment by KharlamovaAlexandra** [comment]
Пойдет на 4 спринт. Но я сама переделаю

**Comment by KharlamovaAlexandra** [comment]
Завершено
