### ISSUE TITLE
Стартовая страница приложения на android не соответствует макету

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#108]
Ожидаемый результат: Стартовая страница приложения на android соответствует макету
Фактический результат: Стартовая страница приложения на android не соответствует макету

**Comment by YuriSilenok** [comment]
Выполнить действия аналогично [этому](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/109#issuecomment-546580018) комментарию

**Comment by MoL4okkk** [comment]
Баг не воспроизводится в версии v.0.0.20191015.3 Android-приложения и более поздних
