### ISSUE TITLE
Меню приложения на android не соответствует макету

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#109]
Ожидаемый результат: Меню приложения на android соответствует макету
Фактический результат: Меню приложения на android не соответствует макету

**Comment by KharlamovaAlexandra** [comment]
Что  - то исправляется?

**Comment by YuriSilenok** [comment]
Всем привет.
- На @ZhezlovaDaria висит задача и 22 числа был выполнен мерж ветки. Почему эта задача не была сразу перевешена на тестирование?
- @MoL4okkk необходимо указывать причину закрытия бага, например Баг не воспроизводится в версии такой-то (как узнать версию, может рассказать @ZhezlovaDaria ). 

ИТОГ:

**Comment by MoL4okkk** [comment]
Баг не воспроизводится в версии v.0.0.20191022.6 Android-приложения и более поздних

**Comment by YuriSilenok** [comment]
> Баг не воспроизводится в версии v.0.0.20191022.6 Android-приложения и более поздних

О каких поздних версия идет речь, баг проверялся еще где-то?
