### ISSUE TITLE
Описание технологий для разработки сайта

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#11]
Основная задача #7 
Отписать в комментариях технологии, которые будут использоваться для разработки сайта

**Comment by YuriSilenok** [comment]
Можно предоставить в виде гугл презентации.
Возможно даже с разказом в конце спринта.

**Comment by stasshtaub** [comment]
HTML5+CSS для верстки.
JQuery для анимации и функционала по типу входа, регистрации, поиска и т.д.
