### ISSUE TITLE
При удачной авторизации открывается пустая страница в приложении на android

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#110]
1. Открыть приложение.
2. Перейти на экран входа в организацию.
3. Ввести корректные данные существующей организации.
4. Нажать войти.
5. Открывается страница профиля без данных (пустая).

Ожидаемый результат: открывается страница с данными 
Фактический результат: открывается пустая страница

#78

**Comment by MoL4okkk** [comment]
Баг не воспроизводится в версии v.0.0.20191015.3 Android-приложения
