### ISSUE TITLE
Разработка ERD

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#111]
Epic: https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/97

Реализовать диаграмму БД.

Ссылка на диаграмму: https://drive.google.com/file/d/1FJN7N_neTjjD3xudElrtnqAcYWNxJU1Y/view?usp=sharing

**Comment by KharlamovaAlexandra** [comment]
Прикрепи ссылку на файл

**Comment by XeniaWorontsova** [comment]
https://drive.google.com/file/d/1FJN7N_neTjjD3xudElrtnqAcYWNxJU1Y/view?usp=sharing

**Comment by KharlamovaAlexandra** [comment]
Заполнить описание задачи

**Comment by KharlamovaAlexandra** [comment]
@XeniaWorontsova  жива задача?

**Comment by KharlamovaAlexandra** [comment]
@XeniaWorontsova  Закрываем наверно уже?
