### ISSUE TITLE
Реализация таблиц в БД

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#112]
Epic: https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/97, https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/164

Реализовать таблицы и связи между ними в соответствии с ERD.

**Текущее состояние:** 
Все, что присутствует сейчас на ERD реализовано в полном объеме

**Comment by KharlamovaAlexandra** [comment]
Заполнить описание задачи и отписаться про состояние

**Comment by XeniaWorontsova** [comment]
> Заполнить описание задачи и отписаться про состояние

Сделано

**Comment by KharlamovaAlexandra** [comment]
@XeniaWorontsova  что с задачей?

**Comment by KharlamovaAlexandra** [comment]
@XeniaWorontsova  Думаю стоит закрывать
