### ISSUE TITLE
Найти способ для разворачивания всей БД без потери данных

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#114]
https://hpanel.hostinger.com/hosting/rayofhope-opensource.hostingerapp.com/files/backups
Здесь хранятся бэкапы всего. Судя по sql-коду, таблички восстановятся. Единственная проблема - связи.

Осталось выяснить откуда ноги растут у этих файлов.

**Comment by XeniaWorontsova** [comment]
https://hpanel.hostinger.com/hosting/rayofhope-opensource.hostingerapp.com/files/backups
Здесь хранятся бэкапы всего. Судя по sql-коду, таблички восстановятся. Единственная проблема - связи.

Осталось выяснить откуда ноги растут у этих фалов.

**Comment by YuriSilenok** [comment]
> https://hpanel.hostinger.com/hosting/rayofhope-opensource.hostingerapp.com/files/backups
> Здесь хранятся бэкапы всего. Судя по sql-коду, таблички восстановятся. Единственная проблема - связи.
> 
> Осталось выяснить откуда ноги растут у этих файлов. @YuriSilenok, @KharlamovaAlexandra

Пожалуйста, перенеси этот комментарий в описание задачи. 

Бэкапы я не делал, они должны делаться автоматически

**Comment by XeniaWorontsova** [comment]
Закрыта в связи с созданием https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/146
