### ISSUE TITLE
Сделать макет публикации нового поста для Web

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#116]
Epic #97 
Story #99

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/open?id=1Kq8uVmjbUTz-9uN78xkgNIil6A3bQHCZ)

Новое событие
![новое событие](https://user-images.githubusercontent.com/47520675/67105602-bb0a8b00-f1d1-11e9-8d83-85ae4ac3821f.jpg)

Новая нужда
![новая нужда](https://user-images.githubusercontent.com/47520675/67105601-bb0a8b00-f1d1-11e9-903a-88a4ae7e28b4.jpg)

Новое мероприятие
![новое мероприятие](https://user-images.githubusercontent.com/47520675/67105603-bb0a8b00-f1d1-11e9-9318-96e22705686d.jpg)

**Comment by KharlamovaAlexandra** [comment]
У нового мероприятия должно быть две даты, конечная и начальная

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/open?id=1Kq8uVmjbUTz-9uN78xkgNIil6A3bQHCZ)

Новое мероприятие
![новое мероприятие](https://user-images.githubusercontent.com/47520675/68127281-9a0e9d80-ff26-11e9-8d78-12e846679b34.jpg)

**Comment by KharlamovaAlexandra** [comment]
Если «Новая запись» подразумевает название ( не очень понятно ), то все вроде соответсвует описанию

**Comment by stasshtaub** [comment]
Выбранный тип записи выделяется слева жирным. Если надо, могу продублировать вместо "новой записи"

**Comment by KharlamovaAlexandra** [comment]
У нас у постов еще заголовок есть
Я думаю, он вообще не особо нужен. Но так считают не все. В бд он вообще вроде как обязательный

https://docs.google.com/document/d/1p0aFXnl3jeQWKu_cQHuSFoc59WKs-PMpChTdkxWICBA

**Comment by stasshtaub** [comment]
Первый раз про него слышу. Если решите его оставить, напиши здесь. Надо будет переделать все макеты постов веба и под андроид

**Comment by KharlamovaAlexandra** [comment]
Хорошо, пока так сверстай. Если что, переделать не очень долго будет

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk Поднять задачу на тестирование и закрыть эту

**Comment by MoL4okkk** [comment]
Тестируется
