### ISSUE TITLE
Написать хранимую процедуру добавления нового поста организации

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#117]
Написать в бд процедуру, которая, если пришли корректные данные, добавляет новую запись о посте в таблицу и возвращает true, иначе возвращает false

Доставить метки

**Comment by XeniaWorontsova** [comment]
Процедура написана в "грязном" виде.

**Comment by YuriSilenok** [comment]
> Процедура написана в "грязном" виде для мероприятия. Будет сделана лучше, когда появится структурированная информация от Сергея.

Здесь необходима ссылка на таск Сергея который блокирует выполнение этого таска

**Comment by XeniaWorontsova** [comment]
Так как сервер пока очень сильно отстает, я думаю, нет смысла, писать хранимые процедуры для 'середины функционала'. Буду действовать поэтапно, чтобы Сергею не надо было самосоятельно писать запросы для начальных действий.

**Comment by YuriSilenok** [comment]
> Так как сервер пока очень сильно отстает, я думаю, нет смысла, писать хранимые процедуры для 'середины функционала'. Буду действовать поэтапно, чтобы Сергею не надо было самосоятельно писать запросы для начальных действий.

все же хотелось понять по

**Comment by YuriSilenok** [comment]
На митинг вынесу необходимость статуса Pending

**Comment by XeniaWorontsova** [comment]
Процедуры созданы и буду описаны в отдельных тасках. Можно будет найти по ссылке: https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/131
