### ISSUE TITLE
Начать диаграмму классов для Сервера приложений

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#120]
Диаграмму классов создавать в программе draw.io 
Файл должен быть создан на гугл диске, ссылка прикрплена в описание задачи

**Comment by YuriSilenok** [comment]
@Svyat935, пожалуйста, запони задачу

**Comment by KharlamovaAlexandra** [comment]
@Svyat935  Что с задачей?

**Comment by KharlamovaAlexandra** [comment]
Закрыто как дубликат #102 задачи
