### ISSUE TITLE
Согласовать метаданные

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#126]
https://drive.google.com/folderview?id=1uZcLnlfH22Ao3dcCLSQZrZ_Z4gee8_l5

Папочка с файликами
Интересует диаграмма структура сущностей
И папка Сущности как они есть

**Comment by urec-programmec** [comment]
https://drive.google.com/folderview?id=1uZcLnlfH22Ao3dcCLSQZrZ_Z4gee8_l5

Папочка с файликами
Интересует диаграмма структура сущностей
И папка Сущности как они есть

**Comment by YuriSilenok** [comment]
Пожалуйста, перенеси комментарий в дескрипшен задачи
![image](https://user-images.githubusercontent.com/14871471/67616148-f9113b80-f7dd-11e9-81bb-eb21d4b87fcc.png)

**Comment by XeniaWorontsova** [comment]
Оставила комментарии в документе "Пользователи". @urec-programmec , жду ответа

**Comment by YuriSilenok** [comment]
> Пожалуйста, перенеси комментарий в дескрипшен задачи
> ![image](https://user-images.githubusercontent.com/14871471/67616148-f9113b80-f7dd-11e9-81bb-eb21d4b87fcc.png)

@urec-programmec
Напоминаю об этом
