### ISSUE TITLE
Сравнить диаграмму классов и реализацию

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#127]
Сравнить диаграмму классов и библиотеку приложения на Android

**Comment by YuriSilenok** [comment]
@MoL4okkk, пожалуйста, заполните описание, метки, проект, веху задачи

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  Ты можешь закрыть задачу

**Comment by MoL4okkk** [comment]
Задача выполнена, результаты сравнения [здесь](https://docs.google.com/spreadsheets/d/1ZsDGr790sF5plt7eP-ErbjunOLC8SOAxHfSMMAai69U/edit#gid=0)
