### ISSUE TITLE
Оплатить хостинг

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#128]
Оплатить один месяц и подготовить смету финансовых потребностей

**Comment by YuriSilenok** [comment]
Оплачено

**Comment by YuriSilenok** [comment]
@KharlamovaAlexandra посмотри пожалуйста [эту](https://docs.google.com/spreadsheets/d/1Js1QaxwEXyI7kyg8yKNeN-nBXRF9XszH1SUrqn8-xRw/edit#gid=0) смету

**Comment by KharlamovaAlexandra** [comment]
Смета ужасает. Требуется обсуждение

**Comment by YuriSilenok** [comment]
Хостинг оплачен сегодня в последний раз
