### ISSUE TITLE
Устранить несоответствия между диаграммой классов Android и их реализацией

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#129]
В ходе выполнения задачи #127 были обнаружены расхождения между диаграммой классов и самими классами приложения на Android.
[Список расхождений](https://docs.google.com/spreadsheets/d/1ZsDGr790sF5plt7eP-ErbjunOLC8SOAxHfSMMAai69U/edit#gid=0)

**Comment by KharlamovaAlexandra** [comment]
Проверить соответствует ли этим изменениям, если да, то внести соответствующие задания в документацию. Если еще остались не исправленные  то повторно оповестить Дарью о необходимости исправления этого бага

- Удаление методов onCreateOptionsMenu, onOptionItemSelected и onNavigationItemSelected, больше не требующихся
- Добавлен класс GalleryAdapter
- Добавлены в класс OrgView и MyProfOrg методы и свойства, которые на данный момент позволяют хранить данные

**Comment by Svyat935** [comment]
Тестирование завершенно, результаты сравнения [здесь](https://docs.google.com/spreadsheets/d/1ZsDGr790sF5plt7eP-ErbjunOLC8SOAxHfSMMAai69U/edit#gid=0)

**Comment by MoL4okkk** [comment]
Несоответствия устранены, багов нет
