### ISSUE TITLE
Нати библиотеку

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#13]
Найти библиотеку для общения с mySql для операционной системы Android. Отписаться о результате в комментариях

**Comment by ZhezlovaDaria** [comment]
Предлагаю использовать JDBC.

**Comment by YuriSilenok** [comment]
У меня нет возражений. Использую то что удобнее

**Comment by KharlamovaAlexandra** [comment]
Одобрено
