### ISSUE TITLE
Создать хранимые процедуры

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#131]
Epic: https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/97, https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/164

Были реализованы:

1. ХП для регистрации организации
2. ХП для авторизации организации
3. ХП для регистрации гражданина
4. ХП для авторизации гражданина
5. ХП для публикации мероприятия
6. ХП для публикации нужды
7. ХП для публикации события

**Список будет обновляться**

Описание к ХП можно найти либо поиском по заголовкам тасков (заголовки перечислены в списке "Были реализованы"), либо по прикрепленным задачам.

**Comment by KharlamovaAlexandra** [comment]
Мама, спаси.... ЧТо это в описании?
@YuriSilenok 
 Где родительские задачи?
Где приоритет и сложность?
Выполнена ли задача?

**Comment by XeniaWorontsova** [comment]
> Мама, спаси.... ЧТо это в описании?
> @YuriSilenok
>  Где родительские задачи?
> Где приоритет и сложность?
> Выполнена ли задача?
Эта задача и является родительской. 
Я поставила приоритет и сложность, но это немного спорный момент, потому что эта задача - лягушка путешествиница, она не будет закончена, пока не будет закончен проект. Поэтому я не знаю, что ей ставить. Это не стори, не эпик, что это?

**Comment by KharlamovaAlexandra** [comment]
Родителем является эпик, но теперь все норм. Эта же задача является стори.
Со сложностью не согласна. Думаю она  O8

**Comment by YuriSilenok** [comment]
> Мама, спаси.... ЧТо это в описании?

В описании перечислены заголовки хранимых процедур которые необходимо реализовать, этими заголовками в последствии будет пользоваться сервер. Это форма договоренности. БД обеспечивает что такие хранимые процедуры будут, а сервер может писать код вставляя вызовы этих хранимых процедур

**Comment by XeniaWorontsova** [comment]
Описание исправлено

**Comment by XeniaWorontsova** [comment]
Закрыта, так как в дальнейшем будут создаваться задачи на каждый спринт
