### ISSUE TITLE
ХП для авторизации организации

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#132]
Реализовано.

**Имя процедуры:**
authorization_organization

**Входные параметры:**

1. in_login
ИНН/email
Тип: строка
2. in_password
Пароль
Тип: строка
3. login_is_INN
Если в качестве логина передан ИНН, то значение 1, иначе - 0
Тип: int, только 0 или 1

**Результат:**
В случае ошибки возвращается эксепшен с кодом 45000 и текстом: "Неверно введен логин или пароль"

https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/131

**Comment by XeniaWorontsova** [comment]
Реализовано

**Comment by YuriSilenok** [comment]
Заполнить метаданные задачи
