### ISSUE TITLE
Составить сценарии тестирования написания постов в WEB

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#135]
Epic #97

Написать сценарии тестирования и занести их в [таблицу](https://docs.google.com/spreadsheets/d/1QX80ipwa-VqxpP4v4vkhY62S_wfBev07Xq2Ys48WiyM/edit#gid=442656046)

Story #98

**Comment by KharlamovaAlexandra** [comment]
Существуют ли сценарии? Если да, то почему задача открыта?

**Comment by MoL4okkk** [comment]
Сценарии написаны
