### ISSUE TITLE
Составить сценарии тестирования написания постов в Android-приложении

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#136]
Epic #97

Написать сценарии тестирования и занести их в [таблицу](https://docs.google.com/spreadsheets/d/16dMIPuW4tlPUntkUoM8C1TRME36dK9TPxPu8maahwFE/edit#gid=1540234671)

Story #98

**Comment by KharlamovaAlexandra** [comment]
Существуют ли сценарии? Если да, то почему задача открыта?

**Comment by MoL4okkk** [comment]
Сценарии написаны, ожидается тестирование
