### ISSUE TITLE
Написать триггеры

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#138]
Epic: https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/164

1) Триггеры на логирование действий пользователя

Задача будет редактироваться по мере появления новых запросов или идей

**Comment by XeniaWorontsova** [comment]
Реализован триггер на добавление, изменение, удаление комментариев

**Comment by KharlamovaAlexandra** [comment]
Почему в описании нет перечисления нужных триггеров?

**Comment by KharlamovaAlexandra** [comment]
Метка sprint5 не должна была быть снята

**Comment by KharlamovaAlexandra** [comment]
В честь чего появилась та задача? Где основания для него? эпики или стори

**Comment by XeniaWorontsova** [comment]
> Почему в описании нет перечисления нужных триггеров?

Исправлено



> В честь чего появилась та задача? Где основания для него? эпики или стори

Очень хороший вопрос. Основание: требование Нины Олеговны, чтобы в БД присутствовал триггер. Как это оформить - не знаю

**Comment by KharlamovaAlexandra** [comment]
У тебя нет  эпика на создание с БД. Надо создать. Перечислить все этапы на создание БД. Прикрепить все глобальные задачи связанные с этими этапами и в том числе ванную задачу. Один из этапов будет являться основанием для этой задачи

**Comment by XeniaWorontsova** [comment]
> У тебя нет эпика на создание с БД. Надо создать. Перечислить все этапы на создание БД. Прикрепить все глобальные задачи связанные с этими этапами и в том числе ванную задачу. Один из этапов будет являться основанием для этой задачи

Сделано

**Comment by XeniaWorontsova** [comment]
Закрыта, так как в дальнейшем будут создаваться задачи на каждый спринт
