### ISSUE TITLE
Разработать Story-01. Регистрация благотворительной организации 

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#141]
[Story-01. Регистрация благотворительной организации](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
В спецификации имеются открытые вопросы, значит ли это, что спецификация еще не закончена?

**Comment by KharlamovaAlexandra** [comment]
Она как бы закончена, но я бы не сказала что это нормальная спецификация

**Comment by YuriSilenok** [comment]
Всё что не нормально поправится сиарами
