### ISSUE TITLE
Провести классификацию стейкхолдеров

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#142]
Epic #156 
Ссылка на документ: https://docs.google.com/document/d/1ucdk1l_mxY_3h2d5SHRILegXccvve2WQJGWWx3jFaIU

https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/148

**Comment by KharlamovaAlexandra** [comment]
Что ты подразумеваешь под классификацией?

**Comment by KharlamovaAlexandra** [comment]
И почему нет родительской задачи ( story )  на работу со стейкхолдерами?

**Comment by XeniaWorontsova** [comment]
> Что ты подразумеваешь под классификацией?

В самом документе это указано. 
"Классификацию заинтересованных сторон: внешняя/внутренняя, воздействие/влияние/власть/интерес, сверху вниз / снизу вверх /наружу /в сторону или иная модель классификации. "

**Comment by KharlamovaAlexandra** [comment]
Каком документе, где ссылка?

**Comment by KharlamovaAlexandra** [comment]
Кроме того, кого ты классифицируешь, если небыли задачи на выявление стейкхолдеров?

**Comment by XeniaWorontsova** [comment]
> Каком документе, где ссылка?

Добавила

**Comment by XeniaWorontsova** [comment]
> Кроме того, кого ты классифицируешь, если небыли задачи на выявление стейкхолдеров?

Добавлена

**Comment by KharlamovaAlexandra** [comment]
Выполнена ли задача?

**Comment by XeniaWorontsova** [comment]
> Выполнена ли задача?

она будет переделываться

**Comment by XeniaWorontsova** [comment]
Выполнено
