### ISSUE TITLE
Разработать Story-02. Авторизация благотворительной организации

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#144]
Epic #61
Описание задачи должно содержать в себе ссылку на документ с разрабатываемой стори

**Comment by YuriSilenok** [comment]
Я не смог найти спецификацию на авторизацию организации

**Comment by KharlamovaAlexandra** [comment]
Это потому чтоб не существует

**Comment by KharlamovaAlexandra** [comment]
Есть #66 и #67 задача. Но непонятно что должно быть в документе?

**Comment by YuriSilenok** [comment]
В документе описываетеся поведение при авторизации, а когда длоходжишь до блоков с различеным поведенеим на андроид или веб, пишеш - "Специфично для Android" и тут можно отсылки и на макеты давать и на что-то еще

**Comment by KharlamovaAlexandra** [comment]
Разработано
[спека](https://docs.google.com/document/d/1tc8xZATtXaF6GUWpDQYYTfyn8zvWJbQeJYwcmKPkdW4/edit)
@MoL4okkk  на тестирование

**Comment by MoL4okkk** [comment]
Задача на тестирование поднята
