### ISSUE TITLE
Идентификация заинтересованных сторон

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#148]
Epic #156 
Ссылка на документ: https://docs.google.com/document/d/1ucdk1l_mxY_3h2d5SHRILegXccvve2WQJGWWx3jFaIU

**Comment by KharlamovaAlexandra** [comment]
будет ли продолжаться выявление стейкхолдеров или это можно передавать в тестирование?

**Comment by XeniaWorontsova** [comment]
> будет ли продолжаться выявление стейкхолдеров или это можно передавать в тестирование?

Пока продолжается

**Comment by KharlamovaAlexandra** [comment]
А когда оно закончится?

**Comment by KharlamovaAlexandra** [comment]
Точнее какой момент считается конечно точкой исследования?

**Comment by XeniaWorontsova** [comment]
> А когда оно закончится?

Должно было во вторник. К сожалению, все не так, как хотелось бы. Ограничимся 7-ым спринтом. Если я выйду за его пределы, это уж в никакие рамки не влезет. Можно будет очень сильно ругаться)

**Comment by XeniaWorontsova** [comment]
> Точнее какой момент считается конечно точкой исследования?

Когда будет переделан документ по стекхолдерам

**Comment by KharlamovaAlexandra** [comment]
Ладно, ожидаю до конца спринта

**Comment by XeniaWorontsova** [comment]
Задача выполнена.
