### ISSUE TITLE
Разработать макет для стартовой страницы и страницы регистрации в мобильном приложении

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#15]
Epic #18 
GlobalStory #24 

Разработать макет формы регистрации благотворительной организации.
Макет должен предусмотреть возможность ввода данные перечисленных в задаче #21

Одобряет конечный вариант @KharlamovaAlexandra

**Comment by KharlamovaAlexandra** [comment]
https://docs.google.com/document/d/1j9kxQ0BHKyfl03hjhXEnlzoGFeNPj4PTshlRt5S41Bo/edit

**Comment by stasshtaub** [comment]
[Регистрации организации](https://drive.google.com/folderview?id=1-P7hO-n-u7ZA7tJ0q2zn4qgDiwbwowht)
[Стартовый экран](https://drive.google.com/folderview?id=1-3vE7bjQtAuERh7RJOb3TjzFy7kKz09m)

**Comment by YuriSilenok** [comment]
Я бы сказал что эту задачу невозможно правильно выполнить, так как неизвестно какие данные должны быть введенены при регистрации оргнаизации, которые должны быть пречислены в таблице задачи #21

**Comment by KharlamovaAlexandra** [comment]
Почему GlobalStory ведет на задачу связанную с веб-порталом?

**Comment by YuriSilenok** [comment]
> Почему GlobalStory ведет на задачу связанную с веб-порталом?

Это ошибка, эта задача должна быть исполнена в рамках GlobalStory  #24
Исправлю

**Comment by KharlamovaAlexandra** [comment]
Привет, @stasshtaub!
Дублирую вопрос.
Будет ли создан в рамках этой задачи экран с сообщением об успешной регистрации. В духе "Вы зарегистрированы, вам на почту выслано письмо"?
Спасибо

**Comment by stasshtaub** [comment]
[Ссылка на гугл-диске](https://drive.google.com/file/d/121KT_Fu2FRv4W68fIJOiZf_pTvodzAZ_/view)
![Подтверждение почты](https://user-images.githubusercontent.com/47520675/61627807-5d75a980-ac89-11e9-82a4-1090ab5a2d2c.jpg)

**Comment by KharlamovaAlexandra** [comment]
Одобрено, спасибо
