### ISSUE TITLE
Не работает кнопка "Новый пост" в веб-версии

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#154]
Epic #97 

1. Открываем профиль организации в WEB
2. Нажимаем на кнопку "Новый пост"

Ожидание: откроется окно создания поста, соответствующее макету.
Реальность: окно не открывается.

#168 
#98

**Comment by MoL4okkk** [comment]
Баг исправлен

**Comment by YuriSilenok** [comment]
> соответствующее макету

здесь должна была быть ссылка на макет
