### ISSUE TITLE
Инструкция для развертывания локального сервера

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#155]
Необходимо написать инструкцию для развертывания сервера приложений на компьютере под управлением unix подобных ОС.

!------------------------------------------------------------------!

1/3 -- техническая часть настройки окружения
Папка
https://drive.google.com/drive/folders/1CssE_P4RBV2YFDc-pXYEcP6qcGEzz0r8
Файл
https://docs.google.com/document/d/1l72a3VRuBhqV79KNh66z4Mx01ek7AnL6vLuesRD4uRQ/edit

!------------------------------------------------------------------!

2/3 -- развёртывание локального окружения и зависимостей к нему готова
Папка, файл -- те же.

!------------------------------------------------------------------!

**Comment by urec-programmec** [comment]
Техническая часть настройки окружения готова.

**Comment by urec-programmec** [comment]
Развёртка окружения для работы локального сервера готова (2/3)

**Comment by YuriSilenok** [comment]
Уже можно тестить задачу?

**Comment by urec-programmec** [comment]
Да, на функционал, представленный в описании

**Comment by MoL4okkk** [comment]
Задачи на тестирование созданы, закрывать эту задачу?

**Comment by MoL4okkk** [comment]
Таск на тестирование поднят
