### ISSUE TITLE
ООТ android

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#158]
Этапы работы:

1. Сравнение диаграммы классов Android и реализации этих классов 
2. Определение стратегии тестирования и тестируемой области
3. Написание классов эквивалентности для методов выбранных классов
4. Составление сценариев тестирования элементов с учётом классов эквивалентности
5. Проведение тестов по сценариям
6. Составление сценариев тестирования интеграции
7. Проведение тестов по сценариям
8. Составление сценариев тестирования правильности
9. Проведения тестов по сценариям

[Таблица с результатами сравнений, классами и сценариями](https://docs.google.com/spreadsheets/d/1ZsDGr790sF5plt7eP-ErbjunOLC8SOAxHfSMMAai69U/edit#gid=0)

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  В описании перечислить все этапы работ. 
В задачи на тестирование соответствия андроида диаграммам указать ссылку на данный эпик
Прикрепить ссылку на гугл -таблицу данной тематики

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  Прикрепить ссылки на результаты, закрыть

**Comment by MoL4okkk** [comment]
[Составленные сценарии тестирования](https://docs.google.com/spreadsheets/d/1ZsDGr790sF5plt7eP-ErbjunOLC8SOAxHfSMMAai69U/edit#gid=1990006707)

[Пояснительная записка](docs.google.com/document/d/1u0SMehyCF4foBx3bJ1bzTA6HeWbZqNnQ0kWdv-TbRUk/edit#heading=h.m09e3g41g4ql), содержащая код тестов и результат их запуска
