### ISSUE TITLE
Сбор сведений о существующих лицензиях для github

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#16]
Что то про возможности на гит наши и типы аккаунтов

**Comment by Parallusion** [comment]
[Ссылка на документ](https://docs.google.com/document/d/1L3cQNRCNBBhU57NO6wwlgFSdYQogMTW-EVOJ7-sXRwc/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
пожалуйста, поместите этот документ в общую папку на гугл диске.

**Comment by Parallusion** [comment]
> пожалуйста, поместите этот документ в общую папку на гугл диске.

Сделано.

**Comment by YuriSilenok** [comment]
Пожалуйста, конвертирует файл docx в формат гугл докумена

**Comment by Parallusion** [comment]
> Пожалуйста, конвертирует файл docx в формат гугл докумена

Сделано.

**Comment by YuriSilenok** [comment]
> [Ссылка на документ](https://docs.google.com/document/d/1L3cQNRCNBBhU57NO6wwlgFSdYQogMTW-EVOJ7-sXRwc/edit?usp=sharing)

Эта ссылка не ведет в обую гугл документ располагаемый в общей папке проекта. Пожалуйста, обновите ссылку.

**Comment by Parallusion** [comment]
> > [Ссылка на документ](https://docs.google.com/document/d/1L3cQNRCNBBhU57NO6wwlgFSdYQogMTW-EVOJ7-sXRwc/edit?usp=sharing)
> 
> Эта ссылка не ведет в обую гугл документ располагаемый в общей папке проекта. Пожалуйста, обновите ссылку.

[Новая ссылка на документ](https://docs.google.com/document/d/1sHSz184sL4WR7qU8pHSifiXunnI1XeUuUidXEZyizKA/edit?usp=sharing)

**Comment by KharlamovaAlexandra** [comment]
Одобрено

**Comment by YuriSilenok** [comment]
А какую лицензию в итоге нужно указать?

**Comment by KharlamovaAlexandra** [comment]
Суть задания была подготовить материал, чтобы все без труда смогли с ним ознакомится. Выбор лицензии, думаю, стоит вынести на групповое обсуждение. Этот вопрос о котором должны быть осведомлены все.

**Comment by YuriSilenok** [comment]
Александра, добавите карточку в бэклог?

**Comment by KharlamovaAlexandra** [comment]
Добавлю
