### ISSUE TITLE
Работа с описанием сущностей сервера

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#161]
Основные сущности, будущие на сервере описаны.

https://drive.google.com/drive/folders/18JOX9crY4tql8sDR8QqhZZwwZIUUcS6q

Интересует диаграмма "Структура сущностей"
Написана не в нотации UML, представляет собой скорее диаграмму плана

"Чем в данный момент для нас является объект, какие поля нам нужны
(важны, необходимы для описания объекта на данном этапе), а какие нет"

Как пример -- на верхнем уровне Пользователя нас интересует только то, 
что у него есть глобальная сущность Профиль, потому что у каждого Пользователя должен быть профиль.
Но зато после, когда мы говорим о данном Пользователе, а конкретно о его Профиле, мы понимаем, что у каждого Пользователя должно быть имя (название).

В дополнение есть файл с минимальным описанием предлагаемых уровней абстракции "Структура сущностей пояснение"

 Задание: 
(ВАЖНО) Понять принципы построения как диаграммы, так и документации. Пожалуйста.
Протестировать в соответствии с этим разработанную документацию по основным сущностям.
Выбрать места, недописанные до нужного уровня. 
При необходимости выбрать неинтуитивно понятные дополнительные глобальные сущности, требующие такого же описания.

**Comment by KharlamovaAlexandra** [comment]
@Parallusion создать задачу на тестирование этой документации, наследовать этого эпика

**Comment by MoL4okkk** [comment]
Таск на тестирование поднят
