### ISSUE TITLE
Создать описание сущностей сервера

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#162]
Epic #161 

https://drive.google.com/drive/folders/18JOX9crY4tql8sDR8QqhZZwwZIUUcS6q
Вообще задача не релевантна, есть другая, более точно описывающая проблему.

**Comment by KharlamovaAlexandra** [comment]
Прикрепить в описание ссылку на папку с сущностями
Перечислить в описании необходимые сущности

**Comment by KharlamovaAlexandra** [comment]
@urec-programmec Ссылку на папку прикрепи в описание, пожалуйста

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  вы это брали на тестирование уже в каком либо виде? Вроде Илья должен был

**Comment by MoL4okkk** [comment]
В процессе тестирования
