### ISSUE TITLE
Story-*. Лента новостей организации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#163]
Epic #157
Разработать спецификацию для ленты постов
Описать функционал ленты и указать различия под web и android

https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit

**Comment by KharlamovaAlexandra** [comment]
@Parallusion  на тестирование. Задачу закрыть после поднятия задачи на тестирование

**Comment by MoL4okkk** [comment]
Задача на тестирование поднята
