### ISSUE TITLE
Реализовать БД

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#164]
1) Реализовать все таблицы
2) Реализовать связи между таблицами
3) Реализовать хранимые процедуры
4) Реализовать триггеры

**Comment by KharlamovaAlexandra** [comment]
Не все задачи отмечены как дочерние, такие как исследование предметной области и ерд тоже тут должны быть

**Comment by XeniaWorontsova** [comment]
> Не все задачи отмечены как дочерние, такие как исследование предметной области и ерд тоже тут должны быть

Исследование предметной области и ERD не относятся к непосредственной реализации

**Comment by XeniaWorontsova** [comment]
Закрыта, так как в дальнейшем будут создаваться задачи на каждый спринт
