### ISSUE TITLE
Протестировать диаграмму классов сервера

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#166]
Epic #159 
Story #169 

Провести тестирование [диаграммы классов сервера](https://www.draw.io/#G1M9Om8nAgxtA8lVABB9oUTAwXKFt4pJhn), составленной в ходе выполнения задачи #102, на соответствие документации

**Comment by KharlamovaAlexandra** [comment]
Где помечена задача с реализацией этой диаграммы, которую должен был закрыть?

**Comment by MoL4okkk** [comment]
Как отмечать эту задачу? Как стори?

**Comment by KharlamovaAlexandra** [comment]
Нет, обычная задача, наследуй от 159

**Comment by MoL4okkk** [comment]
Отметил

**Comment by MoL4okkk** [comment]
Тестирование завершено, несоответствий не выявлено

**Comment by KharlamovaAlexandra** [comment]
Неужели она настолько идеальна?

**Comment by YuriSilenok** [comment]
Вы проводили тестирование на предмет соответсвие нотации UML. Диаграммы классов?
![Screenshot from 2019-11-26 17-31-04](https://user-images.githubusercontent.com/14871471/69642262-8ad8c680-1072-11ea-8c8e-da6bdb85fe45.png)
