### ISSUE TITLE
Анализ прав организаций КГУ и ТЕЛЕ 2 на проект

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#17]
Тут про права кгу и теле2 на проект

**Comment by KharlamovaAlexandra** [comment]
Задача еще активна?

**Comment by Parallusion** [comment]
Анализ данного вопроса невозможно выполнить, в связи с отсутствием какой либо информации в свободном доступе, нужны нормативные документы от каждой организации по проектам, но их на сайтах организаций или на других сайтах  нет в наличии.

**Comment by YuriSilenok** [comment]
Разбить задачу на 2.

1. Теле2 должны были предоставить вам куратором, контакты с ними остались, возможно стоит к ним обратиться
2. КГУ
2.1. в главном корпусе есть юридический отдел, нужно обратиться  к ним
2.2. на кафедре Юриспруденции (или как-то так) существует студенческий юридический отдел, где студни получают опыт решая подобные насущные вопросы.

**Comment by KharlamovaAlexandra** [comment]
Куратора по теле2 не существует

**Comment by YuriSilenok** [comment]
То есть не было предварительной проверки проекта перед выступлением?
А вообще tele2 имеет отношение к этому проекту?
Вы что-нибудь подписывали, если да, то пришлите и мне посмотреть этот док.

**Comment by KharlamovaAlexandra** [comment]
Мы лично ничего не подписывали, но материалы работы сдавали ( правда их так никто и не посмотрел до начала защит ) 
За нас могло что - то подписать КГУ 
Да и что то же мы выиграли...
Когда будут заниматься этим вопросом непосредственно, я свяжусь с представителем теле2 и уточню у него

**Comment by KharlamovaAlexandra** [comment]
Закрыто за неактуальностью
