### ISSUE TITLE
Протестировать макет публикации нового поста для WEB

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#171]
Epic #97 
Story #98 

Протестировать макеты постов в WEB, созданные в ходе выполнения задачи #116, на соответствие требованиям.
Поднимать баги по мере нахождения.

**Comment by KharlamovaAlexandra** [comment]
Выполнено https://docs.google.com/spreadsheets/d/1pn0eiGvR_M5N5YzgW9QFcqIv-y_k0FgnkdhFRbGf8Kw
