### ISSUE TITLE
Протестировать макет публикации постов для Android

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#172]
Epic #97 
Story #98 

Протестировать макеты постов в Android, созданные в ходе выполнения задачи #103, на соответствие требованиям.
Поднимать баги по мере нахождения.

**Comment by KharlamovaAlexandra** [comment]
Выполнено в ходе #196 https://docs.google.com/spreadsheets/d/1yrjrGhbb35uZz7R_UGhSE1dPPKFIPkOcF0diUFn80_k
