### ISSUE TITLE
Отсутствует выбор даты завершения мероприятия на макете публикации постов вида "Мероприятие" для Android

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#173]
Макет не соответствует требованиям описанным в [спецификации](https://docs.google.com/document/d/1p0aFXnl3jeQWKu_cQHuSFoc59WKs-PMpChTdkxWICBA/edit), так как отсутствует кнопка (поле) "Дата завершения мероприятия".

Шаги для воспроизведения бага:
1. Открыть по ссылке [таск](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/103)
2. Открыть макет "Новое мероприятие"

Ожидаемый результат:
Макет соответствует [спецификации.](https://docs.google.com/document/d/1p0aFXnl3jeQWKu_cQHuSFoc59WKs-PMpChTdkxWICBA/edit)

Фактический результат:
Макет не соответствует [спецификации.](https://docs.google.com/document/d/1p0aFXnl3jeQWKu_cQHuSFoc59WKs-PMpChTdkxWICBA/edit)

**Comment by stasshtaub** [comment]
В спецификации не написано, что нужна отдельная кнопка для даты завершения. 
И по идее в спецификации (если по ней делаются макеты) надо только перечислять функционал который должен быть на макете, а не то с какой стороны какая кнопка

**Comment by Parallusion** [comment]
> В спецификации не написано, что нужна отдельная кнопка для даты завершения.
> И по идее в спецификации (если по ней делаются макеты) надо только перечислять функционал который должен быть на макете, а не то с какой стороны какая кнопка

В спецификации указано следующее:
 "Мероприятие
	Имеет фото (можно видео), описание, дату проведения, **дату завершения,** ..."
Таким образом, следует что в макете должна быть дата завершения, но на макете её ни в каком виде нет.

**Comment by stasshtaub** [comment]
> но на макете её ни в каком виде нет.
![IMG_20191124_195008](https://user-images.githubusercontent.com/47520675/69497962-95208680-0ef3-11ea-8b07-9ce463110ddb.jpg)
