### ISSUE TITLE
Презентация "Всем кто тут впервые" не соответствует критериям

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#174]
**Версия google презентации:** v.0 - Грустные котики

Презентация ["Всем кто тут впервые"](https://docs.google.com/presentation/d/1S9-4Yeu17u0SQHVxD-aZLLbwYbyhogthzkJt4SCYXe4/edit#slide=id.g6180f6e33f_0_15) не соответствует следующим критериям:

Критерий  | Результат | Комментарий 
-- | -- | --
Полнота описания | - | Неполное описание на актуальное состояние проекта (информация полная на момент начала работы проекта, в данный момент проект разросся и информация покрывает не всё)
Актуальность | - | Если новый член команды или любой пользователь ознакомится с документом, большое количество информации, которое нужно для ориентации пользователя по гугл диску будет отсутствовать, в связи с неактуальностью презентации |
Логика и согласованность | + | 
Непротиворечивость | + |
Структурированность, адаптированность | - | Информация не структурирована по слайдам, если у пользователя возникнет вопрос будет трудно ориентироваться по документу
Ясность и однозначность | + |
Осуществимость | + |

Ожидаемый результат:
1. В презентации отражена актуальная информация о текущем состоянии структуры нашего проекта на гугл диске,
2. Удалена устаревшая информация.
3. Информация структурирована по слайдам
4. Добавлены заголовки для каждого слайда, отражающие информацию на слайдах, легенду (описано что происходит на слайде)
5. Удалены картинки, или написано на слайде, что они отражают.

**Comment by KharlamovaAlexandra** [comment]
Презентация перенесена в устаревшую документацию
