### ISSUE TITLE
Протестировать документ "CASH" на соответствие критериям

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#176]
**Версия google-документа:** v.0 неструктурированый кеш

Документ ["CASH"](https://docs.google.com/document/d/1yP7GuqnMuICfJoVZXR6nuXpkKnQ2muuofV-aDt4uzsQ/edit) не соответствует следующему критерию:

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | + |  
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | - | Документ не структурирован, нет никакой навигации по нему, необходимо задать структуру документа (выделить темы, пункты и заголовки для них).       Поменять название документа на вариант доработки системы, либо придумать новое, чтобы было понятнее о чём пойдёт речь, ведь не все понимают, что такое CASH, когда видят документ с таким названием
Ясность и однозначность | + |  
Осуществимость | + |  

Ожидаемый результат:
1. Документ структурирован, добавлены заголовки, которые соответствуют выделенным темам, пунктам в документе
2. Название сменено на более понятное рядовому пользователю

Комментарий тестировщика: @KharlamovaAlexandra @urec-programmec является ли этот документ актуальным на данный момент? 

!------------------------------------------------------------------!

Изменения приняты и доработаны.
Файл перемещён в необходимую папку. 
https://docs.google.com/document/d/1yP7GuqnMuICfJoVZXR6nuXpkKnQ2muuofV-aDt4uzsQ/edit

(с)    "Комментарий тестировщика: @KharlamovaAlexandra @urec-programmec является ли этот документ актуальным на данный момент?"

Да, документ остаётся актуальным на данный момент для будущих задач

!------------------------------------------------------------------!

**Comment by MoL4okkk** [comment]
Ай

**Comment by cyberAndrey** [comment]
Повторное тестирование выполнено в рамках #187 таска. Баги исправлены, повторных багов нет
