### ISSUE TITLE
Диаграмма "Функциональная схема" не соответствует критериям

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#177]
**Версия диаграммы draw.io:** Сергей Простокишин 07.10.2019 14:24:02

Диаграмма ["Функциональная схема"](https://www.draw.io/#G1tT2DKYbO14Pa5-obYEzvXQkKCxVw5vqd) не соответствует следующим критериям:

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | - | 1. Требует пересмотра (С) Саша
Актуальность | - | 1. Требует пересмотра (С) Саша
Логика и согласованность | + | 2. Отсутствует легенда, соответственно не понятно по какому принципу происходит деление по цветам, и в принципе легенда нужна
Непротиворечивость | + |  
Структурированность, адаптированность | - | 3. Файл не структурирован, сложно ориентироваться (идея: выделить контейнеры или области под конкретные группы объектов и подписать их)
Ясность и однозначность | + |  
Осуществимость | + |  

Ожидаемый результат:
1. Диаграмма пересмотрена и приведена в актуальное состояние по результатам пересмотра
2. Диаграмма пересмотрена и описаны все функции (возможности) организации и гражданина (на данный момент описано не всё)
3. Добавлена полноценная легенда к диаграмме, со всей информацией, необходимой для понимания диаграммы
4. Диаграмма структурирована, то есть пользователю предоставлена возможность легко ориентироваться по диаграмме 

Комментарий тестировщика: Моё предложение к 4 пункту: выделить контейнеры или области под конкретные группы объектов и подписать их, или же выделить цветами как нибудь конкретные группы однотипных объектов, но это лишь предложение, можно сделать так, как будет правильно по вашему мнению)

**Comment by MoL4okkk** [comment]
Баг исправлен
