### ISSUE TITLE
Регистрация на информационной площадке "Луч надежды"

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#18]
Я должен иметь возможность зарегистрироваться на портале через:
- вэб-приложение как организация #20 
- мобильное приложение на android как организация #24 
- вэб-приложение как гражданин #64
- мобильное приложение на android как гражданин #63

**Comment by YuriSilenok** [comment]
Привет Саша,

Начинаю декомпозицию задач пэ этому эпику.

Спасибо.

**Comment by KharlamovaAlexandra** [comment]
Привет Юрий ,
С декомпозицией ознакомлюсь. 
Мне кажется у этого эпика должен быть PR4
Спасибо

**Comment by YuriSilenok** [comment]
> Мне кажется у этого эпика должен быть PR4

как скажешь,я пока еще не понял что для проекта какой приоритет значит.
