### ISSUE TITLE
Диаграмма "IDEF0 (Как есть на самом деле)" не соответствует критериям

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#180]
**Версия диаграммы draw.io:** Дарья Жезлова 25.04.2019 19:56:00

Диаграмма ["IDEF0 (Как есть на самом деле)"](https://drive.google.com/file/d/1MRbYl0eT89PSGYIDAlaIBRaevNbXoKT0/view) не соответствует следующим критериям:

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | - | Необходимо сделать диаграмму подробнее для описания всей системы
Актуальность | - | Необходимо отразить актуальное состояние на диаграмме(как минимум актуальное состояние видения продукт овнера)
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | - | Необходимо диаграмму сделать более адаптированной к просмотру пользователем, необходимо добавить легенду
Ясность и однозначность | - | Необходимо сделать какие то пояснения, комментарии к диаграмме, для того, чтобы было понятнее
Осуществимость | + |  

Ожидаемый результат:
1. Диаграмма доработана, содержит более полное описание системы
2. На диаграмме отражено актуальное состояние проекта (если по мнению @KharlamovaAlexandra диаграмма в текущем виде отражает актуальное состояние, отпиши пожалуйста в комментарии в этот таск) 
3. Диаграмма адаптирована к просмотру (облегчение ориентации пользователя по диаграмме)
4. Добавлена легенда
5. Добавлены пояснения, комментарии к диаграмме (облегчение понимания пользователем диаграммы, можно добавить в легенду)

**Comment by KharlamovaAlexandra** [comment]
@ Наверно это теперь от части и твоя проблема. Возможно мы отказываемся от IDEF0 и переходим к другим нотациям ( дублирую #178 )

**Comment by XeniaWorontsova** [comment]
@KharlamovaAlexandra, я сделаю описание бизнес процесса "как есть" в нотации BPMN 2.0

**Comment by KharlamovaAlexandra** [comment]
Закрывается в ходе полного изменения диаграммы
