### ISSUE TITLE
[CR-01][Story-01] - Изменить алгоритм работы подсказок у полей на странице регистрации организации

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#181]
Story-01. [Регистрация](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit) 
#179 
Всплывающая подсказка у поля "Название"

Название стори | Регистрация благотворительной организации
-- | --
Как кто? | Как организация
Я хочу | Чтобы мне отображались требования по вводу названия организации
Чтобы | Чтобы я понимал, что требуется ввести именно название **благотворительной организации** 

**Изменение в алгоритме работы подсказки по вводу названия организации:**
Информация о том, что должно быть в поле "Название" должна быть  справа от поля "Название" в виде всплывающего окна красного цвета с текстом белого цвета

Как было | Как должно быть
-- | --
При вводе названия ничего не происходит | При вводе названия справа появляется сообщение о том, что в это поле необходимо записать название благотворительной организации 

Критерии приемлемости
Use Case 1
Когда пользователь начинает вводить Название 
Тогда система отображает всплывающее сообщение с информацией о том, что в это поле необходимо записать название благотворительной организации

Всплывающая подсказка у поля "ИНН"

Название стори | Регистрация благотворительной организации
-- | --
Как кто? | Как организация
Я хочу | Чтобы мне отображались требования по вводу ИНН
Чтобы | Чтобы я не мог ввести некорректное ИНН

**Изменение в алгоритме работы подсказки по вводу ИНН:**
Информация о том, что должно быть в поле "ИНН", а также ограничения на длину, должны быть  справа от поля "ИНН" в виде всплывающих окон красного цвета с текстом белого цвета

Как было | Как должно быть
-- | --
При вводе ИНН ничего не происходит | При вводе ИНН справа появляется сообщение о том, что в это поле необходимо записать номер ИНН благотворительной организации и что его длина 10-12 символов, среди которых цифры от 0 до 9

Критерии приемлемости
Use Case 2
Когда пользователь начинает вводить ИНН 
Тогда система отображает всплывающее сообщение с информацией о том, что в это поле необходимо записать ИНН благотворительной организации, а также чуть ниже в этом же всплывающем сообщении ограничения на ввод ИНН

Всплывающая подсказка у поля "E-mail"

Название стори | Регистрация благотворительной организации
-- | --
Как кто? | Как организация
Я хочу | Чтобы мне отображались требования по вводу E-mail
Чтобы | Чтобы я не мог ввести некорректный E-mail

**Изменение в алгоритме работы подсказки по вводу E-mail:**
Информация о том, что должно быть в поле "E-mail", а также требования должны быть  справа от поля "E-mail" в виде всплывающих окон красного цвета с текстом белого цвета

Как было | Как должно быть
-- | --
При вводе E-mail ничего не происходит | При вводе E-mail справа появляется сообщение с примером e-mail (к примеру user12345678@yandex.ru)

Критерии приемлемости
Use Case 3
Когда пользователь начинает вводить E-mail 
Тогда система отображает всплывающее сообщение с примером e-mail

Всплывающая подсказка у поля "Пароль"

Название стори | Регистрация благотворительной организации
-- | --
Как кто? | Как организация
Я хочу | Чтобы мне отображались требования по вводу Пароля
Чтобы | Чтобы я не мог ввести некорректный Пароль

**Изменение в алгоритме работы подсказки по вводу Пароля:**
Информация о том, что должно быть в поле "Пароль", а также ограничения на длину, должны быть  справа от поля "Пароль" в виде всплывающих окон красного цвета с текстом белого цвета

Как было | Как должно быть
-- | --
При вводе пароля не происходит ничего | При вводе пароля справа появляется сообщение о том, что в этом поле необходимо придумать и ввести пароль к аккаунту на нашей площадке, а также о минимальных ограничениях на пароль (длина пароля)

Критерии приемлемости
Use Case 4
Когда пользователь начинает вводить Пароль 
Тогда система отображает всплывающее сообщение о том, что в этом поле необходимо придумать и ввести пароль к аккаунту на нашей площадке, а также ниже в этом же сообщении о минимальных ограничениях на пароль (длина пароля)

Всплывающая подсказка у поля "Повторите пароль"

Название стори | Регистрация благотворительной организации
-- | --
Как кто? | Как организация
Я хочу | Чтобы мне отображались требования по повторному вводу Пароля, а также если введённый пароль соответствует паролю в поле "Пароль" выводилось сообщение о том, что пароли совпадают 
Чтобы | Чтобы я не мог ввести пароль отличающийся от находящегося в поле "Пароль"

**Изменение в алгоритме работы подсказки по повторному вводу пароля**
Информация о том, что должно быть в поле "Повторите пароль"  и сообщение о несовпадении паролей должны быть  справа от поля "Повторите Пароль" в виде всплывающего окна красного цвета с текстом белого цвета,  а также информация о совпадении паролей в виде всплывающего окна зелёного цвета с текстом белого цвета "Пароли совпадают" 

Как было | Как должно быть
-- | --
При повторном вводе пароля не происходит ничего | При повторном вводе пароля справа появляется сообщение о том, что в этом поле необходимо записать придуманный ранее пароль, который был введен в поле "Пароль", а затем, если пароли не совпадают появляется ниже сообщение о том, что пароли не совпали, а если пароли совпадают, сообщение о том, что пароли совпали

Критерии приемлемости
Use Case 4
Когда пользователь начинает вводить текст в поле "Повторить пароль" 
Тогда система отображает всплывающее сообщение  о том, что в этом поле необходимо записать придуманный ранее пароль, который был введен в поле "Пароль"

Use Case 5
Когда пользователь вводит текст в поле "Повторить пароль" 
Тогда система отображает всплывающее сообщение сообщение о том, соответствует ли введённый пароль в поле "Повторить пароль" паролю в поле "Пароль" ("Пароли совпадают", "Пароли не совпадают")

**Comment by KharlamovaAlexandra** [comment]
1, 2, 4 применено

**Comment by MoL4okkk** [comment]
Спецификация протестирована повторно, соответствующие на тестирование подняты.
