### ISSUE TITLE
Протестировать инструкцию для развёртывания локального сервера

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#184]
Протестировать инструкцию по развёртыванию сервера приложений на компьютере под управлением Unix-подобных ОС. Результаты тестирования занести в [таблицу](https://docs.google.com/spreadsheets/d/1Oxgr3TUBpd5LAV2s84yoQI2RHR_PGDDiVEn1Trh4DJE/edit#gid=0). Поднимать баги по мере нахождения.

Story #155

**Comment by KharlamovaAlexandra** [comment]
Выполнено
