### ISSUE TITLE
Нет сброса данных при смене типа создаваемого поста

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#185]
Epic #97 

Шаги воспроизведения бага:
1. Открыть профиль организации в WEB;
2. Открыть окно создания нового поста;
3. Заполнить поле "Количество";
4. Сменить тип поста на любой другой;
5. Выбрать тип поста "Нужда".

Ожидаемый результат: поле "Количество" будет пустым.
Фактический результат: данные в поле не сброшены.

#98

**Comment by Parallusion** [comment]
Данный баг поднят неверно, так как данный функционал соответствует виденью PO и не является ошибочным.

**Comment by MoL4okkk** [comment]
@Parallusion , в [описании функционала](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/97) сказано следующее:
![image](https://user-images.githubusercontent.com/55210615/70164569-75971400-16d2-11ea-821d-277854526759.png)

**Comment by MoL4okkk** [comment]
Невозможно проверить исправление бага из-за отсутствия сервера

**Comment by stasshtaub** [comment]
> Невозможно проверить исправление бага из-за отсутствия сервера

Данные сбрасываются на стороне клиента, не сервера. Проверяй через код с гита (ветка web) с локального сервера

**Comment by MoL4okkk** [comment]
Баг исправлен
