### ISSUE TITLE
Протестировать описание сущностей сервера

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#187]
Epic #161 

Протестировать документацию, разработанную в ходе выполнения задачи #162, на соответствие критериям документации. Результаты тестирования занести в [таблицу](https://docs.google.com/spreadsheets/d/1Oxgr3TUBpd5LAV2s84yoQI2RHR_PGDDiVEn1Trh4DJE/edit#gid=0). Поднимать баги по мере нахождения.

**Comment by cyberAndrey** [comment]
Тестирование завершено
