### ISSUE TITLE
Регистрация благотворительной организации через вэб-портал

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#19]
Epic #18 

Я как представитель благотворительной организации, должен иметь возможность со стартовой страницы #25 попасть на страницу регистрации организации #23, на которой я заполняю форму регистрации #20. После нажатия на кнопу **Зарегистрироваться** в соответствии с механизмом регистрации #28, на указанную мной электронную почту мне приходит письмо #26 с ссылкой подтверждения почты #27

**Comment by YuriSilenok** [comment]
Привет @stasshtaub ,

посмотри пожалуйста на описание этой стори.
есть ли у нас макеты страниц вэб-портала для описанной ситуации?

Спасибо.

**Comment by stasshtaub** [comment]
Нет. Я хотел начать делать макеты сайта, как закончу со всеми экранами для приложения. Если срочно, могу завтра набросать, но очень примерно

**Comment by KharlamovaAlexandra** [comment]
Юрий, у нас еще не было задач по созданию макетов для веба

**Comment by YuriSilenok** [comment]
ок, я тогда пока эти задачи подготовлю, но нужно понимать, что эта задача будет не для создания всего сразу макета, а только нескольких страниц. как бы скрам и агил.

**Comment by YuriSilenok** [comment]
> Нет. Я хотел начать делать макеты сайта, как закончу со всеми экранами для приложения. Если срочно, могу завтра набросать, но очень примерно

стори стоит на первый спринт, пока это только в виде вопроса все.

**Comment by YuriSilenok** [comment]
Закрыто как рудимент
