### ISSUE TITLE
Инструкция "Переход на локальную разработку" не соответствует критерия

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#190]
Баг поднят в рамках выполнения задачи #184 
**Версия google-документа:** v.0

Документ [Переход на локальную разработку](https://docs.google.com/document/d/1l72a3VRuBhqV79KNh66z4Mx01ek7AnL6vLuesRD4uRQ/edit) не соответствует следующим критериям:

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | - |  Нет на данный момент блока даных от хостинга, нет решения вопроса с единым репозиторием
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + | Структурированнность и адаптированность имеет условный плюс, т.к. раздел с базой данных не вписывается в структуру докумнета и находится в ненадлежащем месте. Должно быть частью раздела "Что для этого нужно сделать"
Ясность и однозначность | + |  Раздел "Почему это надо менять?", пункт 4 вызывает сложность для понимания
Осуществимость | + |  

Ожидаемый результат:
1.  Поставить раздел "База данных" на свое место в структуре документа
2. Переформулирование пункта 4 в разделе "Почему это надо менять?"
3. Дополнить инструкцию данными о хостинге 
4. Решить вопрос с единым репозиторием

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk Закрыть по неактуальности. Отразить состояние документа на данный момент

**Comment by MoL4okkk** [comment]
Фактический результат не соответствует ожидаемому; изменений, влияющих на соответствие документа указанным критериям, не было. Закрыто за неактуальностью.
