### ISSUE TITLE
Составить сценарии тестирования ленты постов в WEB

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#191]
Epic #157 

Написать сценарии тестирования согласно [стори](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit) и занести их в [таблицу](https://docs.google.com/spreadsheets/d/1QX80ipwa-VqxpP4v4vkhY62S_wfBev07Xq2Ys48WiyM/edit#gid=30265015)

Story #170

**Comment by Svyat935** [comment]
Задача выполнена.
