### ISSUE TITLE
Составить сценарии тестирования ленты постов в Android

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#192]
Epic #157

Написать сценарии тестирования согласно [стори](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit) и занести их в [таблицу](https://docs.google.com/spreadsheets/d/16dMIPuW4tlPUntkUoM8C1TRME36dK9TPxPu8maahwFE/edit#gid=1938750302)

Story #170

**Comment by Svyat935** [comment]
Задача выполнена
