### ISSUE TITLE
Обеспечить тестирование эпика Лента постов

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#193]
Epic #157 

Поднять задачу на тестирование опецификации
Поднять задачи на написание сценариев
Поднять задачи на тестирование макетов
Поднять задачи на тестирование документации
Поднимать баги по мере нахождения

**Comment by MoL4okkk** [comment]
Подобная задача была создана ранее: #170
