### ISSUE TITLE
Сделать макет ленты новостей для Web

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#194]
Epic #157 
Story #163

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/drive/u/1/folders/18gf0tu_WbJKgbZ6RfPyCxiHuswhBEJJA)

**Лента полностью:**
![Лента](https://user-images.githubusercontent.com/47520675/70072967-15886b00-1609-11ea-8d0f-0f4d82f491e5.jpg)

**Кнопка "вверх" при скролле**
![Кнопка вверх при скролле](https://user-images.githubusercontent.com/47520675/70072965-15886b00-1609-11ea-87cd-2d77ea7a56c1.jpg)

**Comment by MoL4okkk** [comment]
Задача на тестирование поднята
