### ISSUE TITLE
Сделать макет ленты новостей для Android

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#195]
Epic #157
Story #163

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/drive/u/1/folders/1BNWiWm3xFNxHsfs3wU4-c5DAo5sEdRez)
[Видео-демка](https://drive.google.com/open?id=1-KTRGpg4I_5FcLuPWHMP5PInRAI0GS9T)

**Лента:**
![Лента](https://user-images.githubusercontent.com/47520675/70072696-8c713400-1608-11ea-918a-5fecc044c6cc.jpg)

**Скролл длинного поста:**
![Лента скролл длинного поста](https://user-images.githubusercontent.com/47520675/70072694-8c713400-1608-11ea-93d1-1c4a017c6b44.jpg)

**Скролл ленты до конца:**
![Лента скролл](https://user-images.githubusercontent.com/47520675/70072695-8c713400-1608-11ea-92d7-755d3db9dd75.jpg)

**Фильтры:**
![Фильтры город](https://user-images.githubusercontent.com/47520675/70072692-8bd89d80-1608-11ea-902e-1f49e39c693b.jpg)
![Фильтры выбор деятельности](https://user-images.githubusercontent.com/47520675/70072697-8d09ca80-1608-11ea-91bd-e5d2c54635cd.jpg)
![Фильтры выбор типа записи](https://user-images.githubusercontent.com/47520675/70072699-8d09ca80-1608-11ea-8c1f-860702f1982b.jpg)

**Comment by MoL4okkk** [comment]
Задача на тестирование поднята
