### ISSUE TITLE
Тестирование макетов на Android

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#196]
Протестировать использующиеся макеты приложения на Android на соответствие спецификации (если есть). Результаты тестирования внести в [таблицу](https://docs.google.com/spreadsheets/d/1yrjrGhbb35uZz7R_UGhSE1dPPKFIPkOcF0diUFn80_k/edit#gid=0), указав в качестве стори документ с описанием макета. Поставить сложность задаче. Поднимать баги по мере нахождения.

[Макеты](https://drive.google.com/drive/folders/1COX7nIbw2omRuBOOK5ExATyuc0nFAl18)

**Comment by KharlamovaAlexandra** [comment]
Задача выполнена
