### ISSUE TITLE
Тестирование макетов в WEB

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#197]
Протестировать использующиеся макеты приложения на Android на соответствие спецификации (если есть), а также реализацию этих макетов. Результаты тестирования внести в [таблицу](https://docs.google.com/spreadsheets/d/1pn0eiGvR_M5N5YzgW9QFcqIv-y_k0FgnkdhFRbGf8Kw/edit#gid=0), указав в качестве стори документ с описанием макета. Поставить сложность задаче. Поднимать баги по мере нахождения.

[Макеты](https://drive.google.com/drive/folders/1XNjssCx8GHdAbrux9qVbUahyYJYgfuwg)

**Comment by KharlamovaAlexandra** [comment]
Выполнено
