### ISSUE TITLE
Провести анализ целевой аудитории информационной площадки "Луч надежды"

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#2]
Story #33 
Предоставить информацию о потенциальных  пользователях системы ( Россия ). Уделить внимание органам власти, организациям и бизнесу. Предоставить примеры заинтересованных лиц. Уточнить виды организаций ( деятельность которых официально разрешена на территории РФ ). Привести конкретные примеры организаций КО ( не менее 5 штук)  с описанием того, какими возможностями по работе с аудиторией они имеют сейчас.

**Comment by KharlamovaAlexandra** [comment]
@YuriSilenok уточните пожалуйста теги для аналитической работы

**Comment by YuriSilenok** [comment]
Могу предложить [Analysis](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/labels/Analysis)

**Comment by KharlamovaAlexandra** [comment]
Активность?

**Comment by Parallusion** [comment]
Задача в процессе.

**Comment by YuriSilenok** [comment]
Если она в процессе, тогда почему она на доске еще в бэклоге валяется?

**Comment by KharlamovaAlexandra** [comment]
Каково состояние задачи?

**Comment by YuriSilenok** [comment]
> Каково состояние задачи?

UP
