### ISSUE TITLE
Регистрация благотворительной организации через вэб-портал

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#20]
Epic #18 

Я как представитель благотворительной организации, должен иметь возможность со стартовой страницы #25 попасть на страницу регистрации организации #23, на которой я заполняю форму регистрации #20. После нажатия на кнопу Зарегистрироваться в соответствии с механизмом регистрации #28, на указанную мной электронную почту мне приходит письмо #26 с ссылкой подтверждения почты #27

![Без ошибок](https://user-images.githubusercontent.com/47520675/61364254-24ef5d80-a88e-11e9-951b-180b291e1733.jpg)

**Comment by YuriSilenok** [comment]
Стас, когда будет макет для формы регистрации организации, вставь его в описание.
Илья, будет задача по определению необходимого пакета информации об благотворительной организации при регистрации у нас на портале.

**Comment by YuriSilenok** [comment]
Привет @stasshtaub 

в каком состоянии находиться эта задача?

Спасибо.

**Comment by stasshtaub** [comment]
Готова

**Comment by YuriSilenok** [comment]
Задача не должна висеть на человеке который по не все сделал, если она нуждается в проверке, то перевешивается на того, кто должен проверить, с сответствующим комментарием, если по задаче не осталось никаких работ, в том числе и проверочных, то задача должна быть закрыта. Закрытая задача как правило имеет исполнителя того, кто закрывал задачу.

**Comment by KharlamovaAlexandra** [comment]
Открывая главную страницу сайта я хочу в меню увидеть кнопку зарегистрироваться. 
Нажимая на нее я хочу увидеть тип аккаунта организация/гражданин и выбрать организация. После того я хочу попасть на страницу регистрации организации.
На этом экране я хочу увидеть кнопку “О нас”, “Вход”, поле ввода “Название организации”, поле ввода “инн”, поле ввода “электронная почта”, “пароль”, “подтвердите пароль”, кнопку “зарегистрироваться”.
Возле каждого поля я хочу увидеть подсказку с тем, как надо заполнить это поле в соответствии с ограничениями
Я хочу заполнить поля и нажав кнопку зарегистрироваться, увидеть сообщение, что ссылка подтверждения почты и регистрации отправлена на почту. После этого сообщения я хочу чтобы меня перенаправило на личный кабинет моего профиля.
( Сразу же, а не после того как я подтвержу ссылку).
В случае если я неверно заполнил поля я хочу увидеть сообщения об ошибках.
При заполнении паролей, они должны вводится скрыто, но должна быть кнопочка посмотреть пароль

[подробнее](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)

**Comment by KharlamovaAlexandra** [comment]
Перечитать описание, переоткрыть старые задачи на макеты, переделать, составить сценарии

**Comment by KharlamovaAlexandra** [comment]
@stasshtaub Я жду переделанного макета в соответствии с описанием story на этот спринт (выше описание под которое надо переделать) (конкретно не хватает повторите пароль)

**Comment by KharlamovaAlexandra** [comment]
Верстку сайта тоже потом в соответствии с переделанным макетом

**Comment by stasshtaub** [comment]
[Макет на гугл-диске](https://drive.google.com/open?id=1kusWjHT691CDYcLUhRPxSVMB4ZjJXz5A)

[Верстка](https://rayofhope-opensource.000webhostapp.com/registration/org)

![Без ошибок](https://user-images.githubusercontent.com/47520675/64976785-d4f73c00-d8ba-11e9-9267-a8470b6b75e1.jpg)
