### ISSUE TITLE
Story-* "Лента новостей организации" не соответствует критериям

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#200]
Epic #157 Story #186  #170   
**Версия google-документа:** v.0.1

Результат тестирования документа [0*. Лента постов](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit) на соответствие критериям:

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | + |  
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + | 
Ясность и однозначность | + |  
Осуществимость | + |  

Баг: #206

**Comment by Parallusion** [comment]
@MoL4okkk, были внесены следующие изменения:
1. Добавлена информация про скрытый текст.
2. Добавлена информация про отображение автора записи.
3. Добавлена информация о переходе наверх.
4. Добавлена информация об открытии поста в отдельном окне

[Ознакомиться.](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit)

**Comment by MoL4okkk** [comment]
@Parallusion, повторное тестирование завершено, несоответствия критериям не выявлено. Обнаружен баг: #206

**Comment by MoL4okkk** [comment]
Повторное тестирование завершено, выявленные баги исправлены, документация соответствует критериям
