### ISSUE TITLE
Нет описания различий ленты постов на Android и в WEB

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#201]
Epic #157 Story #170 #186 

В задаче #163 сказано, что разработанная [спецификация](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit) должна содержать описание различий ленты постов в WEB- и Android-версиях.

Фактический результат: спецификация содержит только общее описание ленты.

**Comment by Parallusion** [comment]
@MoL4okkk, были внесены следующие изменения:

Добавлена информация по тому, какой платформе присуще определённое описание функционала.

[Ознакомиться.](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit)

**Comment by MoL4okkk** [comment]
Баг исправлен
