### ISSUE TITLE
Спецификация содержит лишнюю информацию

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#206]
Epic #157 Story #170 #204 

В [спецификации ленты постов](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit), предназначенной для описания функционала, содержится информация, относящаяся к дизайну страниц. 

Ожидаемый результат: информация, относящаяся к дизайну, будет вынесена в отдельный документ.

Баг обнаружен повторно в версии v.1

**Comment by Parallusion** [comment]
Исправлено следующее:
1. Убрана вся информация содержащая описание внешнего вида функционала.

[Ознакомиться](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit)

**Comment by MoL4okkk** [comment]
Баг исправлен

**Comment by KharlamovaAlexandra** [comment]
Баг обнаружен повторно

**Comment by KharlamovaAlexandra** [comment]
Было встречено описание дизайна 
![Снимок экрана 2019-12-01 в 20 16 33](https://user-images.githubusercontent.com/47320583/69917462-7a13c080-1477-11ea-930d-e6eebfe3cd03.png)

**Comment by KharlamovaAlexandra** [comment]
Исправлено
