### ISSUE TITLE
[CR-03][Story-*] - Дополнить описание создания нового поста организацией

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#207]
Story-*. [Создание поста]  #97 

Описание ограничений на ввод необходимой суммы в нужде

Название стори |  Написание постов организацией
-- | --
Как кто? | Создатель поста типа "Нужда"
Я хочу | Чтобы при выборе суммы, которую нужно собрать, выскакивало сообщение об ограничении
Чтобы | Чтобы я не мог потребовать собрать недостижимую сумму

Как было | Как должно быть
-- | --
Нет сообщения об ограничении | Есть сообщение об ограничении

Критерии приемлемости
Use Case 1
Когда организация создаёт пост типа нужда
При вводе недопустимой суммы она видит предупреждение и не может опубликовать данный пост

Отмена загрузки объекта

Название стори |  Написание постов организацией
-- | --
Как кто? | Создатель поста
Я хочу | Чтобы при загрузке любого объекта (фото, видео, документ) возле этого объекта отображалась кнопка, при нажатии на которую отменяется загрузка объекта
Чтобы | Чтобы я мог отменить загрузку объекта, который не хочу добавлять к посту

Как было | Как должно быть
-- | --
Нет описания кнопки "Удалить объект" | Есть описание кнопки "Удалить объект"

Критерии приемлемости
Use Case 2
Когда организация по ошибке добавляет объект к посту или решает не добавлять его
Она может нажать на кнопку, отвечающую за удаление этого объекта

**Comment by Parallusion** [comment]
@MoL4okkk прикрепи, пожалуйста, ссылку на спецификацию

**Comment by Parallusion** [comment]
@MoL4okkk исправлено следующее:
1. Добавлено описание ограничений по вводу суммы в нужде.
2. Добавлено описание функционала по отмене загрузки файлов.

[Ознакомиться ](https://docs.google.com/document/d/1p0aFXnl3jeQWKu_cQHuSFoc59WKs-PMpChTdkxWICBA/edit)

**Comment by KharlamovaAlexandra** [comment]
@Parallusion Cr Был применен?
