### ISSUE TITLE
Протестировать инструкцию для развёртывания локального сервера на предмет воспроизводимости

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#208]
Инструкция #155

Выполнить указания по инструкции.
В отчете приложить сведения о том, какие пункты невозможно было выполнить без поиска дополнительной информации.

[Отчёт о результатах тестирования](https://docs.google.com/document/d/1dTk1gdrMK-U2B4tzhrtWSBNHnptv7OiDUFxRbFR3Fdw/edit).

**Comment by MoL4okkk** [comment]
Тестирование завершено, отчёт в дескрипшене
