### ISSUE TITLE
Макет "Пользователь не найден" не соответствует спецификации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#209]
Задача на тестирование #196

Epic #61 
Story #61
 [макет](https://drive.google.com/drive/u/0/folders/1UvGfDFK6YLuAYphbc2bw3sT2umBB05gX)
Ожидается что:
Если организация ввела электронную почту не правильно, то она увидит предупреждение "Пользователь не найден"
Если организация ввела пароль не правильно, то она увидит предупреждение "Неверный пароль"

Фактический результат:

Если организация ввела электронную почту или пароль не правильно то она увидит предупрежедение "Пользователь не найден"

**Comment by stasshtaub** [comment]
Для таких ошибок есть [универсальный макет](https://drive.google.com/open?id=1VlWMBJMe5rP4BE9AsJjhnJyu5qTcjC3l), нет смысла делать отдельный макет под каждый текст ошибки

**Comment by KharlamovaAlexandra** [comment]
Я помню, что мы это обсуждали
Но задача была поднята не потому, что нужен макет, а потому, что так как в папке макет один, то создается ощущение, что и ошибка всегда одинаковая, вне зависимости от того, какое поле заполнено неправильно

Предполагаю, что макет ошибки в данном случае и подобных вообще не нужен, т.к существует универсальный [тут](https://drive.google.com/drive/u/0/folders/1COX7nIbw2omRuBOOK5ExATyuc0nFAl18)

Но так как удалять жалко, пусть лежит.
