### ISSUE TITLE
Ограничения на данные для регистрации благотворительной организации

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#21]
Epic #18 

При регистрации благотворительной организации, необходимо вводить данные и проверять их на корректность. Таблица.

Название|Правило проверки
------------ | -------------
**_Название организации_**|**Ограничение на ввод 100 символов, запрет использования знаков припинания, кроме запятой и тире**
**ИНН организации**|**10 цифр для юрлиц, 12 цифр для физлиц и ИП**

**Comment by YuriSilenok** [comment]
Здравствуйте,

Пожалуйста, заполните таблицу, она потребуется как для WEB так и для мобильной разработки

**Comment by KharlamovaAlexandra** [comment]
Кто должен заполнять эту таблицу?

**Comment by YuriSilenok** [comment]
У нас там где-то были исследования о том, как проверить благонадежность организации. Думаю выводы из того исследования должны лечь в основу требований к этому таску. Думаю Их может сформировать Илья @Parallusion

**Comment by YuriSilenok** [comment]
Думаю эту задачу можно закрыть, только одно замечаник. Вы заполнили таблицу в описании этой задачи, ни кто об этом не узнал. Нужно было в комментариях написать об этом.
