### ISSUE TITLE
Создать шаблон для поднятия бага на макет

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#212]
- [bug-report-on-the-layout.m](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/blob/master/.github/ISSUE_TEMPLATE/bug-report-on-the-layout.md)
- [Bug report on the layout](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/new?assignees=&labels=Bug&template=bug-report-on-the-layout.md&title=%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0+%D0%BF%D1%80%D0%B8+%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8+%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D0%B0+%22%D0%9D%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D0%B0%22)

**Comment by Parallusion** [comment]
@YuriSilenok определил задачу, как планируемую к реализации на текущем спринте. 
Вопрос: Кем подразумевается выполнение данной задачи?

**Comment by YuriSilenok** [comment]
Видимо мной, но я не уверен что успею в текущем спринте это сделать

**Comment by YuriSilenok** [comment]
Создано:
- [bug-report-on-the-layout.m](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/blob/master/.github/ISSUE_TEMPLATE/bug-report-on-the-layout.md)
- [Bug report on the layout](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/new?assignees=&labels=Bug&template=bug-report-on-the-layout.md&title=%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0+%D0%BF%D1%80%D0%B8+%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8+%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D0%B0+%22%D0%9D%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D0%B0%22)

@KharlamovaAlexandra прошу проверить

**Comment by KharlamovaAlexandra** [comment]
Проверено
