### ISSUE TITLE
На макетах создания постов в Android отсутствует функционал прикрепления документов

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#216]
Задача на тестирование #196

Реальность:
На [макетах](https://drive.google.com/drive/u/0/folders/1BcokszTVImmRaY0G2VPgB4eINa6hj5Va)
Новое событие, новая нужда, новое мероприятие отстутсвует функционал прикрепления постов описанный в [документе](https://docs.google.com/document/d/1p0aFXnl3jeQWKu_cQHuSFoc59WKs-PMpChTdkxWICBA/edit)

Ожидание:
На макетах присутствует функционал прикрепления документов

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/drive/u/1/folders/1BcokszTVImmRaY0G2VPgB4eINa6hj5Va)
[Видео-демка](https://drive.google.com/open?id=1BlxzqmXhA9iGa6jSlKksGcG6v-esXIYG)

![добавление документов](https://user-images.githubusercontent.com/47520675/71491309-0cbe3a00-2841-11ea-9aea-771b2231e6d1.jpg)
![добавление документов выбранные документы](https://user-images.githubusercontent.com/47520675/71491308-0c25a380-2841-11ea-8080-8167cd0d1910.jpg)
![прикрепленные документы](https://user-images.githubusercontent.com/47520675/71491310-0cbe3a00-2841-11ea-82f7-7383b650608a.jpg)

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk когда проверится?

**Comment by MoL4okkk** [comment]
Функционал прикрепления документов отображён, баг исправлен
