### ISSUE TITLE
Написать ТЗ на разработку приложения автоматического создания резервных копий

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#217]
[Техническое задание](https://docs.google.com/document/d/1oxA_sRPZG8WQSZv5-Kv2dqUF-M8rXID2PuTHEXzlKJU/edit)

Введение
- Наименование программы - нет паранойи
- Назначение и область применения
- - Приложение предназначено для архивирования данных с репозитория  и гугл диска, с последующей их активацией и загрузкой их на яндекс-диск с назначенным интервалом времени и без участия пользователя. Предполагается что приложение будет состоять из трех модулей:
- - - Модуль выгрузки данных с гугл диска в виде архива
- - - Модуль выгрузки данных с репозитория и дальнейшей архивации
- - - Модуль запускающий работу предыдущих двух и загружающий полученные архивы на яндекс диск с установленным интервалом

**Comment by YuriSilenok** [comment]
@Parallusion Пожалуйста, определите в каком спринте должен разработан этот документ

**Comment by Parallusion** [comment]
@YuriSilenok определил задачу, как планируемую к реализации на 9 спринте.
