### ISSUE TITLE
Обработка запроса на регистрацию новой организации

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#22]
Epic #18 
GlobalStory #19

Сервер должен иметь возможность принимать запрос на регистрацию организации #20 и #24  по протоколу HTTP (если есть идеи другого протокола, предложите в комментариях) и проверять корректность полученных данных #21. 
Через хранимую процедуру записать данные в БД **_номер таска_**.

**Comment by KharlamovaAlexandra** [comment]
Тут что - нибудь сделано?

**Comment by stasshtaub** [comment]
Сделано в тачке #49. На сервере хранится php функция, которая отправляет запрос  в бд на добавление записи о новой организации, когда пользователь регистрируется с правильными данными
