### ISSUE TITLE
Не полное описание функционала комментариев в спецификации.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/Ray-of-hope#223]
Epic #157 

Описание бага:
Разработанная [спецификация](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit) не имеет полного описания функционала комментариев.

От лица дизацнера:
Фраза "Записи в ленте обладают всем присущим записям данного типа функционалом и общим функционалом. А именно: Комментарии," не полностью раскрывает смысл заложенного функционала. Возникает вопрос какое количество комментариев отображать. В каком порядке.

**Comment by Parallusion** [comment]
Мы же обсуждали это, не понимаю бага. В документе написано дословно:
**"...при открытии поста в отдельном окне - отображаются все комментарии к этому посту..."**
Подробнее описать  то, как будут реализованы и описаны комментарии невозможно, так как это уже дизайн.

**Comment by MoL4okkk** [comment]
@KharlamovaAlexandra , @Svyat935 , объясните суть бага подробнее

**Comment by KharlamovaAlexandra** [comment]
Описание уточнено

**Comment by Parallusion** [comment]
@Svyat935 исправлено следующее:
1. Добавлено описание функциональности комментариев

[Ознакомиться](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit)

**Comment by KharlamovaAlexandra** [comment]
https://docs.google.com/document/d/1DMpAqwAcHVgdcNFC3glbpVXzlyJPY5Ey_Us1mJe01fY/edit
список багов

**Comment by KharlamovaAlexandra** [comment]
Баги исправлены. После редактирования не соответствуют абзацы, абзацам в документе

**Comment by MoL4okkk** [comment]
@KharlamovaAlexandra, [список неисправленных багов](https://docs.google.com/document/d/1DMpAqwAcHVgdcNFC3glbpVXzlyJPY5Ey_Us1mJe01fY/edit).

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  пофикшено

**Comment by MoL4okkk** [comment]
Баг исправлен
