### ISSUE TITLE
Поведение сообщений об ошибке при авторизации организации нигде не описано

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#227]
В рамках задачи #197 

Реальность:
Отсутствуют документация описывающая поведение ошибок
Отсутствуют макеты описывающие поведение ошибок
![](https://sun9-41.userapi.com/c854324/v854324382/18f651/lyogVdIJhg4.jpg)

Ожидание:
Существует документация описывающая поведение ошибок

**Comment by KharlamovaAlexandra** [comment]
Исправлено
[стори](https://docs.google.com/document/d/1tc8xZATtXaF6GUWpDQYYTfyn8zvWJbQeJYwcmKPkdW4/edit)

**Comment by MoL4okkk** [comment]
Баг исправлен
