### ISSUE TITLE
Поведение сообщений об ошибке при регистрации организации не описано 

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#228]
В рамках задачи #197 

Реальность:
Нет документации описывающей поведение ошибок при регистрации организации
Нет макетов описывающих поведение ошибок при регистрации организации
![](https://sun9-38.userapi.com/c854324/v854324382/18f6ac/ZsUJgrTLDSU.jpg)

Ожидание:
Есть документация ИЛИ макеты, описывающие поведение ошибок при регистрации организации.

**Comment by KharlamovaAlexandra** [comment]
Исправлено в v.1 [спецификации](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)

**Comment by MoL4okkk** [comment]
Баг исправлен
