### ISSUE TITLE
Разработать макет для страницы регистрации благотворительной организации для web-портала

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#23]
Epic #18 
GlobalStory #19

Разработать макет формы регистрации благотворительной организации.
Макет должен предусмотреть возможность ввода данные перечисленных в задаче #21

Одобряет конечный вариант @KharlamovaAlexandra

**Comment by stasshtaub** [comment]
- [Стартовый экран](https://drive.google.com/open?id=1WrAEhaR1iiElAgYWtXGQ1dSstNLD6AzD)
  - [Выбор типа аккаунта для регистрации](https://drive.google.com/open?id=1_lDyiwToHix_k4IGfxl_A83jsbjVZRcU)
- [Экран регистрации организации](https://drive.google.com/open?id=1VvkNP7cKJ14PQAwnF18e6M9KZC_1sE2d)
  - [Уведомления об ошибках](https://drive.google.com/open?id=1syWeq_Yx24-iqvS7OVOk9F5-O90wOpT6)

**Comment by KharlamovaAlexandra** [comment]
Привет, @stasshtaub!
Будет ли создан в рамках этой задачи экран с сообщением об успешной регистрации. В духе "Вы зарегистрированы, вам на почту выслано письмо"? 
Спасибо

**Comment by stasshtaub** [comment]
Какой из этих?
![Успешная регистрация](https://user-images.githubusercontent.com/47520675/61621626-f56c9680-ac7b-11e9-9f9b-dd2492d8103a.jpg)
![Подтверждение почты](https://user-images.githubusercontent.com/47520675/61621624-f56c9680-ac7b-11e9-8fa4-edab7aca47c3.jpg)

**Comment by KharlamovaAlexandra** [comment]
Думаю второй

**Comment by stasshtaub** [comment]
[Ссылка на гугл-диске](https://drive.google.com/file/d/12zVceghS0pQpUhbltKcQBqJ27IqYqQD9/view)
![Подтверждение почты](https://user-images.githubusercontent.com/47520675/61627766-3c14bd80-ac89-11e9-8b05-6b03c78c82bd.jpg)
