### ISSUE TITLE
Отсутствует возможности добавления документов в web в профиле организации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#232]
В рамках задачи #197 

Реальность:

![](https://sun9-47.userapi.com/c854324/v854324382/18f6e1/23O8t_0FtFE.jpg)

Ожидание:
Можно загрузить документ

**Comment by stasshtaub** [comment]
Документы загружаются только со страницы редактирования профиля, как и было на макетах
