### ISSUE TITLE
[CR-04][Task-97] - Изменить описание функционала

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#239]
Создание поста  #97 

Список типов постов в окне создания

Название стори |  Написание постов
-- | --
Как кто? | Как организация
Я хочу | Чтобы в окне создания поста список с типами постов был закреплён слева, а не выпадал сверху
Чтобы | Чтобы сократить количество кликов

Как было | Как должно быть
-- | --
Выпадающий список расположен сверху | Список закреплен слева

Критерии приемлемости
Use Case 1
Когда организация открывает окно создания поста
Список с типами постов расположен слева в этом окне и закреплён.

**Comment by KharlamovaAlexandra** [comment]
CR применен 
@MoL4okkk

**Comment by MoL4okkk** [comment]
Изменения проверены, задачи на тестирование подняты
