### ISSUE TITLE
Регистрация благотворительной организации через мобильное приложение на Android

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#24]
Epic #18 

Я как представитель благотворительной оргнаизации, должен иметь возможность со стартовой страницы **макет** попасть на страницу регистрации организации **макет**, на которой я заполняю форму регистрации. После нажатия на кнопу зарегистрироваться, на указанную мной электронную почту мне приходит письмо **стори разработки функции автоматической отправки письма составленного по шаблону** с ссылкой подтверждения почты **стори на разработку механизма подтверждения подтверждения почты**.

**Comment by YuriSilenok** [comment]
закрыто как рудимент

**Comment by ZhezlovaDaria** [comment]
Эта задача для функционала отправки письма с помощью приложения на Android. 
Открыто заново, так как над этим ведется работа

**Comment by KharlamovaAlexandra** [comment]
После стартового экрана я хочу увидеть экран выбора роли гражданин/организация. Выбрав организацию хочу увидеть страницу авторизации организации и внизу кнопку регистрация. Нажав на нее я хочу перейти на страницу регистрации организации.
На этом экране я хочу увидеть поле ввода “Название организации”, поле ввода “инн”, поле ввода “электронная почта”, “пароль”, “подтвердите пароль”, кнопку “зарегистрироваться”, кнопку “войти”
Возле каждого поля я хочу увидеть подсказку с тем, как надо заполнить это поле в соответствии с ограничениями
Я хочу заполнить поля и нажав кнопку зарегистрироваться, увидеть сообщение, что ссылка подтверждения почты и регистрации отправлена на почту. После этого сообщения я хочу чтобы меня перенаправило на личный кабинет моего профиля.
( Сразу же, а не после того как я подтвержу ссылку).
В случае если я неверно заполнил поля я хочу увидеть сообщения об ошибках.
При заполнении паролей, они должны вводится скрыто, но должна быть кнопочка посмотреть пароль
 
[подробнее](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)

**Comment by KharlamovaAlexandra** [comment]
Перечитать описание, переоткрыть старые задачи на макеты, переделать, составить сценарии

**Comment by KharlamovaAlexandra** [comment]
@stasshtaub Я жду переделанного макета в соответствии с описанием story на этот спринт (выше описание под которое надо переделать) (конкретно не хватает повторите пароль)

**Comment by stasshtaub** [comment]
[Макет на гугл-диске](https://drive.google.com/open?id=1-P7hO-n-u7ZA7tJ0q2zn4qgDiwbwowht)

![Регистрация организации](https://user-images.githubusercontent.com/47520675/64982719-88fec400-d8c7-11e9-8f67-4719c6e72e2c.jpg)

**Comment by KharlamovaAlexandra** [comment]
@ZhezlovaDaria  Состояние задачи?

**Comment by ZhezlovaDaria** [comment]
@KharlamovaAlexandra В процессе
