### ISSUE TITLE
Документ "Блочные данные" не соответствует критериям

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#240]
Task #187 

**Версия google-документа:** v.0 [Блочные данные](https://docs.google.com/document/d/1yGUuTWXaJJB3utQsU6scVVyzV83CXVipPwVDIMDhEjA/edit)

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | - |  Нет информации о принципе работы блочных данных; пункт "Требования к хранению => Комментарии" упускает поле id для комментария (в модели оно есть)
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + |  
Ясность и однозначность | - |  Непонятна разница между сообщениями в пункте "Сообщения"; неясность в пункте "Требования к хранению => Уведомления" (насчет кол-ва таблиц)
Осуществимость | + |  

Ожидаемый результат:
Документ дополнен, неясности устранены.

**Comment by KharlamovaAlexandra** [comment]
Закрыто за неактуальностью
