### ISSUE TITLE
Документ "Пользователь" не соответствует критериям 

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#241]
Task #187 

**Версия google-документа:** v.0 [Пользователь](https://docs.google.com/document/d/1tpk8DjZPjjVGrppESpf9PaSJpU3IMDxKbcKun0dwbQ8/edit)

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | - |  Основные поля состоят из других полей (не описано каких)
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + |  
Ясность и однозначность | - |  В пункте "Формальное описание" фраза "в основном" наводит на мысль, что описаны не все случаи создания; определиться с вариантом хранения id
Осуществимость | + |  

Ожидаемый результат:
Документ дополнен, неясности устранены.

**Comment by KharlamovaAlexandra** [comment]
Закрыто за неактуальностью
