### ISSUE TITLE
Документ "Пост" не соответствует критериям 

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#242]
Task #187 

**Версия google-документа:** v.0 [Пост](https://docs.google.com/document/d/1MEK8WJxV617u4HtD3laq9NvSt8n0LWHALM9z0S5YTtQ/edit)

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | - |  "Сценарии использования" нет изменения и удаления поста
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + |  
Ясность и однозначность | - |  Пост также связан с Комментарием композицией; "Требования к хранению" определиться с связью Организация-Пост
Осуществимость | + |  

Ожидаемый результат:
Документ дополнен, неясности устранены.

**Comment by KharlamovaAlexandra** [comment]
Закрыто за неактуальность
