### ISSUE TITLE
Документ "Основа" не соответствует критериям 

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#243]
Task #187 

**Версия google-документа:** v.0 [Основа](https://docs.google.com/document/d/1EPJ89VPFIHqgMGk9CimPgZaUfLqmZB9aJxJAuoZK_jI/edit)

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | + |  
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + |  
Ясность и однозначность | - |  Подозрительно мало основных полей; почему уведомления - это структура, когда технически описание такое же как у других полей?
Осуществимость | + |  

Ожидаемый результат:
Документ дополнен, неясности устранены.

**Comment by KharlamovaAlexandra** [comment]
Закрыто за нектуальностью
