### ISSUE TITLE
Диаграмма "Структура сущностей" не соответствует критериям

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#244]
Task #187 

**Версия google-документа:** v.0 [Структура сущностей](https://www.draw.io/#G10s1hvIrmogHVdMOGben8277gCISfmAx4)

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | + |  
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + |  
Ясность и однозначность | - |  Есть вероятность упущения какой-либо функциональности, но это не должно критично влиять на всю структуру; (Левый нижний угол) : Организация превью - не понятно, зачем нужно
Осуществимость | + |  

Ожидаемый результат:
Документ дополнен, неясности устранены.

**Comment by KharlamovaAlexandra** [comment]
Закрыто за неактуальностью
