### ISSUE TITLE
Диаграмма "Функциональная схема" не соответствует критериям документации

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#246]
Task #245 

**Версия google-документа:** v.1 [Функциональная схема](https://drive.google.com/file/d/1tT2DKYbO14Pa5-obYEzvXQkKCxVw5vqd/view)

Критерий | Результат | Комментарий
-- | -- | --
Полнота описания | - |  Отсутствует описание функционала сайта и модерации; отсутствует информация о том, что из себя представляет конечный продукт; отсутствует описание настроек ленты; ветка "Организация" -> "Лента событий" - отсутствует информация о возможностях Диалогов, о возможностях Комментариев, о возможностях Часто задаваемых вопросов, о функционале Настроек.
Актуальность | + |  
Логика и согласованность | + |  
Непротиворечивость | + |  
Структурированность, адаптированность | + |  
Ясность и однозначность | + | 
Осуществимость | + |  

Комментарий тестировщика: нужно ли добавить в возможности организации просмотр фотографии и скачивание документов других организаций?

Ожидаемый результат:
Документ изменён и дополнен необходимой информацией.

**Comment by KharlamovaAlexandra** [comment]
Документ функциональная схема не является актуальным и будет переделываться с нуля в другом формате
