### ISSUE TITLE
Стори "Лента постов" не соответствует критериям спецификации

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#248]
Epic #157 Story #170 #250 

[Спецификация](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit) v.2

Критерий | Результат 
-- | -- 
Завершённость | - 
Непротиворечивость | + 
Ясность | + 
Согласованность | + 
Проверяемость | +
Наличие структуры | + 
Полнота описания | - 
Логика | + 
Однозначность | + 
Единичность | + 

Комментарий: нет описания фильтрации постов.

**Comment by KharlamovaAlexandra** [comment]
Исправлено. 
Версия спецификации v.3

**Comment by MoL4okkk** [comment]
Баг исправлен
