### ISSUE TITLE
Разработать критерии для тестирования спецификаций

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#249]
Подготовить и обосновать критерии для тестирования спецификаций проекта

[Документ, описывающий критерии](https://docs.google.com/document/d/1Cgyt-yHdH0KgR034OFgCj1q2xfyIAfvR4uZ_ufRVt1o/edit).

**Comment by MoL4okkk** [comment]
Критерии составлены и утверждены продуктовнером
