### ISSUE TITLE
Разработать макет стартовой страницы для веб-портала

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#25]
Epic #18 
GlobalStory #19

Разработать макет стартовой страницы.

Одобряет конечный вариант @KharlamovaAlexandra

**Comment by stasshtaub** [comment]
[Стартовый экран](https://drive.google.com/open?id=1WrAEhaR1iiElAgYWtXGQ1dSstNLD6AzD)

**Comment by YuriSilenok** [comment]
На сколько законно использовать фотографию фона, она похожа на профессиональную?

**Comment by stasshtaub** [comment]
Эту законно, она без авторских прав с бесплатного фотостока

**Comment by KharlamovaAlexandra** [comment]
Мне нравится. Одобряю

**Comment by KharlamovaAlexandra** [comment]
Для стартового экрана использовать фоном картинку (тут должна быть ссылка на картинку с девочкой и собачкой)

**Comment by stasshtaub** [comment]
Ниче не понял. Макет скинуть с этим текстом?

**Comment by KharlamovaAlexandra** [comment]
Текст передалать

**Comment by KharlamovaAlexandra** [comment]
Остальное это критерии приемки макета для Ильи

**Comment by KharlamovaAlexandra** [comment]
И положи фоновую картинку на Гугл диск, чтобы я могла прикрепить ссылку на нее

**Comment by stasshtaub** [comment]
[Фон](https://drive.google.com/file/d/16ZmfCEs2hUxlW12xWQ18oZ0NKrs2mqvy/view?usp=drivesdk)
Текст на [стартовом](https://rayofhope-opensource.000webhostapp.com/) поменял
