### ISSUE TITLE
Протестировать спецификацию "Лента постов"

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#250]
Epic #157
В рамках #170 задачи
По критериям разработанным в #249 протестировать [спецификацию](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit) "* .Лента постов"

**Comment by MoL4okkk** [comment]
Тестирование завершено
