### ISSUE TITLE
Story-01.Регистрация благотворительной организации не соответствует критериям спецификации

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#253]
Epic #18 

[Спецификация](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit) в версии v.1

Критерий | Результат 
-- | -- 
Завершённость | + 
Непротиворечивость | + 
Ясность | + 
Согласованность | + 
Проверяемость | +
Наличие структуры | +
Полнота описания | +
Логика | + 
Однозначность | - 
Единичность | + 

Комментарий: что подразумевается под возможностью входа без подтверждения электронной почты (последний абзац)?

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  исправлено

**Comment by MoL4okkk** [comment]
@KharlamovaAlexandra , выявлен новый баг. Обновил дескрипшен

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  Было обговорено командой, что почта нужна только для части функционала. Следовательно чтобы пользоваться приложением почту подтверждать необязательно. Подтвердить потребуется только для получения доп функций

**Comment by MoL4okkk** [comment]
Баг исправлен
