### ISSUE TITLE
Протестировать макеты регистрации организации в WEB на соответствие спецификации

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#254]
Epic #18  

Протестировать макеты на соответствие спецификации, изменённой после применения CR #181.
Результаты занести в [таблицу](https://docs.google.com/spreadsheets/d/1pn0eiGvR_M5N5YzgW9QFcqIv-y_k0FgnkdhFRbGf8Kw/edit).
Поднимать баги по мере нахождения.

**Comment by Parallusion** [comment]
Макеты протестированы, выявлены следующие баги: #260 и #261
