### ISSUE TITLE
Отправка письма для подтверждения электронного адреса

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#26]
Epic #18 

Пользователь должен получать электронное письмо с ссылкой на подтверждение регистрации. #27 
[Рассмотреть](https://ru.wordpress.org/support/topic/%D0%BF%D0%BE%D0%B4%D1%82%D0%B2%D0%B5%D1%80%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8/) возможность настройки через WordPress

**Comment by YuriSilenok** [comment]
Привет 

в каком состоянии находиться эта задача?

Спасибо.

**Comment by stasshtaub** [comment]
Письмо отправляется в функции регистрации организации после проверки введенных данных и добавления пользователя в бд. В письме ссылка для подтверждения с двумя get-параметрами: email, который подтверждается, и hash-ключ, который сравнивается с hash ключём записанным в бд у пользователя с переданным email'ом

**Comment by YuriSilenok** [comment]
Стас, пожалуйста, если ты эту задачу делаешь, то перевесь ее на себя. Если эта задача сделалана, то перевесь ее на себя и закрой.

Справшивая про состояние задачи, нужно знать, делается она или сделана, если делается, успеваем ли мы ее сделать до конца спринта.
