### ISSUE TITLE
Ошибка при проектировании макета "Без ошибок"

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#260]
[01. Регистрация благотворительной организации](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)
#20 
Версия: **19:45 16 сент.**
[Ссылка на макет](https://drive.google.com/drive/u/0/folders/1kusWjHT691CDYcLUhRPxSVMB4ZjJXz5A)

**Фактический результат:** 
На макете отсутствуют подсказки, в каком-либо виде.

**Ожидаемый результат:** 

Обеспечить возможность подсказок для пользователя:
Для пароля : “Минимум 8 знаков: цифры и латинские буквы”
Для названия: “Зарегистрированное название организации / привычное для граждан название организации ” 
Для ИНН: “10 цифр”

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/open?id=1kusWjHT691CDYcLUhRPxSVMB4ZjJXz5A)

![Подсказки](https://user-images.githubusercontent.com/47520675/77260440-1e28ae00-6c99-11ea-8ed6-72e46671ad8c.jpg)

**Comment by MoL4okkk** [comment]
Баг исправлен
