### ISSUE TITLE
Ошибка при проектировании макета "С ошибками"

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#261]
[01. Регистрация благотворительной организации](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)
#20 
Версия: **19:46 16 сент.**
[Ссылка на макет](https://drive.google.com/drive/u/0/folders/1kusWjHT691CDYcLUhRPxSVMB4ZjJXz5A)

**Фактический результат:** 
Сообщения об ошибках не соответствуют спецификации.

**Ожидаемый результат:** 

При неуспешности проверки 1 выдавать ошибку “Заполните все поля”
При неуспешности проверок 2 и 10 выдавать ошибку “Некорректный email”
При неуспешности проверок 3 и 4 выдавать ошибку “Некорректный ИНН”
При неуспешности проверок 5, 6 и 11 выдавать ошибку “Некорректный пароль”

**Comment by KharlamovaAlexandra** [comment]
Макеты можно не исправлять, изменить текст ошибок только в реализации в соответствии со спецификацией
