### ISSUE TITLE
Ошибка при проектировании макета "Подтверждение почты"

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#262]
Epic #20 Task #255 
[Story 01. Регистрация организации ](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)
Версия от 16 сентября 2019

**Фактический результат:** 
![image](https://user-images.githubusercontent.com/55210615/70779100-dab6cd80-1d94-11ea-9c28-494100220ed9.png)

**Ожидаемый результат:** Текст на макете соответствует спецификации.
**Неожиданный результат:** На макете реализована кнопка "Ок", описания которой нет в спецификации.

**Comment by KharlamovaAlexandra** [comment]
Наличие кнопки может быть по усмотрению дизайнера. Текст можно исправить только в реализации и не исправлять макет
