### ISSUE TITLE
Нет макетов, отображающих подсказки при регистрации в Android

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#263]
Epic #20 Task #255 

[Story 01. Регистрация](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)

Фактический результат: отсутствуют макеты, отображающие подсказки для полей ввода при регистрации организации в Android.
Ожидаемый результат: необходимые макеты созданы.

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/open?id=1-P7hO-n-u7ZA7tJ0q2zn4qgDiwbwowht)

![Подсказки](https://user-images.githubusercontent.com/47520675/77261210-f9830500-6c9d-11ea-8774-298a57384d53.jpg)

**Comment by MoL4okkk** [comment]
Баг исправлен
