### ISSUE TITLE
Ошибка при проектировании макетов "Некорректный пароль" и "Неправильный email"

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#264]
Epic #20 Task #255 
[Story 01. Регистрация организации ](https://docs.google.com/document/d/1QkQMIYAaNvvknFlBldHHwvcq2iuWHP7E4QYHCFUZdy4/edit)
Версия от 16 сентября 2019

**Фактический результат:** текст ошибок на макетах не соответствует спецификации:
![image](https://user-images.githubusercontent.com/55210615/70787429-aac0f780-1d9f-11ea-9fc5-15de1125a9a6.png)
![image](https://user-images.githubusercontent.com/55210615/70787436-b1e80580-1d9f-11ea-892b-33e2f929282a.png)

**Ожидаемый результат:** текст ошибок соответствует указанному в спецификации: 
![image](https://user-images.githubusercontent.com/55210615/70787502-dba12c80-1d9f-11ea-96e3-0bf2e9c7d6b3.png)

**Comment by KharlamovaAlexandra** [comment]
Текст можно изменить только  в реализации, не изменяя макеты
