### ISSUE TITLE
Разработать шаблон письма отправляемое при подтверждении электронной почты благотворительной организации

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#27]
Epic #18

Пользователь должен получать письмо с текстом соответствующим общим нормам и культуре переписки.

**Comment by YuriSilenok** [comment]
Привет @KharlamovaAlexandra, думаю это по твоему таланту задача.

**Comment by KharlamovaAlexandra** [comment]
https://docs.google.com/document/d/1IavhKfmaqKwB0aeDczJjUGWqHmu3WlHIO33oBoIWmXE/edit
