### ISSUE TITLE
Документация содержит описание дизайна

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#277]
Версия документа от 2 декабря 2019 г., 17:16

Документ ["Типы записей"](https://docs.google.com/document/d/1p0aFXnl3jeQWKu_cQHuSFoc59WKs-PMpChTdkxWICBA/edit) содержит описание внешнего вида ленты постов (пункты "Как выглядят посты в WEB" и "Посты в Android").

Ожидаемый результат: документация изменена, описание внешнего вида исключено.

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk Исправлено, на перепроверку

**Comment by MoL4okkk** [comment]
Баг исправлен
