### ISSUE TITLE
Построить дерево целей для неравнодушных граждан

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#280]
Срок: до 07.03.2020 включительно.
По завершению перевести на Илью
https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/143

**Comment by XeniaWorontsova** [comment]
@Parallusion 
готово.
Ссылка на документ со всеми деревьями: https://drive.google.com/file/d/1Ij-aThmSJHgzoYyEH7FV2txws8nf3RP-/view?usp=sharing

**Comment by Parallusion** [comment]
@XeniaWorontsova при тестировании дерева целей для неравнодушных граждан возникли следующие вопросы:

1. О каком инвентаре идёт речь? Что он из себя представляет и зачем он нужен? Это прослеживается и в других деревьях, так что дублировать этот вопрос в других тасках не буду.

**Comment by XeniaWorontsova** [comment]
@Parallusion 
Попыталась конкретизировать
