### ISSUE TITLE
Построить дерево целей волонтеров

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#281]
Срок: до 08.03.2020 включительно.
По завершению перевести на Илью
https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/143

**Comment by XeniaWorontsova** [comment]
@Parallusion 
готово.
Ссылка на документ со всеми деревьями: https://drive.google.com/file/d/1Ij-aThmSJHgzoYyEH7FV2txws8nf3RP-/view?usp=sharing

**Comment by Parallusion** [comment]
@XeniaWorontsova при тестировании дерева целей волонтеров возникли следующие вопросы:

1)Что подразумевается под "Патронировать инвалидов и лиц с ограниченными возможностями здоровья"? Нельзя ли как то это понятнее представить?
2)Корректна ли цель получить психологическое образование? (она слишком широкая как по мне и тяжело ассоциировать её с целью "Оказать психологическую поддержку смертельно-больным людям")

**Comment by XeniaWorontsova** [comment]
@Parallusion 
Нужен ретест
