### ISSUE TITLE
Построить дерево целей юридических лиц

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#282]
Срок: до 09.03.2020 включительно.
По завершению перевести на Илью
https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/143

**Comment by XeniaWorontsova** [comment]
@Parallusion 
готово.
Ссылка на документ со всеми деревьями: https://drive.google.com/file/d/1Ij-aThmSJHgzoYyEH7FV2txws8nf3RP-/view?usp=sharing

**Comment by Parallusion** [comment]
@XeniaWorontsova, при тестировании дерева целей юридических лиц возникли следующий вопрос:
1) Что подразумевается под "Заключить договор с нуждающимся на оказание помощи"? Каким образом это происходит? Есть пример заключения договора?

**Comment by XeniaWorontsova** [comment]
@Parallusion 
Пример договора по ссылке: https://drive.google.com/file/d/1HCs9i7mCLIlMs0knd7I-0B5aYDr3oQbO/view?usp=sharing
