### ISSUE TITLE
Построить дерево целей для благотворительной организации

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#285]
По завершению перевести на Илью
https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/143

- [x] нумерация
- [x] Что подразумевается под "ресурсами" в пункте "Подготовить ресурсы"?
- [x] Почему цель "Сообщить о благотворительном мероприятии органам власти Костромской области" состоит из следующих целей: "Определиться с временем проведения мероприятия" и "Определиться с местом проведения мероприятия"? Правильно ли я понимаю, что для того, чтобы донести информацию о мероприятии властям достаточно определиться с временем и местом мероприятия?
- [x] Хватит ли для того, чтобы провести мероприятия сообщить о них органам власти и гражданам? Больше ничего не нужно, чтобы провести мероприятие?
- [x] Что подразумевается под "Оформить копилку для сбора средств"?
- [x] Чем отличаются в контексте дерева мероприятия, события и акции?
- [x] Случайно ли в цели "Определить срочность оказания помощи" две одинаковые подцели: "Определить список необходимого" и "Определить список необходимого"?
- [x] В дереве очень часто встречается "специалист", что он из себя представляет? Возможно ли как-нибудь конкретизировать данное понятие в целях данного дерева?
- [x] Какому количественному критерию ты придерживалась при написании дерева целей? Существует число Миллера (7+-2), по которому в основном строятся деревья, но как я понимаю, у тебя был другой принцип, потому что дерево целей не удовлетворяет данному критерию, но если ты следовала другим принципам, то напиши, пожалуйста.

**Comment by XeniaWorontsova** [comment]
@Parallusion Задача сделана, нужно протестировать. 
Ссылка на документ: https://drive.google.com/file/d/1Ij-aThmSJHgzoYyEH7FV2txws8nf3RP-/view?usp=sharing

**Comment by Parallusion** [comment]
@XeniaWorontsova при тестировании дерева целей я столкнулся с проблемой ориентации в листьях, т.е. у листьев нет индекса, на которые я мог бы ссылаться в своих сообщениях и в принципе. Поэтому, если ты не против, предлагаю тебе пронумеровать (расставить индексы) листья деревьев. Если ты согласна с этим, то я подниму на тебя баг. 

Также при тестировании дерева целей для благотворительной организации возникли следующие вопросы:
1) Что подразумевается под "ресурсами" в пункте "Подготовить ресурсы"?
2)Почему цель "Сообщить о благотворительном мероприятии органам власти Костромской области" состоит из следующих целей: "Определиться с временем проведения мероприятия" и "Определиться с местом проведения мероприятия"? Правильно ли я понимаю, что для того, чтобы донести информацию о мероприятии властям достаточно определиться с временем и местом мероприятия?
3) Хватит ли для того, чтобы провести мероприятия сообщить о них органам власти и гражданам? Больше ничего не нужно, чтобы провести мероприятие?
4) Что подразумевается под "Оформить копилку для сбора средств"?
5) Чем отличаются в контексте дерева мероприятия, события и акции? 
6) Случайно ли в цели "Определить срочность оказания помощи" две одинаковые подцели: "Определить список необходимого" и "Определить список необходимого"? 
7) В дереве очень часто встречается "специалист", что он из себя представляет? Возможно ли как-нибудь конкретизировать данное понятие в целях данного дерева?

**Comment by XeniaWorontsova** [comment]
> @XeniaWorontsova при тестировании дерева целей я столкнулся с проблемой ориентации в листьях, т.е. у листьев нет индекса, на которые я мог бы ссылаться в своих сообщениях и в принципе. Поэтому, если ты не против, предлагаю тебе пронумеровать (расставить индексы) листья деревьев. Если ты согласна с этим, то я подниму на тебя баг.

@Parallusion 
Согласна

**Comment by XeniaWorontsova** [comment]
> 7\. Какому количественному критерию ты придерживалась при написании дерева целей? Существует число Миллера (7+-2), по которому в основном строятся деревья, но как я понимаю, у тебя был другой принцип, потому что дерево целей не удовлетворяет данному критерию, но если ты следовала другим принципам, то напиши, пожалуйста.

@Parallusion 
Никогда никто в жизни мне не говорил про количественный критерий. Чем я руководствовалась - не меньше 3-х уровней.  Я бы хотела изучить информацию по ссылке, где ты нашел этот критерий, так как я везде вижу разную информацию по этому вопросу. Скинь, пожалуйста

**Comment by XeniaWorontsova** [comment]
> 7\. Какому количественному критерию ты придерживалась при написании дерева целей? Существует число Миллера (7+-2), по которому в основном строятся деревья, но как я понимаю, у тебя был другой принцип, потому что дерево целей не удовлетворяет данному критерию, но если ты следовала другим принципам, то напиши, пожалуйста.

Это дерево соответствует этому критерию

**Comment by XeniaWorontsova** [comment]
> 5\. Случайно ли в цели "Определить срочность оказания помощи" две одинаковые подцели: "Определить список необходимого" и "Определить список необходимого"?

Случайность, исправлено

**Comment by XeniaWorontsova** [comment]
> 4\. Чем отличаются в контексте дерева мероприятия, события и акции?

Мероприятия и акции я все-таки решила объединить, немного конкретизировав в одном случае слово "мероприятие". 
Мероприятие предполагает под собой привлечение людей (сбор людей) для какой-либо цели (сбор средств, уборка территории). Событие же понятие шире, оно может включать в себя проведение мероприятия, но так же к этому относится рождение ребенка, выздоровление человека, с помощью собранных средств и т.д.

**Comment by XeniaWorontsova** [comment]
> 3\. Что подразумевается под "Оформить копилку для сбора средств"?

Попыталась написать более понятно

**Comment by XeniaWorontsova** [comment]
> 6\. В дереве очень часто встречается "специалист", что он из себя представляет? Возможно ли как-нибудь конкретизировать данное понятие в целях данного дерева?

Попыталась конкретизировать

**Comment by XeniaWorontsova** [comment]
> 1. Что подразумевается под "ресурсами" в пункте "Подготовить ресурсы"?

Конкретизировала

**Comment by XeniaWorontsova** [comment]
> 1. Почему цель "Сообщить о благотворительном мероприятии органам власти Костромской области" состоит из следующих целей: "Определиться с временем проведения мероприятия" и "Определиться с местом проведения мероприятия"? Правильно ли я понимаю, что для того, чтобы донести информацию о мероприятии властям достаточно определиться с временем и местом мероприятия?

Уточнила

**Comment by XeniaWorontsova** [comment]
> 2\. Хватит ли для того, чтобы провести мероприятия сообщить о них органам власти и гражданам? Больше ничего не нужно, чтобы провести мероприятие?

Добавила еще задачи

**Comment by XeniaWorontsova** [comment]
@Parallusion, please, retest
