### ISSUE TITLE
Разработать макет уведомлений об ошибках на вэб-портале

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#29]
Epic #18

В результате обработки запроса пользователя, сервером может быть возвращена ошибка. Необходимо разработать макет уведомления о подобных ошибках.
Например, отказ о регистрации благотворительной организации если ИНН организации уже существует в системе.

**Comment by KharlamovaAlexandra** [comment]
Для выполнения этой задачи следует знать, какие вообще ошибки могут быть

**Comment by YuriSilenok** [comment]
Я предполагаю что дожен быть заголовок ошибки, текст ошибки и возможно кнопка ОК. Любая ошибка должна подходить под этот макет.

**Comment by stasshtaub** [comment]
Будут лишние клики. На этом экране лучше такие подсказки у каждого поля, которое проверяется. Для других ошибок (нет сети, например) уведомление будет с названием, текстом и кнопкой ок, в отдельном всплывающем сообщении. Такое сообщение уже универсальное для любых других экранов и ошибок

**Comment by stasshtaub** [comment]
[Ссылка на гугл-диске](https://drive.google.com/open?id=11YI_XESRHlGySDXawWi0w_qXwvslQc9t)
![Сообщение об ошибке](https://user-images.githubusercontent.com/47520675/61450393-a82cb400-a95f-11e9-930e-fa7eddc751ca.jpg)

**Comment by KharlamovaAlexandra** [comment]
Одобрено
