### ISSUE TITLE
Написать сценарии для регистрации организации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#290]
Epic #286
Написать сценарии для android приложения покрывающие область регистрации организации 
Прикрепить на них ссылку 

[Сценарии для класса RegOrg](https://docs.google.com/spreadsheets/d/1Bz_NG9aFTjp3Xt59unL-ja0UduV0eBYEEsRgdaFmVPk/edit#gid=2113115713)
[Сценарии для класса CallDB_RegOrg](https://docs.google.com/spreadsheets/d/1Bz_NG9aFTjp3Xt59unL-ja0UduV0eBYEEsRgdaFmVPk/edit#gid=2144553199)

**Comment by MoL4okkk** [comment]
Сценарии написаны, ссылки в описании
