### ISSUE TITLE
Разработать Story для личного прфиля организации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#294]
Epic #74
Относится к требованиям #147 
Написать стори в соответствии с принятыми правилами и отдать на тестирование 
Вынести к реализации на 14 спринт 
Рассмотреть cr ( если появятся )
[стори](https://docs.google.com/document/d/16cAaS3Rm5sgUYvIXeKKn8VT5R9YTQ-JJRVpWvVaXA7o/edit)

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  В тетсирование

**Comment by MoL4okkk** [comment]
Тестируется
