### ISSUE TITLE
Изучить вопрос легальности Ц.А

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#3]
Узнать как проверить существует ли официально организация пытающаяся зарегистрироваться в приложении ( какие данные для этого нужны  ). Возможно ли это сделать через налоговую?

**Comment by Parallusion** [comment]
[Ссылка на документ](https://docs.google.com/document/d/1El-erQWsr1iUQLJhd5lTxFkua0lVwooiQ5F9r91g7TU/edit?usp=sharing)

**Comment by KharlamovaAlexandra** [comment]
Одобрено
