### ISSUE TITLE
Разработать макет уведомлений об ошибках на Android

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#30]
Epic #18

В результате обработки запроса пользователя, сервером может быть возвращена ошибка. Необходимо разработать макет уведомления о подобных ошибках.
Например, отказ о регистрации благотворительной организации если ИНН организации уже существует в системе.

**Comment by KharlamovaAlexandra** [comment]
Для выполнения этой задачи следует знать, какие вообще ошибки могут быть

**Comment by stasshtaub** [comment]
- [Экран регистрации организации](https://drive.google.com/open?id=1JuavsXKXkvKS9lJN-_cSkVOuQLPoiAiQ)
  - [Уведомление о некорректном ИНН](https://drive.google.com/open?id=1Qtpr25CX6PebmwlD7BnToOmU0SgChsod)
  - [Уведомление о неправильном E-mail](https://drive.google.com/open?id=1OmL_nc2LOOPLIqj7KFSEtUN9l23eLZSr)
  - [Уведомление о некорректном пароле](https://drive.google.com/open?id=1JKzD7TGuD6WoP2cn5av6YeZllt9VBY33)

[Демка со всеми экранами](https://xd.adobe.com/view/a05ccc9f-f7dd-4140-71b4-f39fb0b6292e-d66d/)

**Comment by YuriSilenok** [comment]
> Для выполнения этой задачи следует знать, какие вообще ошибки могут быть

Сенарий такой.
- заполнили с точки зрения гуи все верно
- отправили запрос на сервер о регистрации
- но оказалась что организация с таким ИНН существует или БД недоступна
Я ожидаю что это отлельное всплывающее сообщение будет с текстом.
Не прошу расписать все возможные сообщения, а нужен шаблон универсального.

**Comment by stasshtaub** [comment]
[Уведомление об ошибке](https://drive.google.com/open?id=1VlWMBJMe5rP4BE9AsJjhnJyu5qTcjC3l)

**Comment by YuriSilenok** [comment]
Да, именно это я и имел ввиду.
Саша, если тебя все устраивает, пожалуйста, закрой задачу

**Comment by KharlamovaAlexandra** [comment]
Согласна с выполнением
