### ISSUE TITLE
Провести ревью багов

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#303]
Провести ревью багов относительно Макетов и WEB

**Comment by MoL4okkk** [comment]
@KharlamovaAlexandra 

#264 - текст на макетах не совпадает с указанным в спецификации:
- вместо текста ошибки - текст подсказки с неверным количеством символов;
![image](https://user-images.githubusercontent.com/55210615/77121427-3a83db00-6a4c-11ea-8a3e-e945a3c31dab.png)

- "Неправильный" вместо "Некорректный".

#262 - отличия в тексте сообщения о подтверждении почты, наличие на макете кнопки "ОК", описания которой нет в спецификации.

#261 - отличия в тексте ошибок.

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk Баги закрыты так как они не критичны, и не стоят таких затрат усилий
