### ISSUE TITLE
Анализ продуктов стейкхолдеров проекта

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#304]
Epic #147 
- [x] Найти сайты и социальные сети организаций ( потенциальных пользователей, не менее 10 )

- [x] Найти системы с которыми они работают и пользуются постоянно  ( с расчетом на то, что наша система будет к ним обращаться )

- [x] Найти системы наших конкурентов

- [x] Найти системы дружественных нам коллег

- [x] Найти системы с которыми мы сами будем работать

**Comment by MyDanielM** [comment]
Отчёт по задаче
https://drive.google.com/open?id=1f67EneAFppuXvjJmbSF4ideidPwlZee1A_WN6e42Lec

**Comment by KharlamovaAlexandra** [comment]
@MyDanielM  Не увидела в отчете систем с которыми мы сами будем работать. Куда смотреть?

**Comment by MyDanielM** [comment]
@KharlamovaAlexandra Добавил лист с системами, которые мы можем использовать

**Comment by KharlamovaAlexandra** [comment]
Принято, @MoL4okkk в тестирование

**Comment by MoL4okkk** [comment]
Принято на тестирование
