### ISSUE TITLE
Story-08. Лента постов не соответствует критериям спецификации

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#306]
Спецификация ["Лента постов"](https://docs.google.com/document/d/1TP_bUWStqtJZPt8JGelRgwGyq9PCXUbF2qKxWsSFwJQ/edit)  (версия от 7 декабря 2019 г., 21:58) не соответствует следующим критериям:

Критерий | Результат 
-- | -- 
Завершённость | + 
Непротиворечивость | + 
Ясность | - 
Согласованность | + 
Проверяемость | +
Наличие структуры | +
Полнота описания | +
Логика | + 
Однозначность | - 
Единичность | + 

Комментарий: 13-ый абзац (о фильтрации записей): непонятно, в каких случаях и где присутствует фильтр "Только в моём городе".

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk Исправлено

**Comment by MoL4okkk** [comment]
Баг исправлен
