### ISSUE TITLE
Реализовать макет для стартовой страницы и страницы регистрации в мобильном приложении под Android

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#31]
Epic #18
GlobalStory #19

Реализовать макет #15 формы регистрации благотворительной организации а так же реализовать ограничения перечисленные в таблице задачи #21

**Comment by KharlamovaAlexandra** [comment]
Если задача закончена, то закрой ее пожалуйста @ZhezlovaDaria
