### ISSUE TITLE
Резюме пользовательских ролей

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#32]
Изучить, сделать

**Comment by YuriSilenok** [comment]
Use case ?

**Comment by KharlamovaAlexandra** [comment]
Думаю да. Есть старый. Но он требует пересмотра и обновления

**Comment by KharlamovaAlexandra** [comment]
В работе над этой задачей мне потребуется помощь @Parallusion , @YuriSilenok  и других по их желанию. 

https://drive.google.com/drive/u/0/folders/1nVI7bT9hPAajFGejAt76rfNqcUPE2h2m - тут расположена старая диаграмма. Но я думаю что в ней много неточностей

Для начала я бы хотела уточнить какие у нас будут стейкхолдеры и акторы? Я уверена , что это не только гражданин и организация.  Как минимум стекхолдером у нас будет база ФНС. И я не уверена, правильно ли использовать гражданина, не слишком ли это обобщенно?  

Спасибо

**Comment by YuriSilenok** [comment]
> других по их желанию.

нужна ли нам возможность через символ @ проект, в этом случае уведомление получат все, кто есть в проекте?

stakeholders - заинтересованные стороны
Думаю ФНС нами не будет заинтересована, мы ей будем заинтересованы.

Мысль: Попытка выявить все роли которые мы не планируем в первой фазе похоже спуск к водопадной модели.

**Comment by KharlamovaAlexandra** [comment]
Мне бы точно пригодилась такая возможность для упоминания всех 

Стекхолдеры, это еще и те в ком заинтересованы мы. Они нам нужны для проверки организации, значит они наши стекхолдеры. ( P.S. Стекхолдеры могут быть так хе и негативные, те кто будет нам мешать ) 

Ну надо выявить хотя бы тех кто планируется в первой фазе. 
Регистрация организации точно есть в первой фазе, значит всех кто с этим связан мы должны определить

**Comment by YuriSilenok** [comment]
теперь можно через @Students-of-the-city-of-Kostroma/ray-of-hope заспамить весь проект
