### ISSUE TITLE
Исследование предметной области

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#33]
Epic: https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/97

Придумать как организовать данные
[Файл](https://docs.google.com/document/d/1J1WMfvaO6jvt0QB2ELL5CykKrdTjsnIqjkjeIFznTi8/edit) с исследованием
Это исследование затрагивает следующие Story: #141

**Comment by YuriSilenok** [comment]
Это у Вас в следующем семестре. Создам док. В него соберем все сведения которые должны храниться.

**Comment by YuriSilenok** [comment]
+ @Takunava
Денис тоже в этом заинтересован

**Comment by YuriSilenok** [comment]
И @Parallusion 
Илья как аналитик собирающий сведения.

**Comment by YuriSilenok** [comment]
Я бы сказал что это достаточно большая задача, потому что этому учаться в течении семестра
Вот [док](https://docs.google.com/document/d/1J1WMfvaO6jvt0QB2ELL5CykKrdTjsnIqjkjeIFznTi8/edit) на исследование предметной области.
@Parallusion посмотрите, что Вы можете добавить в этот док?

**Comment by Parallusion** [comment]
> Я бы сказал что это достаточно большая задача, потому что этому учаться в течении семестра
> Вот [док](https://docs.google.com/document/d/1J1WMfvaO6jvt0QB2ELL5CykKrdTjsnIqjkjeIFznTi8/edit) на исследование предметной области.
> @Parallusion посмотрите, что Вы можете добавить в этот док?

Не понял вопроса, что имеется в виду под "что Вы можете добавить в этот док?"?

**Comment by YuriSilenok** [comment]
Выв собирали некоторые сведения об организации, в том числе и о том, как проверить организацию.
Что мы длолжны о ней хранить, возможно юр адрес, счета

**Comment by YuriSilenok** [comment]
Еще есть раздел с бизнесправилами, там можно описать как будет происходить процесс регистрации (подтверждение почты, сверка с БД налоговой...)

**Comment by KharlamovaAlexandra** [comment]
Тоже мертвецкая тишь

**Comment by Parallusion** [comment]
Задача требует обсуждения.

**Comment by YuriSilenok** [comment]
Эта задача требует прохождения нескольких этапов.
1. Илья
1.1. Нужно предоставить информацию о том, какие сведения нам нужно хранить вообще. хотя бы списочек
1.2. Определить список ролей и набор функций которые им будут доступны в системе
2. Денис + студент 4 курса (УД КП)
2.1. Проводят анализ предметной области
2.2. Стоят диаграмму функциональных зависимостей (не обязательно, но помогает структурировать данные на ранней стадии)
2.3. Строят ER диаграмму
2.4. Описывают реляционную схему зависимостей
3. Cтудент 4 курса (УД КП) -> реализуют вторую БД
4. Денис -> пробует переключить на правильную БД сайт

Думаю это уже не стори, а эпик и под это все нужно поднять соответствующие стори.

**Comment by KharlamovaAlexandra** [comment]
А давно у нас эпики в процессе? 
И что вообще происходит с этой задачей она как то развивается?

**Comment by YuriSilenok** [comment]
> А давно у нас эпики в процессе?
> И что вообще происходит с этой задачей она как то развивается?

Переведенена в таск, до стори она не дотягивыает, так как пользователь не работает с БД.

**Comment by KharlamovaAlexandra** [comment]
Состояние задачи?

**Comment by XeniaWorontsova** [comment]
В процессе. Можно смотреть и критиковать таблицу и ERD. Ограничения будут прописаны ориентировачно завтра.

**Comment by YuriSilenok** [comment]
Вынес обсуждение диаграммы в чат

**Comment by kamisam4** [comment]
По незнанию закрыл и реопен сделал, не бейте

**Comment by YuriSilenok** [comment]
Главное что отписал
Но на самом деле ее нужно закрыть, так как @XeniaWorontsova Уже не занимается исследованием предметной области, ведь так?

**Comment by XeniaWorontsova** [comment]
на текущем этапе - не занимаюсь, но хотели же от общей задачи делать задачи на отдельные спринты. Эта не общая задача, @YuriSilenok ?

**Comment by YuriSilenok** [comment]
Тогда нужно поднять дочерние задачи на исследование предметной области на каждый спринт и закрыть те, которые выполнены.

**Comment by XeniaWorontsova** [comment]
@YuriSilenok 
![image](https://user-images.githubusercontent.com/33964762/70078958-c3e5dd80-1614-11ea-9ef0-89ca5c98f219.png)

**Comment by XeniaWorontsova** [comment]
Закрыта, так как в дальнейшем будут создаваться задачи на каждый спринт
