### ISSUE TITLE
Реализовать макет стартовой страницы веб-портала

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#34]
GlobalStory #19 
Макет #25

**Comment by stasshtaub** [comment]
https://rayofhope-opensource.000webhostapp.com/

**Comment by YuriSilenok** [comment]
Заметка.
В In Progress перемащают когда приступил к задаче, а не когда готово к проверке.

**Comment by YuriSilenok** [comment]
Хотя, сама задач живет на 2 минуты больше

**Comment by YuriSilenok** [comment]
А где реализация по указанной ссылке?
![image](https://user-images.githubusercontent.com/14871471/61880830-425f9f80-aefe-11e9-8d19-aa15aadae263.png)

**Comment by stasshtaub** [comment]
![image](https://user-images.githubusercontent.com/47520675/61880975-8b175880-aefe-11e9-98d4-4bde0b44df9e.png)

**Comment by YuriSilenok** [comment]
Да, чистанул куки, появилось.

**Comment by YuriSilenok** [comment]
Ссылка на макет ведет к макету мобильного приложения

**Comment by YuriSilenok** [comment]
Когда Вы исправили в описании ошибку, об этом необходимо написать в комментарии. Что бы не думалось о том, что про исправление забыто

**Comment by KharlamovaAlexandra** [comment]
Одобрено
