### ISSUE TITLE
Реализовать макет вэб-страницы регистрации организации

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#35]
Epic #18 
GlobalStory #19 

Реализовать макет #23 и ограничения ввода #21

@stasshtaub Оцените вес задачи

**Comment by stasshtaub** [comment]
ИНН точно только по количеству цифр проверять?

**Comment by YuriSilenok** [comment]
Существуют еще какие-то правила?
Если приступили к задаче, перетените ее в инпрогрес по доске 
https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/projects/1

**Comment by stasshtaub** [comment]
https://www.google.com/search?q=контрольная+сумма+инн&oq=коньрольная+сумма+инн&aqs=chrome.1.69i57j0l3.5880j1j7&client=ms-android-xiaomi-rev1&sourceid=chrome-mobile&ie=UTF-8

https://www.nalog.ru/rn44/service/actual_inn_ul/

**Comment by YuriSilenok** [comment]
> [https://www.google.com/search?q=контрольная+сумма+инн&oq=коньрольная+сумма+инн&aqs=chrome.1.69i57j0l3.5880j1j7&client=ms-android-xiaomi-rev1&sourceid=chrome-mobile&ie=UTF-8](https://www.google.com/search?q=%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F+%D1%81%D1%83%D0%BC%D0%BC%D0%B0+%D0%B8%D0%BD%D0%BD&oq=%D0%BA%D0%BE%D0%BD%D1%8C%D1%80%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F+%D1%81%D1%83%D0%BC%D0%BC%D0%B0+%D0%B8%D0%BD%D0%BD&aqs=chrome.1.69i57j0l3.5880j1j7&client=ms-android-xiaomi-rev1&sourceid=chrome-mobile&ie=UTF-8)
> 
> https://www.nalog.ru/rn44/service/actual_inn_ul/

@Parallusion обратите внимание, в задаче #21 не указаны подобные проверки

@stasshtaub Вы молодец! Если у Вас есть замечания или вопросы в других тасках, не стесняйтесь их задавать. Пожалуйста, учтите эту [контрольную сумму](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE#%D0%9D%D0%BE%D0%BC%D0%B5%D1%80%D0%B0_%D0%98%D0%9D%D0%9D) при реализации макета

**Comment by stasshtaub** [comment]
https://rayofhope-opensource.000webhostapp.com/registration-organization/

**Comment by KharlamovaAlexandra** [comment]
Привет, @stasshtaub 

Увидела
Первые две с айфона просмотр, вторые с Firefox. 
Хочется узнать механизм проверки ИНН. 
Из замечаний форма не отчищается после того, как регистрация произошла. И я смогла зарегистрироваться когда поля названия и ИНН совпали. Не знаю что с этим сделать, но думаю это не нормально.

В остальном все хорошо, спасибо за работу. Мне нравится

![IMG_9552](https://user-images.githubusercontent.com/47320583/62049954-ffad0880-b218-11e9-9241-8b345586ee9a.PNG)
![IMG_9551](https://user-images.githubusercontent.com/47320583/62049955-ffad0880-b218-11e9-8ac0-7eb569c5b873.PNG)
![1](https://user-images.githubusercontent.com/47320583/62049970-076cad00-b219-11e9-912a-659e509334b5.PNG)
![2](https://user-images.githubusercontent.com/47320583/62050026-266b3f00-b219-11e9-8d41-586188507bc8.PNG)

С уважением,
Александра

**Comment by stasshtaub** [comment]
Поле с название никак не проверяется, там проверка только чтобы оно непустое было. Верстка съезжает щас везде, кроме мониторов 16:9, потом исправлю под остальные экраны.

ИНН проверяется вот в этом  [файле](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/files/3442700/validate_form.txt) (функция "validate_inn($inn)"), на хостинге он лежит в папке public_html/wp_admin/validate_form.php. Там же файл с разметкой для письма (confirmation_email_template.html).

Какие проверки добавлять для названия?

**Comment by KharlamovaAlexandra** [comment]
Хорошо что задумался о контрольных цифрах. 
На счет проверок сразу ответить не могу. Подниму задачу для Ильи, чтобы он сверился с документами РФ, на то какие названия допустимы

**Comment by stasshtaub** [comment]
проверь щас в firefox

**Comment by KharlamovaAlexandra** [comment]
Теперь все нормально. В Opere и Safari тоже

**Comment by YuriSilenok** [comment]
> Первые две с айфона просмотр, вторые с Firefox.
Хочется узнать механизм проверки ИНН.
Из замечаний форма не отчищается после того, как регистрация произошла. И я смогла зарегистрироваться когда поля названия и ИНН совпали. Не знаю что с этим сделать, но думаю это не нормально.

Пора подключать тестирование. Надо осбудить на митинге.

**Comment by YuriSilenok** [comment]
> public_html/wp_admin/validate_form.php

почему эти файлы размещены в папке wp_admin? ранее Вы указывали папку registration-organization.

**Comment by stasshtaub** [comment]
> > public_html/wp_admin/validate_form.php
> 
> почему эти файлы размещены в папке wp_admin? ранее Вы указывали папку registration-organization.

аякс запрос может работать только с файлами в этой папке

**Comment by YuriSilenok** [comment]
Знаете с чем это связано?

**Comment by stasshtaub** [comment]
Из-за настроек вордпресса, это нормально

**Comment by YuriSilenok** [comment]
Вордпресс ведь нам не нужен, может снесем его?

**Comment by stasshtaub** [comment]
Не нужен, но надо будет переписать файлы страниц сайта, которые щас сверстаны специально под вордпресс. Вечером сделаю

**Comment by stasshtaub** [comment]
#42

**Comment by KharlamovaAlexandra** [comment]
Я так понимаю задача выполнена и все связанные с ней вопросы решены?

**Comment by stasshtaub** [comment]
Да

**Comment by YuriSilenok** [comment]
Я бы ожидал следующий сценарий для Story
- Задача создана и назначена исполнителю
- задача выполнена и назначена проверяющему
- если к задаче есть вопросы, они заданы и назначена исполнителю
- задача выполнена и назначена проверяющему
- задача проверена и закрыта проверяющим

**Comment by KharlamovaAlexandra** [comment]
Одобрено
