### ISSUE TITLE
Структурировать каталог на гугл-диске

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#36]
Предложить способ структурирования

**Comment by YuriSilenok** [comment]
Предлагаю первый уровень каталогов разбить по командам.
![image](https://user-images.githubusercontent.com/14871471/61887278-fd416a80-af09-11e9-83a7-15c7bee44650.png)
Посмотри пожалуйста как остальное устроено

**Comment by KharlamovaAlexandra** [comment]
Привет, @YuriSilenok 
Не уверена что это очень удобно, человек новый\ не знающий, что происходит  может не понять что и где искать. Но для нас думаю пока вполне подойдет.
+ я ввела бы папку анализ, все сгружать в управление проектом наверно не очень удобно ( как минимум мне ). 
P.S.  Я не догадалась куда мне сгрузить шаблон письма

**Comment by YuriSilenok** [comment]
> Не уверена что это очень удобно, человек новый\ не знающий, что происходит может не понять что и где искать.

Для новых людей всегда проводится обзор проекта. В компаниях это испытательный срок.

**Comment by YuriSilenok** [comment]
> P.S. Я не догадалась куда мне сгрузить шаблон письма

![image](https://user-images.githubusercontent.com/14871471/62150611-28abc700-b307-11e9-9bfd-74e61c41cec0.png)
Я думаю шаблон должен лежать в спеке

**Comment by YuriSilenok** [comment]
> Плюсом я ввела бы папку анализ, все сгружать в управление проектом наверно не очень удобно ( как минимум мне ).

![image](https://user-images.githubusercontent.com/14871471/62151169-5f361180-b308-11e9-9263-3c6304b3faff.png)
Могу предложить переименовать эту папку

**Comment by KharlamovaAlexandra** [comment]
Хорошая идея, поддерживаю
