### ISSUE TITLE
Определить проверки для полей регистрации организации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#37]
Сверится с документами РФ и определить, какие названия допустимы для регистрации названия организации ( Скорее всего там предъявляются какие нибудь ограничения той службой которая это все в РФ регистрирует ). Чтобы обезопасить себя от ввода непонятной кучи символов.
Для ИНН используется проверка по контрольной сумме, нужно ли что  - то еще?
Какие пароли мы будем использовать?

Ответить в комментариях. Одобряет Александра и Юрий

Проблема возникла в ходе решения задачи #35

**Comment by YuriSilenok** [comment]
@KharlamovaAlexandra у нас есть специальная стори #21  которая которая содержит в себе все ограничения на данные. Думаю необходимо указать что посчле закрытия этой задачи, необходимо внести изменения в задачу #21.

**Comment by KharlamovaAlexandra** [comment]
Вопрос решен. Илья отпиши пожалуйста решение в комментарии и закрой задачу

**Comment by Parallusion** [comment]
Дополнительных проверок не будет, все остальные ограничения указаны в задаче #21 .
