### ISSUE TITLE
Разработать логотип для информационной площадки "Луч надежды"

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#4]
Прикрепить результат работы или ссылку на результат в комментариях. Указать с помощью чего было создано/как открыть.

**Comment by stasshtaub** [comment]
Лого в .png (картинка без фона): [ссылка на гугл-диск](https://drive.google.com/file/d/1-Hjnp1qmNPbpzfpOoiACwWEZ0OqXWkUU/view?usp=drivesdk)
Лого в .svg (вектор для верстки приложения): [ссылка на гугл-диск](https://drive.google.com/file/d/1-N87i6mBPd75D-0wD0BkYGriG8jGaZCz/view?usp=drivesdk)
Лого в .eps (вектор для любых бесплатных редакторов типа Inscape): [ссылка на гугл-диск](https://drive.google.com/file/d/1-LogVZP97LQKFmqjP2a8Q93BMqoNO9og/view?usp=drivesdk)
Исходный файл для Corel Draw x8: [ссылка на гугл-диск](https://drive.google.com/file/d/1-EO-58I6_SNKTggQ8K7Ks16P9cGl6kOX/view?usp=drivesdk)
