### ISSUE TITLE
Разработать план тестирования

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#40]
Я вроде что - то слышала чтобы сравнивать готовый сайт с макетом и ручное тестирование....

**Comment by YuriSilenok** [comment]
[Этот ](https://docs.google.com/spreadsheets/d/1QX80ipwa-VqxpP4v4vkhY62S_wfBev07Xq2Ys48WiyM/edit#gid=0) док предназначен для тестирования WEB

Если есть какие-то мысли по нему или непонимание того, как это устроено, сразу пишите.

@Parallusion ты как глава отдела тестирования посмотри обязательно посмотри на эту таблицу. 
Тебе ее нужно заполнить и создать подобную для Android

**Comment by KharlamovaAlexandra** [comment]
Задача мертва?

**Comment by Parallusion** [comment]
Задача не мертва, но чтобы её выполнять мне нужен человек, который работал  с приложением для того, чтобы объективно понимать как всё должно работать, какие баги есть и тд. Как я понимаю, это Даша, поэтому я предлагаю собраться за одним компьютером и на основании информации от Даши я буду делать сразу же анализ и вносить всё в таблицу.

**Comment by YuriSilenok** [comment]
Это не так работает.
Напомните мне что бы я на митинге рассказал как стори тестируется или давай Илья как-нибудь вместе созвонимся, я тебе расскажу.
Я когда-то начинал [шаблон для тестов под WEB](https://docs.google.com/spreadsheets/d/1QX80ipwa-VqxpP4v4vkhY62S_wfBev07Xq2Ys48WiyM/edit#gid=859627632) посмотри его

**Comment by YuriSilenok** [comment]
План есть
