### ISSUE TITLE
Проверить наличие макетов на диске

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#41]
Проверить наличие всех созданных макетов на диске ( соответственно в папках в которых они быть должны )

**Comment by YuriSilenok** [comment]
На текущий момент все макеты концентрируются в [этой ](https://drive.google.com/drive/folders/1rNL4IP_H9FMM4zQpNn8pG3jn-BJatV7D )папке

**Comment by stasshtaub** [comment]
Макеты на диске
