### ISSUE TITLE
Добавить проверку ИНН по базе фнс

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#42]
Проверить введённый инн на странице регистрации организации по базе фнс

**Comment by YuriSilenok** [comment]
Может стоит эту проверку реализовать не на фронтенде, а на бэкенде, иначе, злоумышленики смогут обходя гуевую проверку и просто засылать данные в нашу систему?

**Comment by stasshtaub** [comment]
Она на бэкэнде. Апи будет вот [этот](https://dadata.ru/api/find-party/), вечером привяжу к аякс-запросу на форме

**Comment by stasshtaub** [comment]
Добавил проверку. 

[Сервис](https://dadata.ru/api/find-party/#pricing) с API разрешает бесплатно обрабатывать до 10000 запросов в день. База на сервисе обновляется не позднее 3 дней после ее обновления на сайте фнс.

Чтобы не отправлять запросы зря, введенное число сначала проверяется по контрольной сумме на то, может ли оно вообще быть номером инн или нет (функция validate_inn($inn)). Если не может - всплывает подсказка "Некорректный инн"

Если эта проверка проходит, отправляется запрос для проверки по базе фнс (функция audit_check($INN)). В ответ приходит json, и если он будет пустым, значит такого ИНН нет в базе и он недействителен - на странице регистрации всплывает окно "Недействительный инн".

![2](https://user-images.githubusercontent.com/47520675/62294078-df788600-b472-11e9-8ce9-73c6628295d0.PNG)

![Снимок](https://user-images.githubusercontent.com/47520675/62294077-dedfef80-b472-11e9-99dc-42b2d4745f39.PNG)
