### ISSUE TITLE
Заблокирована установка релиз-версии для Android

### ISSUE THREAD

**Issue by ZhezlovaDaria** [Students-of-the-city-of-Kostroma/Ray-of-hope#43]
Сценарий воспроизведения:
1. Скачать релиз-APK
2. Начать установку
3. Увидеть сообщение "Приложение не установлено"

**Comment by YuriSilenok** [comment]
Если это баг, то где сценарий воспроизведения?

**Comment by YuriSilenok** [comment]
Какова его сложность и приоритет?

**Comment by KharlamovaAlexandra** [comment]
Вопрос решен?
