### ISSUE TITLE
Сделать макет страницы профиля организации для сайта

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#45]
Разработать макеты страницы профиля организации (со стороны других пользователей + личная страница организации) и страницы редактирования своего профиля

**Comment by stasshtaub** [comment]
Профиль организации со стороны других пользователей

![Профиль организации (со стороны других пользователей)](https://user-images.githubusercontent.com/47520675/62379304-5be09700-b54f-11e9-9df3-79596829e141.jpg)

**Comment by stasshtaub** [comment]
Дополнительное меню
![С выпадающим](https://user-images.githubusercontent.com/47520675/62380187-5d12c380-b551-11e9-9003-1f110043bd41.jpg)

**Comment by KharlamovaAlexandra** [comment]
Какую функцию выполняет находящийся в правом верхнем углу поиск? 

Где можно посмотреть описание данной организации и ее документы? ( Куда мне нажать как пользователю, чтобы подробнее узнать чем организация занимается? )

Если сравнивать с макетом для мобильного приложения, то на сайте можно разместить больше информации. Как я понимаю по задумке пользователь сразу может увидеть какие - то посты. Они принадлежат какой то категории или это самый последний пост любой категории который опубликовала организация?

Хотелось бы увидеть макет профиля организации с их взгляда. Так как сейчас мы работаем в направлении, что организация произвела регистрацию и попадает на страничку своего профиля. А регистрацию гражданина и список организаций ( через который он ее нашел ) мы еще не делали, так что вид с этой стороны потребуется чуть позже.

**Comment by stasshtaub** [comment]
Забыл про описание с доками

Поиск ищет организации, такой же но с фильтрами будет в списке организаций. Так-то можно убрать, но он там хорошо заполняет место.
Категория постов выбирается слева, по умолчанию отображаются посты сразу всех категорий. Сверху самый новый пост

С этого экрана проще начинать их делать - тут больше всего элементов. 
Как добавлю описание с доками, сделаю такой же со взгляда самой организации

**Comment by KharlamovaAlexandra** [comment]
Можно использовать для поиска нужного поста этой организации по ключевому слову, как в вк. Хотя тогда будет не очень логично его местоположение. В целом я не против поиска организаций, как и в списке, так что оставляй. 

Если в меню есть список любимых организаций, то как ее туда добавить? ( галочка, звездочка на профиле самой организации)

**Comment by stasshtaub** [comment]
добавлю, в приложении тоже вроде надо

**Comment by KharlamovaAlexandra** [comment]
Окей

**Comment by stasshtaub** [comment]
Личный профиль организации

![Личный профиль](https://user-images.githubusercontent.com/47520675/62425958-dc3a0000-b6e7-11e9-9310-0765a2054fb7.jpg)

**Comment by stasshtaub** [comment]
Редактирование профиля

![Редактирование профиля](https://user-images.githubusercontent.com/47520675/62425983-20c59b80-b6e8-11e9-8b23-432378a33789.jpg)

![Вид деятельности](https://user-images.githubusercontent.com/47520675/62425984-20c59b80-b6e8-11e9-9c57-6e1f808481c2.jpg)

![Выбор города](https://user-images.githubusercontent.com/47520675/62425985-20c59b80-b6e8-11e9-9296-075ee2834666.jpg)

**Comment by stasshtaub** [comment]
Вид со стороны других пользователей

![Со стороны других пользователей](https://user-images.githubusercontent.com/47520675/62426005-54082a80-b6e8-11e9-9b9f-a8c3ea9ed34f.jpg)

**Comment by KharlamovaAlexandra** [comment]
> 
> 
> Редактирование профиля
> 
> ![Редактирование профиля](https://user-images.githubusercontent.com/47520675/62425983-20c59b80-b6e8-11e9-8b23-432378a33789.jpg)
> 
> ![Вид деятельности](https://user-images.githubusercontent.com/47520675/62425984-20c59b80-b6e8-11e9-9c57-6e1f808481c2.jpg)
> 
> ![Выбор города](https://user-images.githubusercontent.com/47520675/62425985-20c59b80-b6e8-11e9-9296-075ee2834666.jpg)

При редактировании можно удалять документы?

**Comment by KharlamovaAlexandra** [comment]
Одобряю макеты

**Comment by stasshtaub** [comment]
На экране просмотра документа можно будет
