### ISSUE TITLE
Профиль организации в мобильном приложении под Android

### ISSUE THREAD

**Issue by ZhezlovaDaria** [Students-of-the-city-of-Kostroma/Ray-of-hope#48]
Epic #74

Я как представитель благотворительной организации хочу иметь возможность просматривать свой профиль с мобильной версии информационной площадки

[макет](https://drive.google.com/drive/u/0/folders/1Pz38S9zhqnESQdTf-JZQdCa5ni7Dr77E)

Цвет фона должен быть белым

В верху страницы должно быть меню [по утвержденными критериям](https://docs.google.com/document/d/1fDVUJFGRfAm5C-G3VlOjThgFCoTHOi1LUZlpstPbpMs/edit#)

Должно отображаться фото организации - круглое  с права

Название организцации с лева от фото в верхнем регистре одним из допустимых цветов

Город и тип  организации под названием в одном из допустимых цветов

Описание организации под написать  в виде блока с закругленными краями которое можно раскрыть (по нажатию на надпись "больше...") если текста внутри много ( по умолчанию отображать три строки )

Контакты организации состоящие из: адреса, телефона находятся под описанием
ниже
Заголовок "документы организации:"  в одном из утвержденных цветов
под ним
Документы одной строкой в виде прямоугольников с закругленным краями на которых отображается главная страница самого документа ( можно скролить в право в лево )

Под основной информацией страницы будет кнопка синего утвержденного цвета с закругленными краями и белым текстом "Посмотреть записи организации" при нажатии на которую будут отображаться посты всех типов в порядке их публикации ( до этого посты не видно )

Ниже должно быть три кнопки ( нужды, мероприятия, события в данном порядке) кнопки с закругленными краями синего утвержденного цвета с белым текстом

Во втором спринте не показывать на макетах посты и так же не реализовывать их

Размещение элементов на странице, используемые размеры и шрифты на усмотрение дизайнера

Создать задачу на создание макета
Создать задачу на реализацию макета
В каждой задаче пометить эпики 74 и стори 48

**Comment by YuriSilenok** [comment]
А действительно @ZhezlovaDaria почему эта задачу по доске таскает @KharlamovaAlexandra ?

**Comment by ZhezlovaDaria** [comment]
@YuriSilenok , извиняюсь, как-то упустила этот момент. Исправлюсь.

**Comment by KharlamovaAlexandra** [comment]
Задача ведь еще в процессе?

**Comment by ZhezlovaDaria** [comment]
@KharlamovaAlexandra , да.

**Comment by KharlamovaAlexandra** [comment]
Состояние задачи?

**Comment by YuriSilenok** [comment]
Дарья, ты успеваешь реавлизовать эту задачу до конца спринта?

**Comment by ZhezlovaDaria** [comment]
@YuriSilenok Предварительные макеты есть, позже, как и говорили на планировании, можно поднять баги.
Функциональность планирую реализовывать в рамках уже другой задачи.

**Comment by KharlamovaAlexandra** [comment]
Значит надо закрывать задачу в таком случае

**Comment by KharlamovaAlexandra** [comment]
Состояние задачи?

**Comment by KharlamovaAlexandra** [comment]
Что с задачей?
