### ISSUE TITLE
Реализовать макет страницы редактирования профиля организации

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#49]
Epic #74 
Макет #45 
Добавить в письмо ссылку подтверждения почты. После перехода по ссылке аккаунт активируется и пользователь перенаправляется на редактирование профиля. 
По прямой ссылке, если пользователь не авторизован, страница редактирования недоступна

**Comment by KharlamovaAlexandra** [comment]
За счет чего рейтинг такой высокий?

**Comment by stasshtaub** [comment]
какой рейтинг

**Comment by KharlamovaAlexandra** [comment]
021
Просто большие задачи, это не очень хорошо
Поэтому интересно узнать важные и сложные моменты этой задачи

**Comment by stasshtaub** [comment]
надо наполнить базу данных таблицами для картинок аватаров и документов, сделать каталоги на хостинге где будут храниться эти картинки, добавить апи с базой городов для подсказок при вводе города

**Comment by YuriSilenok** [comment]
> надо наполнить базу данных таблицами для картинок аватаров и документов, сделать каталоги на хостинге где будут храниться эти картинки, добавить апи с базой городов для подсказок при вводе города

Мы проседаем в этом вопросе, по идее этим Денис должен заниматься.
Вы не в курсе, курсовики по УД на 4 курсе есть?
Если такое есть, возможно стоит попросить Нину Олеговну выделить человека который нам БД спроектирует и сразу ее реализует.

**Comment by stasshtaub** [comment]
Страница готова. Чтобы зайти, зарегистрируйтесь на свою почту. После регистрации добавляется запись о пользователе в бд с нулем в поле status (статус активации). На почту придет ссылка для подтверждения - после перехода пользователь активируется (1 в status) и откроется страница редактирования профиля. 
Если открыть ссылку (https://rayofhope-opensource.000webhostapp.com/pages/edit_org.php) без подтверждения почты - будет редирект на страницу регистрации (когда будет готова страница авторизации, перенаправлять будет туда).

Подсказки с вводом городов работают через перебор таблицы городов и регионов в нашей бд.
Аватар сохраняется на хостинге в папке user_data/avatar, имя картинки аватара = id пользователя в бд.
Аватар сохраняется на хостинге в папке user_data/docs/ в папке с id организации.

Пока что при загрузке аватара не проверяется тип файла (можно загрузить текст например). И если загрузить одно и то же изображение в документы два раза и нажать сохранить - документ сохранится только один раз (файлы с одинаковым именем перезаписываются на хостинге). Потом это исправлю. Плюс сообщения об ошибках и об успешной загрузке выходят через стандартные alert'ы - потом переделаю на всплывающие сообщения как на странице регистрации

**Comment by KharlamovaAlexandra** [comment]
Привет 
В названии организации я могу писать только заглавными буквами? Я попыталась вбить названии организации "Право на жизнь", выскочила ошибка
![10](https://user-images.githubusercontent.com/47320583/63093901-84b15500-bf6f-11e9-92cb-937f7b680624.PNG)
Я так понимаю само письмо подтверждения еще не отсылается, ну мне точно ничего не пришло на почту. Но сообщение о подтверждении адреса появилось.
Как можно протестить кабинет пользователя? 

Спасибо

**Comment by stasshtaub** [comment]
Твоя запись добавилась в бд, письмо должно скоро придти, из-за бесплатного хостинга они отправляться могут долго, иногда в спам попадали.
Щас можешь првоерить через эту ссылку (такая же придёт в письме): https://rayofhope-opensource.000webhostapp.com/confirm_org.php?email=sdarapana31@mail.ru@gmail.com&hash=67ec669a49deaa7a39977a7a89c9564e

Название вечером посмотрю, там в проверке че-то не так с русскими буквами

**Comment by KharlamovaAlexandra** [comment]
Через ссылку открывается так же окно регистрации. Пока кнопка входа не будет готова, проверить не получится ( не страшно ). Как придет письмо на почту, сообщу

**Comment by stasshtaub** [comment]
Почту не ту написал, щас нормально

**Comment by YuriSilenok** [comment]
> Потом это исправлю.

Может баг поднять, что бы не забыть?

**Comment by KharlamovaAlexandra** [comment]
Какие форматы поддерживаются? 
![Снимок экрана 2019-08-16 в 11 58 20](https://user-images.githubusercontent.com/47320583/63156410-512d0400-c01d-11e9-95a6-0f32eb0c4ecc.png)
И в safari:
![Снимок экрана 2019-08-16 в 11 59 04](https://user-images.githubusercontent.com/47320583/63156480-6c980f00-c01d-11e9-9b8b-9d15aa155987.png)
Я ожидала что я перейду на страницу организации нажав на картинку
![Снимок экрана 2019-08-16 в 12 01 09](https://user-images.githubusercontent.com/47320583/63156575-a537e880-c01d-11e9-9135-263047fe22ba.png)
и на главную
![Снимок экрана 2019-08-16 в 12 01 24](https://user-images.githubusercontent.com/47320583/63156583-acf78d00-c01d-11e9-8ca4-cfb22c901d13.png)
Остальное устраивает

**Comment by stasshtaub** [comment]
Я под документами понимал их сканы (картинки). Что должно туда загружаться, doc и pdf?
Аватар в шапке будет вести на страницу организации, но её ещё сделать надо.
Логотип по идее будет дублировать кнопку "лента" и открывать ленту, или сделать перевод на главную?

Какой браузер на первом скрине? В одной строке списка доков должны помещаться 3 прямоугольника

**Comment by KharlamovaAlexandra** [comment]
> Что должно туда загружаться, doc и pdf?

PDF, DOC, JPEG ( было бы не плохо ). Ну и подсказку о загружаемых форматах.

> Логотип по идее будет дублировать кнопку "лента" и открывать ленту, или сделать перевод на главную? 

Пусть будет лента

> Какой браузер на первом скрине? В одной строке списка доков должны помещаться 3 прямоугольника

Все в safari

**Comment by YuriSilenok** [comment]
Стас, пожалуйста, добавь метку Story

**Comment by stasshtaub** [comment]
Добавил проверку файлов, для доков: jpg, pdf, docx, для аватара: jpg. Документы docx загружаться дольше остальных, потому что превью для них (перевод в картинку) делается на сервере.
Файлы сначала (после выбора файлов) проверяются в браузере у клиента. После нажатия "сохранить" проверяются на сервере.

Проверь вид в сафари

**Comment by KharlamovaAlexandra** [comment]
С отображение в Safari теперь все хорошо

Попробовала подгрузить docx. Сначала показывает, что все норм ( второй документ ) 
![Снимок экрана 2019-08-31 в 19 11 23](https://user-images.githubusercontent.com/47320583/64066514-85124700-cc23-11e9-9f36-e744578007ae.png)
Затем я обновляю страницу и все пропадает
![Снимок экрана 2019-08-31 в 19 11 34](https://user-images.githubusercontent.com/47320583/64066522-a1ae7f00-cc23-11e9-9e7b-87ef18a3c40d.png)
Попробовала загрузить jpg - ситуация аналогично

**Comment by stasshtaub** [comment]
Почисти кэш браузера, ctrl+f5 или для сафари: https://www.google.com/amp/s/lifehacker.ru/clearing-safari-cache/amp/

**Comment by stasshtaub** [comment]
Ты кнопку сохранить нажимала? Доки загружаются на сервер только после этого

**Comment by KharlamovaAlexandra** [comment]
Теперь он пишет так  и происходит полный ужас. Но думаю это проблемы Safari. Я позже попробую все сделать через нормальный браузер

![Снимок экрана 2019-08-31 в 19 34 26](https://user-images.githubusercontent.com/47320583/64066753-5f3a7180-cc26-11e9-9869-60233eefcad0.png)

**Comment by YuriSilenok** [comment]
> С отображение в Safari теперь все хорошо
> 
> Попробовала подгрузить docx. Сначала показывает, что все норм ( второй документ )
> ![Снимок экрана 2019-08-31 в 19 11 23](https://user-images.githubusercontent.com/47320583/64066514-85124700-cc23-11e9-9f36-e744578007ae.png)
> Затем я обновляю страницу и все пропадает
> ![Снимок экрана 2019-08-31 в 19 11 34](https://user-images.githubusercontent.com/47320583/64066522-a1ae7f00-cc23-11e9-9e7b-87ef18a3c40d.png)
> Попробовала загрузить jpg - ситуация аналогично

У нас где нибудь написано под какие будка нужно верстать?

**Comment by stasshtaub** [comment]
Под все надо 
Ошибка с повреждёнными файлами была не из-за сафари, исправил проверку, щас нормально должно работать

**Comment by YuriSilenok** [comment]
> Под все надо
> Ошибка с повреждёнными файлами была не из-за сафари, исправил проверку, щас нормально должно работать

 это звучит как достигнуть исчерпывающее тестирование.
Даже если вы обладаете набором каких-то браузеров Мне нужно забывать о том что есть версия этих браузеров А ещё не нужно забывать что есть статистика по процентам использования этих браузеров И нецелесообразно поддерживать браузеры и версии браузеров которые не используются
@KharlamovaAlexandra Что ты думаешь по этому поводу? Должны ли мы проанализировать этот вопрос Или мы будем выдумывать каких браузерах это тестировать?

**Comment by KharlamovaAlexandra** [comment]
Надо составить список устройств и их версий в которых мы будем поддерживать работу платформы и для веба и для анроида

**Comment by KharlamovaAlexandra** [comment]
Я вот поняла, что загружать документы мы можем, а удалять нет

**Comment by KharlamovaAlexandra** [comment]
Но наверно на это уже нужно поднять баг, а задачу закрыть

**Comment by stasshtaub** [comment]
Для удаления либо будет кнопка в окне просмотра документа (если нужно такое окно, а не просмотр через час браузер в новой вкладке), либо могу крестик какой-нибудь сделать каждому доку, пока специально не делал удаление

**Comment by YuriSilenok** [comment]
Если эту функциональность ни кто не просил, тогда нужно сделать новую стори для этого, которая попадет в бэклог проекта, а не в текущий спринт
