### ISSUE TITLE
Разработать макеты части экранов для мобильного приложения

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#5]
Разработать макеты для экранов указанных на изображении. Прикрепить результат работы или ссылку на результат в комментариях. Указать с помощью чего было создано/как открыть. 
![изображение](https://user-images.githubusercontent.com/47320583/60528900-1e91ab00-9cfe-11e9-875d-01c5d5988782.png)

**Comment by stasshtaub** [comment]
Экраны:
- [Экран загрузки](https://drive.google.com/file/d/1zUI0-J2Edt6UXFG95vHHgE-9iAnVyc9a/view)
- [Нет подключения к сети](https://drive.google.com/file/d/1LPkFT_V6PfOTYvq9KJrm90q0h5MwXGyu/view?usp=sharing)
- [Экран выбора роли](https://drive.google.com/file/d/1JV4QB7OV45a24nUzLIZ-pG1uYtu_xTWj/view?usp=sharing)
  - [Экран подсказки для гражданина](https://drive.google.com/file/d/1V7xaaC56-2HxZanFvB1Sci5INYWEMq6U/view?usp=sharing)
  - [Экран подсказки для организации](https://drive.google.com/file/d/1KGZy-ofzDC3mP9iI8JDGJ9HVaI9RAy9U/view?usp=sharing)
- [Экран входа гражданина](https://drive.google.com/file/d/19fzYMa99Wulc7qAYW7nbvCeY9ekAcoKy/view?usp=sharing)
- [Экран входа организации](https://drive.google.com/file/d/1bh79zIi6ejbNR2x0fIUYYEYLBkY9IH7h/view?usp=sharing)

[Демка со всеми экранами и переходами между ними](https://xd.adobe.com/view/a05ccc9f-f7dd-4140-71b4-f39fb0b6292e-d66d/) (обновляется без изменения ссылки)
Для вёрстки приложения: [Страница с размерами, цветами и стилями всех элементов и экранов](https://xd.adobe.com/spec/0cba9ba7-9e70-4e08-747e-7ee9612e5dd1-7a8b/)
На странице для верстки экраны прокручиваются стрелками клавиатуры (лучше уменьшить масштаб справа вверху)

Дизайн создаётся в Adobe XD (работает только на WIndows 10): [ссылка на скачивание](https://www.adobe.com/ru/products/xd.html)
Исходный файл в Adobe XD: [ссылка](https://drive.google.com/file/d/1-7RpUmXC46fwcRsyiSpaVN24tBmDlr2h/view?usp=sharing)
