### ISSUE TITLE
Реализовать подвал страницы "О нас" для WEB

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#50]
Epic #51 
GlobalStory #52

На сайте реализовать раздел "О  нас" согласно макетам

**Comment by YuriSilenok** [comment]
эгегей, epic, story, globalStory это взаимоисключающие метки

**Comment by YuriSilenok** [comment]
и это два стори, одно на мобилку, другое для вэба, не видел еще, есть или нет, но нужен глобалСтори в котором будет прописана инфа которая будет в разделе о нас.

**Comment by KharlamovaAlexandra** [comment]
Описание раздела готово

**Comment by YuriSilenok** [comment]
@KharlamovaAlexandra какие критерии приемки для этой стори будут?
@Parallusion мы плавно начнем погружаться в правильное тестирование стори, ваши тесты должны ориентироваться в первую очередь на критерии приемки, они будут составлять больший приоритет. Потом ориентируетесь на общее описание стори. 

Стори закрывается после того как она исполнена.
После закрытия стори, открывается таск на тестирование стори ссылкой на стори.
Ссылка обязательна нужно что бы понять, протестировано стори или нет.

**Comment by KharlamovaAlexandra** [comment]
Критерии приемки:
1. Соответствие макету по расположению объектов, стилистике и т.д ( без учета, что съехало на 3 миллиметра )
2. Соответствие текста на странице обговоренному заранее тексту в задаче #52 
3. Должно адекватно отображаться на мобильных устройствах 
4. Нормально смотреться в браузерах Google Chrome, Opera, Firefox, Safari ( версии указывать не буду, но в последних на 19.08.2019 точно )
5. Все идеи добавленные в работу должны быть обговорены и одобрены отдельно ( как минимум мы должны знать, что они существуют ) 

Думаю технические требования добавлять не стоит такие как скорость отклика  используемые технологии и т.д

**Comment by KharlamovaAlexandra** [comment]
@YuriSilenok Кто будет осуществлять приемку?

**Comment by YuriSilenok** [comment]
Процесс следующий,

1. Стори пилиться разрабами по критериям. Текущий спринт. 
2. Открываются таск и на тестирование, тестеры проверяют что все норм. Спринт +1
3. Если критикалов по стори нет, то это стори включается в демо. Конец спринта+1

Ответ на вопрос, команда тестирования проверяет что критерии выполнены

**Comment by stasshtaub** [comment]
Страница готова. Открывается через кнопку "о нас" с [главной страницы](https://rayofhope-opensource.000webhostapp.com/) и со [страницы регистрации](https://rayofhope-opensource.000webhostapp.com/registration/org), или через скролл на главной.

[Макет](https://drive.google.com/file/d/1qTY5tYxRMZCStfZpj_ZEZlBlW4SRcGPF/view?usp=drivesdk)

**Comment by KharlamovaAlexandra** [comment]
На мой взгляд все хорошо. @Parallusion забирай на тестирование
