### ISSUE TITLE
Раздел "О нас"

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#51]
Я как пользователь системы должен иметь возможность перейти в раздел  "О нас" и прочитать следующий текст.

> “Люди хотят, но не могут помочь”
> 
> Из этой фразы родилось наше мобильное приложение, а затем и сайт. 
> 
> Наша команда состоит из людей, которые хотят, чтобы эта фраза стала ложью. 
> 
> Мы реализуем информационную благотворительную площадку,  главная цель которой, сделать проще и понятней процесс помощи нуждающимся.
> 
> Мы создаем информационную платформу объединяющую неравнодушных людей готовых помочь и  людей которым эта помощь нужна.  
> 
> Площадка ориентированная под нужды благотворительных организаций…
>  
> Площадка на которой граждане увидят информацию в одном месте и смогут помочь просто нажав на кнопку…
> 
> Площадка, чтобы творить добро!
> 
> Площадка, которую освещает луч надежды!

Какие шрифты и размеры должны быть для этого?

**Comment by YuriSilenok** [comment]
Похоже на эпик, и 50 таск будет создаваться в рамках этого эпика

**Comment by YuriSilenok** [comment]
А нет, вижу что все правильно

**Comment by YuriSilenok** [comment]
Тогда мне непонятно что должно быть сделано в рамках этой задачи

**Comment by YuriSilenok** [comment]
Хотя нет, это все же эпик

**Comment by KharlamovaAlexandra** [comment]
https://docs.google.com/document/d/17-jGFL2WxEliW1knnKH9HulV5AB7vtKU1vT-L0pwJKs/edit

**Comment by YuriSilenok** [comment]
Саша, посмотри пожалуйста, я поправил описание этого эпика

**Comment by KharlamovaAlexandra** [comment]
А кто должен решать какие должны быть шрифты?

**Comment by YuriSilenok** [comment]
Я бы сказал что если у заказчика нет каких-либо предпочтений, то дизайнер предлагает собственное решение и если оно подходит, то это должно быть зафиксирован в тори скорее всего. Если предпочтения есть, то дается описание шрифта или точное его название в эпике.

**Comment by KharlamovaAlexandra** [comment]
Данный эпики завершен. Обе story уходят в тестирование
