### ISSUE TITLE
Реализовать раздел "О нас" в  Android приложении

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/Ray-of-hope#53]
Epic #51

**Comment by YuriSilenok** [comment]
Эту задачи стоит перевесить на Дарью, после того как будет подготовлены сведения #52

**Comment by KharlamovaAlexandra** [comment]
Критерии приемки:

1.Соответствие макету по расположению объектов, стилистике и т.д ( без учета, что съехало на 3 миллиметра )
2.Соответствие текста на странице обговоренному заранее тексту в задаче #52
3.Должно адекватно отображаться на мобильных устройствах с операционной системой Android версии 4.2 и выше
4.Все идеи добавленные в работу должны быть обговорены и одобрены отдельно ( как минимум мы должны знать, что они существуют )

**Comment by YuriSilenok** [comment]
https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/50#issuecomment-524546876

**Comment by KharlamovaAlexandra** [comment]
Каково состояние задачи?

**Comment by YuriSilenok** [comment]
> Каково состояние задачи?

Дарья, ты успеваешь закончить до конца спринта эту задачу?

**Comment by ZhezlovaDaria** [comment]
@YuriSilenok, эта задача готова. В данный момент, страница открывается через боковое меню. Нужно протестировать страничку

**Comment by YuriSilenok** [comment]
Тестирование это отдельные таски и отдельная команда
Если задача готова и релиз состоялся, можно закрывать эту задачу

**Comment by KharlamovaAlexandra** [comment]
Если задачу закрыть, то как Илья поймет, что ее надо тестировать?

**Comment by YuriSilenok** [comment]
По фильтру, если стори закрыта, значит готова, значит можно тестить.
Стори живут отдельно от задач тестирования, стори это задача на разработку.
Но я еще раз завтра уточню как делают это в Лондонские разработчики.
