### ISSUE TITLE
Создать новую диаграмму классов

### ISSUE THREAD

**Issue by ZhezlovaDaria** [Students-of-the-city-of-Kostroma/Ray-of-hope#55]
Story: #8 
[Старая диаграмма классов](https://vk.com/doc440009443_513450642?hash=044164445954860b97&dl=90678f775145743e33)

Опираясь на продуктовое виденье, определить требуемые классы согласно паттерну MVC.

**Comment by KharlamovaAlexandra** [comment]
https://www.draw.io/?state=%7B%22folderId%22:%2211j8QaS7pbCQ7dhZu4FYe9AFvyZLymCcw%22,%22action%22:%22create%22,%22userId%22:%22113328235892001138746%22%7D#G1GDXiEWnW122p1VEPSeW_jopJT2UumjPH - Новая диаграмма. В процессе разработки

**Comment by YuriSilenok** [comment]
Пожалуйста, когда диаграмма будет готова, нужно будет созвониться для её обсуждения

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/66338236-62bdc880-e949-11e9-8a2c-6822f337ccc9.png)
Немного о нотации, с Артемом Руфимовичем вопрос того как отображать свойства решился.
Если свойство с частями get и set, то мы описываем в два метода типа getKey() : string и setKey(value : string)

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/66338584-145cf980-e94a-11e9-850d-3567a05e1687.png)

Должен ли драйвер принимать на вход экземпляр модели (модель содержит проверки на данные)

Должен ли драйвер вызываться контроллером?

**Comment by KharlamovaAlexandra** [comment]
@Svyat935 @ZhezlovaDaria Что тут происходит?
