### ISSUE TITLE
Узнать про бесплатные лицензии для ВУЗа

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#56]
Если вы студент либо преподаватель, и образовательная лицензия требуется вам для личного использования, вам нужно оформить индивидуальную студенческую подписку. Для этого необходим адрес электронной почты в домене университета или действительная ISIC карта. Если у вас нет возможности оформить личную подписку, заинтересуйте вашего преподавателя в том, чтобы он подал заявку на аудиторные лицензии для использования в вашем учебном заведении.

Если образовательные лицензии требуются для централизованного распределения в школах/ВУЗах, где учащиеся не имеют возможности подать индивидуальные заявки на студенческие лицензии, либо для установки ПО на компьютеры в компьютерных классах/аудиториях, преподавателю или сотруднику учебного заведения необходимо оформить заявку на аудиторные (classroom) лицензии. Аудиторные лицензии можно выдавать поимённо студентам и коллегам (через ссылку-приглашение) либо распределять через сервер лицензий по локальной сети в компьютерных классах учебного заведения.

**Comment by KharlamovaAlexandra** [comment]
https://jetbrains.ru/students/classroom-licenses/free-classroom-licenses/

**Comment by YuriSilenok** [comment]
Займусь этим в 28.08, так как там триалы на 14 дней.

**Comment by YuriSilenok** [comment]
понял что я не могу доказать что я работаю в ВУЗе, буду просить Людмилу Юрьевну от своего имени зарегистрироваться.

**Comment by YuriSilenok** [comment]
Людмила Юрьевна согласилась помочь с регистрацией и получением бесплатной лицензии на этом портале.

**Comment by YuriSilenok** [comment]
Людмила Юрьевна отправила заявку на создание электронных адресов в домене института, это значит что мы все сможем получить доступ к ресурсам.

**Comment by KharlamovaAlexandra** [comment]
Когда? 
вот в чем вопрос

**Comment by YuriSilenok** [comment]
Как почту сделают

**Comment by KharlamovaAlexandra** [comment]
Почты получены но не для всех? Что делаем?

**Comment by YuriSilenok** [comment]
Пойду зарегаюсь  на портале, сначала разберусь как и что мы там можем использовать, потом сделаю презентацию с котиками

**Comment by KharlamovaAlexandra** [comment]
Хорошо. Задачу можно закрывать?

**Comment by YuriSilenok** [comment]
@KharlamovaAlexandra привет, посмотри пожалуйста, Людмила Юрьевна предоставила [этот](https://docs.google.com/spreadsheets/d/12hvO8rgVsn8gYUHEo5Hx7TZuYHw7A2vhTGTjnyd8aw4/edit?usp=sharing) документ, но я не могу сообразить, как из этого получить почту в домене КГУ?

**Comment by KharlamovaAlexandra** [comment]
Все просто, только кажется тут есть не все члены команды

**Comment by KharlamovaAlexandra** [comment]
Конкретно нет Ксюши

**Comment by YuriSilenok** [comment]
Там и меня нет, ЛЮ рассказала как можно авторизоваться на сайте через это

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/66418886-bb559a00-ea0b-11e9-90f3-eef6ad2ccf6a.png)
Неудача

**Comment by YuriSilenok** [comment]
Написал скрипт который проверил все электорнные адреса предолставленные ЛЮ/
[Результат](https://docs.google.com/spreadsheets/d/1ThxEVRoW3hZB7h4mb1fWCNpemATX1ZvURo4B7dWtiQk/edit#gid=244543142) фатальный, ни по одному адресу войти не удалось

**Comment by KharlamovaAlexandra** [comment]
Однозначно что - то не так, ведь мой рабочий

**Comment by YuriSilenok** [comment]
я заметил что в присланной таблице пароль отличается от того, что прислала ЛЮ.
Второй символ i и j
Сейчас перезапущу скрипт с другим паролем

**Comment by YuriSilenok** [comment]
Создал скрам проект.
Подготовить обзорную презентацию #118
