### ISSUE TITLE
Разработать макеты для экрана "Забыли пароль" под мобильное придожение 

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#57]
Экран для восстановления пароля с помощью почты 
Экран для введения нового пароля ( когда перешли по ссылке с почты )
Данные экраны будут одинаковы как для гражданина, так и для организации
Поставить сложность задаче

**Comment by stasshtaub** [comment]
Эти макеты есть на [диске](https://drive.google.com/folderview?id=1_S5rcxmu67aeCa62qntxamD2qSGFeiiJ)
Старый пароль сразу отправляется на почту, если введённая совпадает с той на которую регистрировались. Делать с изменением пароля?

Все сделанные экраны для приложения отмечены галочкой [здесь](https://docs.google.com/document/d/1j9kxQ0BHKyfl03hjhXEnlzoGFeNPj4PTshlRt5S41Bo/edit?usp=drivesdk)

**Comment by KharlamovaAlexandra** [comment]
> Старый пароль сразу отправляется на почту

Этот вопрос требует обсуждения. На мой взгляд не очень надежно. 
И так же, думаю где - то в настройках или в редактировании профиля должна быть добавлена возможность обновления пароля.
Пока задачу не закрывай, но и изменений не делай. Мы вынесем это в обсуждения

**Comment by stasshtaub** [comment]
@KharlamovaAlexandra что решили?

**Comment by KharlamovaAlexandra** [comment]
Не будем менять. Пароль будет высылаться на почту после ее введения, как на макетах. В настройках появится возможность изменения пароля
