### ISSUE TITLE
Не отображен переход из ... в "О нас"

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#58]
В макетах для мобильного приложения из ... нет перехода на экран "О нас"

https://drive.google.com/drive/u/0/folders/1XbP9ZvoDuseL86tyvc696k-HxPJeYdzH

Поставить сложность задаче

**Comment by YuriSilenok** [comment]
Есть очень хорошее правило для описания багов, представьте что тот, кто будет читать этот баг, ни разу не видел приложение и не знает о нем ничего.

Я бы ожидал увидеть какую-то навигацию по меню, скрины экрана прям в баге.
Может быть стрелкой показать на скрине что не так.

**Comment by KharlamovaAlexandra** [comment]
В ходе работы переход к разделу о нас был обнаружен на [экране выбора роли ](https://drive.google.com/drive/u/0/folders/1CIgDkKWOMq0b2v9B2n9Dm9d0wQb0YDCT)
Мне кажется это неправильным. Пользователь вряд ли захочет узнавать о деятельности платформы ( команды ) на этапе выбора роли. Он либо захочет это узнать из описания приложения в плей маркете, либо уже когда нибудь потом пользуясь приложением уже год. Мне кажется логичным перенести это в "..." в самом приложении.

**Comment by YuriSilenok** [comment]
> был обнаружен на [экране выбора роли ](https://drive.google.com/drive/u/0/folders/1CIgDkKWOMq0b2v9B2n9Dm9d0wQb0YDCT)

Эта ссылка ведет не на экран, а на папку с тремя экранами

Описание не живет отдельно от комментариев, если по какой-то причине получется что описание неверное, то в комменатрии указываептся что я изменил описание задачи/бага/конституции и при этом меняется описание. всегда есть возможность посмотреть историю изменений.

[Статья](https://habr.com/ru/company/docsvision/blog/264163/) для тех, кто не помнит как заводить баги

**Comment by YuriSilenok** [comment]
@Parallusion Пожалуйста, приведи в соответствие с требованиями к багу этот баг

**Comment by stasshtaub** [comment]
исправлено в #93

**Comment by YuriSilenok** [comment]
@stasshtaub баги закрываются тестировщиками

**Comment by YuriSilenok** [comment]
Указал веху в текущий спринт

**Comment by KharlamovaAlexandra** [comment]
Баг когда нибудь будет закрыт?

**Comment by KharlamovaAlexandra** [comment]
@Parallusion  @MoL4okkk что с задачей?

**Comment by YuriSilenok** [comment]
Выполнить действия аналогично [этому](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/109#issuecomment-546580018) комментарию

**Comment by MoL4okkk** [comment]
Баг не воспроизводится в версии [макета](https://drive.google.com/file/d/1G2JtnQOVVhanWD0kSWd1IeVsZQCBym91/view) от 1 октября 2019 года и более поздних

**Comment by YuriSilenok** [comment]
> Баг не воспроизводится в версии [макета](https://drive.google.com/file/d/1G2JtnQOVVhanWD0kSWd1IeVsZQCBym91/view) от 1 октября 2019 года и более поздних

Нужно указывать версию
