### ISSUE TITLE
Обсуждение действий с паролем

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#59]
В ходе обсуждения задачи #57  возник вопрос о том, как восстанавливать пароль пользователям. А так же о его изменении в течении использования аккаунтов

**Comment by YuriSilenok** [comment]
- ссылкой на почту, нужен шаблон письма

**Comment by YuriSilenok** [comment]
ох, я понял что обсуждали, наших пользователей в раз заспамят конкуренты.
Такое можно делать, но с хорошими ограничениями, что такую операцию можно делать раз в 24 часа.

С одной стороны можно будет генерить надежные пароли, с другой стороны их будут чаще менять, что тоже даст дополнительную защиту.

**Comment by KharlamovaAlexandra** [comment]
Стоит ли нам вообще генерировать пароли? Может мы будем отсылать на почту пользователю письмо с ссылкой, перейдя по которой он переходит на страницу, где сам должен придумать новый пароль. Такая система используется во многих интернет магазинах и я встречаю ее чаще, нежели чем система сама генерирует неудобный/непонятный для пользователя новый пароль

**Comment by YuriSilenok** [comment]
С точки зрения пользователя, да, это не удобно.

**Comment by YuriSilenok** [comment]
Любое решение которое будет принято, будет сформировано в виде отдельного спринта, в котором необходимо указать какой другой спринт он исправляет.

**Comment by YuriSilenok** [comment]
Предлагаю пойти по классической схеме
По ссылке отосланную на почту пользователь попадает на страницу смены пароля, где сам его придумывает, при это он должен соответствовать требованиям предъявляемые к паролю на странице регистрацции + новый пароль не должен совпадать тремя последними паролями.

**Comment by KharlamovaAlexandra** [comment]
поддерживаю
