### ISSUE TITLE
Анализ рынка мобильных платформ и на его сонове рекомендовать платформу для разработки мобильного приложения

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#6]
Произвести анализ ситуации на рынке и с учетом потребностей информационной площадки "Луч надежды"  произвести выбор операционной системы, для которой будет оптимально разрабатывать мобильное приложение. Результат работы приложить в комментария в виде ссылки на гугл документ.

**Comment by Parallusion** [comment]
[Результат анализа](https://docs.google.com/document/d/1Jic1_8XqMCGhRxfsttlzc-ovCFftcLq-aW-ukaghsUk/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
Думаю нужно перевесить задачу на @KharlamovaAlexandra это будет значить что Александре нужно будет ознакомиться с результатами работы.

**Comment by KharlamovaAlexandra** [comment]
Ознакомлена
