### ISSUE TITLE
Что возвращает бд?

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#60]
Story #8 
В ходе выполнения задачи #55 возник вопрос:
Что приходит из базы данных? 
Какой тип данных которые она отдает при обращении к ней?( когда мы не указываем что мы хотим получить, а просто есть желание узнать работает ли база вообще, при запуске мобильного приложения)
Нужно ли нам проверять что приходит из базы данных?
Может ли придти из базы данных информация, которая может навредить приложению?
Моет быть это вообще обработает все php или что - то на пути от бд к приложению?

**Comment by KharlamovaAlexandra** [comment]
@ZhezlovaDaria  я думаю ты можешь переделать эту задачу под те вопросы с которыми Стас тебе поможет разобраться

**Comment by YuriSilenok** [comment]
@ZhezlovaDaria необходимо отписать что вы решили по этому вопросу со Стасам

**Comment by ZhezlovaDaria** [comment]
@KharlamovaAlexandra  данные с БД проходят через php-функцию и возвращаются в виде JSON файла.
Проверяться будет уже содержимое самого файла.

**Comment by YuriSilenok** [comment]
По этой задаче ожидаются еще активности?

**Comment by KharlamovaAlexandra** [comment]
Нет
