### ISSUE TITLE
Авторизация организации в приложении на Android 

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#66]
Epic #61

Я как представитель благотворительной организации после того как увидел приветственный экран приложения должен увидеть экран выбора роли.

Я нажимаю на пункт Организация и перехожу на страницу авторизации организации. [Согласно макету](https://drive.google.com/drive/folders/1dg-6EMgN457DhjY-hf4LnXhmBWy8_KbL) 

На странице авторизации я должен увидеть следующие элементы:

Белый фон
Логотип информационной  площадки ( вариант из подтвержденных:голубо - красный )

Поле ввода "Инн/почты"
Поле ввода "Пароль" 
Поля ввода в серой рамочке с закругленными краями, цвет текста так же серый (#ececec)
Кнопка "Авторизоваться" цвета (#006df9)
Ссылка "Забыли пароль?" прямо под кнопкой (#006df9) 
Ссылка "Создать аккаунт" внизу страницы (#006df9) 

предупреждения появляются в формате messagebox
messagebox белого цвета с закругленными краями по середине страницы
Текст в messagebox:
"Ошибка" цвета #7b7b7b ;
Информационное сообщение цвета #bababa
OK цвета #006df9

Критерии приемки:

если я ранее регистрировался, то у меня есть возможность авторизоваться по Инн/почте и паролю
После удачной авторизации я должен попасть на страницу ленты ( пока лента не реализована в личный кабинет )
если я ввел электронную почту не правильно, то я должен увидеть предупреждение "Пользователь не найден"
если я ввел пароль не правильно, то я должен увидеть предупреждение "Неверный пароль"

**Comment by ZhezlovaDaria** [comment]
В процессе
