### ISSUE TITLE
Авторизация благотворительной организации через Web

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#67]
Epic #61 

На главной странице сайта в меню, я как представитель благотворительной организации, должен увидеть раздел "Войти". При нажатии на этот раздел должно быть выпадающее меню с выбором Организация/Гражданин.

Я нажимаю на пункт Организация  и перехожу на страницу авторизации организации. [Согласно макету ](https://drive.google.com/drive/u/0/folders/17odWTPVos9KpwJ3Bhve2LBgZpWcsF2wi)

На странице авторизации я должен увидеть следующие элементы:
Фон цвета #324055
Логотип белого цвета в верхнем левом углу
Ссылки меню:  О нас , Вход , Регистрация в правом вернем углу [по утвержденным критериям](https://docs.google.com/document/d/1fDVUJFGRfAm5C-G3VlOjThgFCoTHOi1LUZlpstPbpMs/edit) 
Заголовок белого цвета АВТОРИЗАЦИЯ ОРГАНИЗАЦИИ 

- Поле ввода "Инн/почта"
- Поле ввода "Пароль"
Поля ввода имеют закругленные края и белую рамку-обводку. Текст в них так же написан белым цветом

- Кнопка "Войти" белого цвета с закругленными краями, цвет текста #324055
- Ссылка "Забыли пароль?" белого цвета под кнопкой войти

предупреждения появляются в формате messagebox
messagebox белого цвета с закругленными краями по середине страницы
Текст в messagebox:
"Ошибка" цвета #7b7b7b ;
Информационное сообщение цвета #bababa
OK цвета #006df9

**Критерии приемки:**

- если я ранее регистрировался, то у меня есть возможность авторизоваться по Инн/почте и паролю
- После удачной авторизации я должен попасть на страницу ленты ( пока лента не реализована в личный кабинет )
если я ввел электронную почту не правильно, то я должен увидеть предупреждение "Пользователь не найден"
если я ввел пароль не правильно, то я должен увидеть предупреждение "Неверный пароль"

**Comment by KharlamovaAlexandra** [comment]
Epic #61

**Comment by stasshtaub** [comment]
Вместо кнопки "Авторизоваться" - кнопка "Войти". При некорректных данных выводится ошибка "Пользователь не найден", т.к. сообщение "Не верная почта или пароль" запутает пользователя, когда он будет входить по инн.
А так да, задача готова

**Comment by KharlamovaAlexandra** [comment]
Окей

**Comment by KharlamovaAlexandra** [comment]
В тестирование
