### ISSUE TITLE
Создать макет для Web авторизации благотворительной организации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#68]
Story #67 

Авторизация производится по Инн/почте и паролю. Должна быть кнопка войти и забыли пароль. Остальное в соответствии с дизайном информационной платформы "Луч надежды"

Доставить соответствующие лэйблы на данную задачу

В комментариях прикрепить готовый макет

**Comment by stasshtaub** [comment]
Может по email'у ааторизовывать? Проще запомнить

**Comment by KharlamovaAlexandra** [comment]
Мы обсуждали это. У нас в идеале пользователь должен ввести или Инн или почту и сервер сам поймет что это. Как у Google. Так что стоит Сделать поле для ввода и того и того. Поправлю описание

**Comment by stasshtaub** [comment]
[Макет на гугл-диске](https://drive.google.com/open?id=1Jo5MWs9X-sUdu3hlIV7Sqk2diUlPtztB)

![Авторизация организации](https://user-images.githubusercontent.com/47520675/64973598-f7398b80-d8b3-11e9-8263-079de2ddc85b.jpg)

**Comment by KharlamovaAlexandra** [comment]
На странице авторизации я должен увидеть следующие элементы:
Фон цвета #324055
Логотип белого цвета в верхнем левом углу
Ссылки меню:  О нас , Вход , Регистрация в правом вернем углу [по утвержденным критериям](https://docs.google.com/document/d/1fDVUJFGRfAm5C-G3VlOjThgFCoTHOi1LUZlpstPbpMs/edit) 
Заголовок белого цвета АВТОРИЗАЦИЯ ОРГАНИЗАЦИИ 

- Поле ввода "Инн/почта"
- Поле ввода "Пароль"
Поля ввода имеют закругленные края и белую рамку-обводку. Текст в них так же написан белым цветом


- Кнопка "Войти" белого цвета с закругленными краями, цвет текста #324055
- Ссылка "Забыли пароль?" белого цвета под кнопкой войти

Расположение элементов на странице, размер элементов а так же используемые шрифты на усмотрение дизайнера

если я ввел электронную почту не правильно, то я должен увидеть предупреждение "Пользователь не найден"
если я ввел пароль не правильно, то я должен увидеть предупреждение "Неверный пароль"

предупреждения появляются в формате messagebox
messagebox белого цвета с закругленными краями по середине страницы
Текст в messagebox:
"Ошибка" цвета #7b7b7b ;
Информационное сообщение цвета #bababa
OK цвета #006df9

**Comment by KharlamovaAlexandra** [comment]
Добавить макеты с ошибками

**Comment by stasshtaub** [comment]
Мы же решили в каком-то из тасков, что одно макета для всех однотипных ошибок достаточно? 
[Макет ошибок на гугл-диска](https://drive.google.com/file/d/11YI_XESRHlGySDXawWi0w_qXwvslQc9t/view?usp=drivesdk)

**Comment by KharlamovaAlexandra** [comment]
Отлично, значит я могу закрывать задачу, спасибо
