### ISSUE TITLE
Создать макет для Android авторизации благотворительной организации

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#69]
Sorry #66 

Авторизация производится по Инн/почте и паролю. Должна быть кнопка войти и забыли пароль. Остальное в соответствии с дизайном информационной платформы "Луч надежды"

Доставить соответствующие лэйблы на данную задачу

В комментариях прикрепить готовый макет

**Comment by stasshtaub** [comment]
[Макет на диске](https://drive.google.com/open?id=1dg-6EMgN457DhjY-hf4LnXhmBWy8_KbL)

![Вход организации](https://user-images.githubusercontent.com/47520675/64975227-27cef480-d8b7-11e9-89c7-8e7ba088060a.jpg)

![Пользователь не найден](https://user-images.githubusercontent.com/47520675/64975228-28678b00-d8b7-11e9-94e4-6b03adee5c12.jpg)

**Comment by KharlamovaAlexandra** [comment]
На странице авторизации я должен увидеть следующие элементы:

Белый фон
Логотип информационной  площадки ( вариант из подтвержденных:голубо - красный )
Поле ввода "Инн/почты"
Поле ввода "Пароль" 
Поля ввода в серой рамочке с закругленными краями, цвет текста так же серый (#ececec)
Кнопка "Авторизоваться" цвета (#006df9)
Ссылка "Забыли пароль?" прямо под кнопкой (#006df9) 
Ссылка "Создать аккаунт" внизу страницы (#006df9) 

Расположение элементов на странице, а так же их размеры на усмотрение дизайнера

если я ввел электронную почту не правильно, то я должен увидеть предупреждение "Пользователь не найден" 
если я ввел пароль не правильно, то я должен увидеть предупреждение "Неверный пароль"

предупреждения появляются в  формате messagebox 
messagebox белого цвета с закругленными краями по середине страницы 
Текст в messagebox:  
"Ошибка" цвета #7b7b7b ;
 Информационное сообщение цвета #bababa 
 OK цвета #006df9

**Comment by KharlamovaAlexandra** [comment]
Доделать еще один макет об ошибке

**Comment by stasshtaub** [comment]
Зачем? Макет у всех ошибок одинаковый

**Comment by KharlamovaAlexandra** [comment]
На нем будет текст Неверный пароль

**Comment by KharlamovaAlexandra** [comment]
Я думаю что макеты должно быть под ве ситуации сделаны, если ты считаешь что в макете ничего не изменится кроме текста ошибки, тогда мы можем его не делать, я просто упомяну об этом в описание задачи

**Comment by stasshtaub** [comment]
не изменится
