### ISSUE TITLE
Выбрать технологии для настройки удаленного сервера

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#7]
Ознакомится с ситуацией и предложить технологии и способы настройки облачного сервера. Результат работы приложить в комментария в виде ссылки на гугл документ.

**Comment by KharlamovaAlexandra** [comment]
@YuriSilenok  Пожалуйста, уточните задание более конкретно.

**Comment by YuriSilenok** [comment]
Нам необхоодимо разместить вэб-приложение и БД.
Мы еще не определились с платформами. 
Возможно нам нужен будет обычный хостинг: который предоставляет:
- доменом третьего уровня - url
- attach php -  движек генерирующий страницы html
- MySQL. -  СУБД с доступон не только вэбсайту, к нему должена подключаться мобилка.

В основном этот выбор завите от того, на чем смогут разработать сайт.
На чем мы его можем разработать?

**Comment by KharlamovaAlexandra** [comment]
Вопрос о разработке сайта нужно перенаправить @stasshtaub ответственному за эту область

**Comment by YuriSilenok** [comment]
значит нужно повесить на него задачу, а то получается ты ей занимаешься.

**Comment by KharlamovaAlexandra** [comment]
Непонятно кто этой задачей должен заниматься Стас или Денис. За часть с сайтом отвечает Стас, за часть с сервером отвечает Денис

**Comment by YuriSilenok** [comment]
@Takunava протестировать возможность связи с БД из вне

@stasshtaub мы не знаем на чем Вы умеете писать сайты, [посмотрите](https://ru.000webhost.com/members/website/list), 
![image](https://user-images.githubusercontent.com/14871471/60588446-070efc80-9da8-11e9-953b-910e9a2377a4.png)
знакомо ли Вам что-то из этого?

**Comment by stasshtaub** [comment]
Пишу на html без cms и конструкторов

ср, 3 июл. 2019 г., 14:35 Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
То есть только сайты визитки?
Никакого динамического контента?

**Comment by stasshtaub** [comment]
С ним, с подключенным js

ср, 3 июл. 2019 г., 14:55 Юрий Силенок <notifications@github.com>:

**Comment by YuriSilenok** [comment]
Ок, js это хорошо

**Comment by KharlamovaAlexandra** [comment]
Что с этой задачей. Она закончена или её кто - то делает?

**Comment by YuriSilenok** [comment]
> Что с этой задачей. Она закончена или её кто - то делает?

Думаю можно закрыть, мне в общих чертах понятно как будет работать
