### ISSUE TITLE
Создать макет для Android авторизации гражданина

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#70]
Story #62

Авторизация производится по почте и паролю. Должна быть кнопка войти и забыли пароль. Остальное в соответствии с дизайном информационной платформы "Луч надежды"

Доставить соответствующие лэйблы на данную задачу

В комментариях прикрепить готовый макет

**Comment by stasshtaub** [comment]
[Макет на гугл-диске](https://drive.google.com/open?id=1UvGfDFK6YLuAYphbc2bw3sT2umBB05gX)

![Вход гражданина](https://user-images.githubusercontent.com/47520675/64976298-9a40d400-d8b9-11e9-9a1f-44ebff617295.jpg)

![Вход гражданина неправильный логин-пароль](https://user-images.githubusercontent.com/47520675/64976497-19360c80-d8ba-11e9-8bc2-8066fbfc3658.jpg)
