### ISSUE TITLE
Создать макет для Web авторизации гражданина

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#71]
Story #65 

Авторизация производится по почте и паролю. Должна быть кнопка войти и забыли пароль. Остальное в соответствии с дизайном информационной платформы "Луч надежды"

Доставить соответствующие лэйблы на данную задачу

В комментариях прикрепить готовый макет

**Comment by stasshtaub** [comment]
[Макеты на гугл-диске](https://drive.google.com/open?id=1UvGfDFK6YLuAYphbc2bw3sT2umBB05gX)


![Вход гражданина](https://user-images.githubusercontent.com/47520675/64975432-b17ec200-d8b7-11e9-8193-0c355f9e3eb0.jpg)

![Вход гражданина неправильный логин-пароль](https://user-images.githubusercontent.com/47520675/64975506-d96e2580-d8b7-11e9-9db3-d4b4c80191ce.jpg)

**Comment by stasshtaub** [comment]
[Макет на гугл-диске](https://drive.google.com/open?id=1SAHtVPfroWz78sk-kG_3NqVa9iXFjSeH)

![Авторизация гражданина](https://user-images.githubusercontent.com/47520675/64976265-85644080-d8b9-11e9-82b5-8f8b8b830ad2.jpg)

**Comment by KharlamovaAlexandra** [comment]
Меня устраивает, в тестирование
