### ISSUE TITLE
Отсутствует документация Дизайн для макетов в директории нашего проекта на Гугл диск 

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#75]
1. В [меню](https://rayofhope-opensource.000webhostapp.com/) web-версии "Луч надежды" текст светлеет при наведении на него курсора
2. В #25  задаче отсутствуют критерии приёмки.
3. Документ Дизайн для макетов с описанием данного функционала отсутствует.

Результат: Документация не соответствует функционалу.
Ожидаемый результат: Будет создан документ Дизайн для макетов с описанием функционала.

**Comment by KharlamovaAlexandra** [comment]
Тут нельзя ссылаться на story #20, так как тема стори не касается стартовой страницы. Тут должна быть упомянута задача про стартовые страницы, но у нас ее нет. Точнее у нас есть сама такая задача #25, но нет для нее не Story, ни эпика. Я думаю должен быть баг на то, что нет критериев приемки 25 задачи

**Comment by KharlamovaAlexandra** [comment]
#77 - решение
