### ISSUE TITLE
Отсутствует информация о функционале сообщения о письме подтверждения регистрации в Story номер #20 

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#76]
1. Корректно ввести все данные на [странице регистрации организации](https://rayofhope-opensource.000webhostapp.com/registration/org)
2. Появляется диалоговое окно о завершении регистрации, с возможностью нажать на кнопку "ОК"
3. В story #20 отсутствует информация о данном функционале, а также критерии приёмки в задаче #23 

Результат: Документация не соответствует функционалу.
Ожидаемый результат: Изменен Story #20  в соответствии с данным функционалом, добавлены критерии приёмки в задаче #23

**Comment by KharlamovaAlexandra** [comment]
Наверно стоит добавит об отсутствии критериев в задаче #23

**Comment by Parallusion** [comment]
> Наверно стоит добавит об отсутствии критериев в задаче #23

Изменено

**Comment by KharlamovaAlexandra** [comment]
Можно более подробное уточнение проблемы? Нужно само письмо или написать зачем оно нужно, или как оно должно выглядеть?

**Comment by Parallusion** [comment]
> Можно более подробное уточнение проблемы? Нужно само письмо или написать зачем оно нужно, или как оно должно выглядеть?

У тебя не написано в документации, как должно быть реализовано это сообщение (именно после нажатия на кнопку "Зарегистрироваться"). Я вижу два варианта:
1. После того как я нажимаю в появившемся messagebox кнопку "ОК" - осуществляется переход.
2. После того как сообщение повисело определенное время на экране - осуществляется переход.

То есть, не описано условие перехода на страницу пользователя после регистрации (либо же это нажатие на кнопку ОК в всплывающем окне, что скорее всего так и есть, но об этом я не видел информации в твоём Story, поэтому поднял баг на отсутствии информации о функционале).

**Comment by KharlamovaAlexandra** [comment]
После нажатия на конопку "Ок" пользователь попадает на страницу ленты, как в web версии так и в  мобильной

**Comment by KharlamovaAlexandra** [comment]
Обе story изменены
