### ISSUE TITLE
Тестирование авторизации на информационной площадке

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#78]
Epic #61
Результаты тестирования авторизации [в веб-версии](https://docs.google.com/spreadsheets/d/1QX80ipwa-VqxpP4v4vkhY62S_wfBev07Xq2Ys48WiyM/edit#gid=100933411) и [в Android-приложении](https://docs.google.com/spreadsheets/d/16dMIPuW4tlPUntkUoM8C1TRME36dK9TPxPu8maahwFE/edit#gid=66221483)

**Comment by KharlamovaAlexandra** [comment]
Тесты пишутся?

**Comment by KharlamovaAlexandra** [comment]
Какое безобразие

**Comment by MoL4okkk** [comment]
В результате тестирования были обнаружены баги, впоследствии исправленные и протестированные заново (успешно). Тестирование не завершено, так как неясно, завершилась ли работа над авторизацией гражданина. С сентября в этом направлении никаких изменений замечено не было.

**Comment by YuriSilenok** [comment]
> В результате тестирования были обнаружены баги, впоследствии исправленные и протестированные заново (успешно). Тестирование можно считать завершённым.

Баги были обнаружены, отлично, где агрегированные сведения о них?

**Comment by KharlamovaAlexandra** [comment]
@YuriSilenok Какие сведения???

Не хватает ссылок на всякие таблицы

**Comment by MoL4okkk** [comment]
> 
> Баги были обнаружены, отлично, где агрегированные сведения о них?


> 
> Не хватает ссылок на всякие таблицы

Добавил в дескрипшен

**Comment by KharlamovaAlexandra** [comment]
@MoL4okkk  Состояние задачи?

**Comment by MoL4okkk** [comment]
> Состояние задачи?

Выполнена
