### ISSUE TITLE
Профиль организации в  WEB

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#79]
Epic #74 

Я как представитель благотворительной организации хочу иметь возможность просматривать свой профиль с web версии информационной площадки

[макет](https://drive.google.com/drive/u/0/folders/1nXtCVTAtZKrseCSrJAFCIGpMzL_J_ouV) 

Цвет фона должен быть белым

В верху страницы должно быть меню по [утвержденными критериям](https://docs.google.com/document/d/1fDVUJFGRfAm5C-G3VlOjThgFCoTHOi1LUZlpstPbpMs/edit#heading=h.atsidu1di0do)

Должно отображаться фото организации - круглое с левой стороны

Название организцации по середине в верхнем регистре одним из допустимых цветов

Город  и тип организации под названием в одном из допустимых цветов 

Описание организации под типом и городом в виде блока с закругленными краями которое можно раскрыть( по нажатию на надпись "больше...") если текста внутри много ( по умолчанию отображать три строки )

Контакты организации состоящие из: адреса, телефона   находятся под описанием

Заголовок "документы организации:"  с правой стороны в одном из утвержденных цветов 
под ним
Документы в виде прямоугольников с закругленным краями на которых отображается главная страница самого документа ( не более трех штук изначально ) можно раскрыть остальные если нажать "больше..."

С левой стороны под фото организации  должно быть три кнопки ( нужды, мероприятия, события в данном порядке) кнопки с закругленными краями синего утвержденного цвета с белым текстом

Под основной информацией страницы будет кнопка синего утвержденного цвета с закругленными краями и белым текстом "Посмотреть записи организации" при нажатии на которую будут отображаться посты всех типов в порядке их публикации ( до этого посты не видно )

Во втором спринте не показывать на макетах посты и так же не реализовывать их

Размещение элементов на странице, используемые размеры и шрифты на усмотрение дизайнера 

Создать задачу на создание макета
Создать задачу на реализацию макета 
В каждой задаче пометить эпики 74 и стори 79

**Comment by stasshtaub** [comment]
> Описание организации под типом и городом в виде блока с закругленными краями

Скругленные края - это поля для ввода, они появляются только там, где можно редактировать. На странице просмотра профиля их не будет

**Comment by YuriSilenok** [comment]
> Скругленные края - это поля для ввода, они появляются только там, где можно редактировать. На странице просмотра профиля их не будет

Обрати внимание на комментарии или описание в задачах в режиме просмотра, они скруглены
Сможешь посмотреть как это сделано?

**Comment by stasshtaub** [comment]
Зачем? Это лишний элемент. Тут на гите он отделяет комменты друг от друга и от задачи, а у нас на странице организации выделять описание не надо, у него и так есть заголовок и общая подложка для всей информации. Это будет только захломлять макет. 
Вообще в задаче лучше сначала просто писать что должно быть на странице, а оформление согласовывать уже после первого макета, изменяя его пока не утвердим полностью

**Comment by KharlamovaAlexandra** [comment]
Вот на счет этого я согласна, лично мне было бы так работать проще. Мне сложно изначально полностью описывать желаемый вид макетов. Причем возможно даже макеты стоит делать на спринт раньше, чем их реализовывать

**Comment by YuriSilenok** [comment]
> Зачем?

Хотелка продуктовнера



> Вообще в задаче лучше сначала просто писать что должно быть на странице, а оформление согласовывать уже после первого макета, изменяя его пока не утвердим полностью

Мой комментарий не относился к тому как описывать задачи, а к тому что скругленные края нельзя сделать.

Или я не правильно понял обсуждение

**Comment by KharlamovaAlexandra** [comment]
Но тут ж есть на макете скрученные края

![Снимок экрана 2019-09-21 в 21 00 11](https://user-images.githubusercontent.com/47320583/65377285-d0fc5d00-dcb2-11e9-9788-820658db96dd.png)
Да и тут, и вообще еще много где
![Снимок экрана 2019-09-21 в 21 01 22](https://user-images.githubusercontent.com/47320583/65377309-ff7a3800-dcb2-11e9-94eb-cb60910c4e98.png)

**Comment by stasshtaub** [comment]
Когда я написал, что скругления эт поля для ввода, я думал что в описании задачи  перепутали макеты и поэтому написано скруглить описание (в макете редактирования профиля у всех текстовых элементов свой прямоугольник со скруглениями).
Да, у блока с типом записей есть скругления, т.к. это отдельный блок макета, не связанный с блоком инфы организации. А описание организации уже находится на подложке (общая для всей инфы организации). 
Если делать подложку со скруглениями для описания - оно будет вынесено в свой блок и отделено от всей другой инфы организации (то же самое что с типом записей, но для описания). Либо будет общая подложка для всей инфы организации, а в ней ещё одна скругленная подложка (другого цвета) под описание, и я все равно не понимаю зачем это

**Comment by KharlamovaAlexandra** [comment]
Я подумала, что раз описание организации можно свернуть и развернуть, то наверное его лучше сделать отдельным блоком. Но на макетах это в принципе выглядит и так нормально, так что можно обойтись без закруглений
