### ISSUE TITLE
Проанализировать архитектуру 

### ISSUE THREAD

**Issue by KharlamovaAlexandra** [Students-of-the-city-of-Kostroma/Ray-of-hope#8]
Проанализировать имеющуюся архитектуру мобильного приложения для информационной площадки "Луч надежды" и выявить проблемы. Результат работы приложить в комментария в виде ссылки на гугл документ.

**Comment by YuriSilenok** [comment]
Эта задача актуальна?

**Comment by KharlamovaAlexandra** [comment]
Да
