### ISSUE TITLE
Разработать макет страницы профиля организации для WEB

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#83]
Стори #79 
Эпик #74

**Comment by stasshtaub** [comment]
Выбери какой-то вариант из этих. 
Если оставлять посты изначально скрытыми (первый вариант), на странице будет много пустого места, плюс каждый раз придется делать лишний клик чтобы их открыть.
Во втором сразу отображаются посты (все какие есть), тип записей меняется в левом меню

![проиль организации 1](https://user-images.githubusercontent.com/47520675/65268391-b6de4580-db1f-11e9-97ff-b849ef4aa41f.jpg)

![проиль организации 2](https://user-images.githubusercontent.com/47520675/65268390-b645af00-db1f-11e9-88e0-12a95ec808fb.jpg)

**Comment by KharlamovaAlexandra** [comment]
Второй выглядит лучше, но мне не нравится на нем блок «+ новый пост». Он слишком большой и отвлекает внимание, хотя ключевым элементом страницы не является. Я бы убрала его.  И добавила + новая запись в блок все записи.

**Comment by KharlamovaAlexandra** [comment]
И еще наверно на втором макете перенесла бы редактировать профиль в правую часть (как на первом). А то под документами много пустого места, да и случайно кликать так будут меньше

**Comment by stasshtaub** [comment]
Насчёт места под документами, лучше сделать 6 документов вместо 3, как было сначала

**Comment by KharlamovaAlexandra** [comment]
Пусть будет 6, а как это будет выглядеть, если у них столько не загружено? Допустим если они всего 1 загрузили?

**Comment by stasshtaub** [comment]
Плохо

**Comment by stasshtaub** [comment]
Как че-нибудь придумаю, скину новый макет

**Comment by KharlamovaAlexandra** [comment]
Окей

**Comment by KharlamovaAlexandra** [comment]
Один документ я хотела бы наверно видеть как - то так, если это возможно. В целом он бы так и остался один в левом верхнем углу 

![IMG_0447](https://user-images.githubusercontent.com/47320583/65377320-1fa9f700-dcb3-11e9-9642-812a340ed421.jpeg)

**Comment by stasshtaub** [comment]
Кнопку редактирования переносить не стал, справа она не вписывается

![проиль организации 2](https://user-images.githubusercontent.com/47520675/65613013-f0023400-dfbd-11e9-8e33-24514b9e76f5.jpg)

С 1 доком будет так
![1 doc](https://user-images.githubusercontent.com/47520675/65613249-58511580-dfbe-11e9-9285-34b6415623a2.jpg)

**Comment by KharlamovaAlexandra** [comment]
Это макеты со взгляда гражданина? Откуда кнопка пожертвовать? 

И даже если так, то мне кажется она должна быть не внизу, а где - то в верху

**Comment by stasshtaub** [comment]
Это со стороны самой организации. Снизу это пост-нужда. У таких постов есть эта кнопка, так они хоть чем-то от событий внешне отличаются. Если убирать эту кнопку, надо будет подписывать у каждой записи ее тип. 
Со стороны гражданина будет ещё кнопка пожертвований в блоке с инфой организации

**Comment by KharlamovaAlexandra** [comment]
У нужды должен быть прогресс бар собранного, а не кнопка

**Comment by stasshtaub** [comment]
Ок. Со стороны гражданина и прогрессбар и кнопка? Куда-то надо будет нажимать, чтобы пожертвования засчитались именно в прогрессбар к конкретной нужде

**Comment by stasshtaub** [comment]
С прогрессбаром будет так
![проиль организации 2](https://user-images.githubusercontent.com/47520675/65689554-f6ec7d80-e075-11e9-8f4e-4177d28248f4.jpg)

**Comment by KharlamovaAlexandra** [comment]
Одобрено

**Comment by KharlamovaAlexandra** [comment]
У нас нельзя перечислить деньги конкретной нужде. Пост нужна собирает чисто вещи. деньги можно перечислить только в целом организации

**Comment by stasshtaub** [comment]
Тогда организация сама увеличивает счётчик у прогрессбара? Надо кнопку добавить для этого?

**Comment by KharlamovaAlexandra** [comment]
Я предполагала какой нибудь ползунок, которым они будут показывать прогресс, а над ползунком может какую нибудь штучку, куда они могли бы ввести точное число и ползунок сам бы встал на место

**Comment by stasshtaub** [comment]
Подсказка появляется, когда двигают или нажимают на ползунок, и пропадает через пару секунд если не двигают. Если нажать на число в подсказке - можно менять. Так?
![проиль организации 2](https://user-images.githubusercontent.com/47520675/65690929-a88cae00-e078-11e9-906b-4a90c3a85102.jpg)

**Comment by KharlamovaAlexandra** [comment]
Все верно
