### ISSUE TITLE
Проанализировать адреса благотворительных организаций

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#84]
Нужно посмотреть по каким адресам могут находится благотворительные организации. Проанализировать, как указывыются адреса на других сайтах. Например, как происходит разделение на деревню, город,  село. Какие вообще поля могут быть указаны. Результат работы приложить в комментарии в виде ссылки на гугл документ.

**Comment by Parallusion** [comment]
[Ссылка](https://docs.google.com/document/d/17MGJn4yC4Sdb9kmkXnAg25YHRGoSweVNullXsVrwxy0/edit?usp=sharing)

PS. Просьба комментарии и вопросы оставлять прямо в документе.

**Comment by KharlamovaAlexandra** [comment]
Перенеси документ на диск!!!!!!!!!!!!

**Comment by KharlamovaAlexandra** [comment]
После перенесения, закройте задачу

**Comment by Parallusion** [comment]
Перенес документ.
