### ISSUE TITLE
Неверный текст в сообщении о неверно введённом пароле 

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#85]
В стори #67 сказано, что при авторизации организации через WEB при верно заполненном первом поле и неверно введённом пароле должно выводиться сообщение "Неверный пароль".

  Фактически, при нажатии на кнопку "Войти" выходит messagebox с текстом "Пользователь не найден".

**Comment by stasshtaub** [comment]
исправил
![0000](https://user-images.githubusercontent.com/47520675/66126362-f877f180-e5f1-11e9-8512-04e521c22e74.JPG)
