### ISSUE TITLE
Внешний вид страницы не соответствует макету в мобильном приложении на android при попадании на экран выбора роли

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#86]
Шаги для воспроизведения бага:
1. Открыть приложение "Луч надежды" на android
2. Попадаем на страницу выбора роли.

Ожидаемый результат: Страница выбора роли соответствует макету.
Фактический результат: Страница выбора роли не соответствует макету.

**Comment by KharlamovaAlexandra** [comment]
Когда баг будет закрыт?

**Comment by YuriSilenok** [comment]
Выполнить действия аналогично [этому](https://github.com/Students-of-the-city-of-Kostroma/Ray-of-hope/issues/109#issuecomment-546580018) комментарию

**Comment by MoL4okkk** [comment]
Баг не воспроизводится в версии v.0.0.20191005.4 Android-приложения и более поздних
