### ISSUE TITLE
Реализовать страницу профиля организации для WEB

### ISSUE THREAD

**Issue by stasshtaub** [Students-of-the-city-of-Kostroma/Ray-of-hope#88]
Story: #79 
Макет: #83

**Comment by stasshtaub** [comment]
Верстка: https://rayofhope-opensource.000webhostapp.com/organisation/2 (чтобы открылось, надо [авторизоваться](https://rayofhope-opensource.000webhostapp.com/login/org))
Личный профиль организации открывается по клику на аватар в шапке (или по прямой ссылке с id организации, например, "/organisation/2")

**Comment by KharlamovaAlexandra** [comment]
Меня устраивает, можно предавать тестирование
