### ISSUE TITLE
Отсутствует вкладка "О нас" в макете меню приложения на Android 

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/Ray-of-hope#93]
[Макет](https://drive.google.com/drive/u/0/folders/1XbP9ZvoDuseL86tyvc696k-HxPJeYdzH) 

Ожидаемый результат: макет меню соответствует требованиям.
Фактический результат: макет меню не соответствует требованиям.

**Comment by stasshtaub** [comment]
Вроде не макет должен соответствовать приложению, а наоборот?

**Comment by Parallusion** [comment]
> Вроде не макет должен соответствовать приложению, а наоборот?

Поднимаю баг со слов Саши. Проблема конкретно в твоём макете, а не в приложении, так что в данном случае макет должен соответствовать приложению, если будет обратное, то в таком случае реализация уже неправильная, хотя она является корректной со слов Саши. Поэтому тут проблема именно в макете.

**Comment by stasshtaub** [comment]
А понял. Я просто подумал  что в приложении эта кнопка уже есть и вы хотите чтоб было так же в макете.
Макет завтра скину

**Comment by stasshtaub** [comment]
[Макет на гугл-диске](https://drive.google.com/open?id=1KxzjiOWwBpFpq5OxhgXAKdndoZhH8VRi

![Другое для организации](https://user-images.githubusercontent.com/47520675/65990670-af5e5b00-e494-11e9-807e-bf51e784a4ed.jpg)
