### ISSUE TITLE
Отсутствует кнопка "Больше" в профиле организации в WEB

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/Ray-of-hope#95]
1. Открываем профиль организации.
2. Под описанием организации должна отобразиться кнопка "Больше", показывающая полное описание (при условии, что данное описание содержит больше трёх строк).

Ожидаемый результат: отобразится кнопка "Больше".
Фактический результат: 
![Для скринов](https://user-images.githubusercontent.com/55210615/65996176-960edc00-e49f-11e9-97f6-b6f100476842.jpg)

**Comment by KharlamovaAlexandra** [comment]
Описание бага данный момент не верно

**Comment by stasshtaub** [comment]
исправил

![Снимок](https://user-images.githubusercontent.com/47520675/66231554-74a42f00-e6ef-11e9-98e5-6adef4517751.JPG)
